* Anmerkungen

Ethymologen: Ethymologen sind Wissenschaftler, die sich mit der Geschichte und der Bedeutung von Begriffen beschäftigen. Mauss erinnert mit der Erwähnung dieses Begriffs an seine Ausbildung im Kontext der Philologie von alten Sprachen.

Murray: Es handelt sich hier um den britischen Philologen und Lexikographen James Augustus Henry Murray (1837-1915), der der Hauptherausgeber des /Oxford English Dictionary/ war.

Kluge: Es handelt sich hier um den deutschen Sprachwissenschaftler und Lexikographen Friedrich Kluge (1856-1926), der der Hersaugeber des Werkes /Etymologisches Wörterbuch der deutschen Sprache/ war, das bis heute veröffentlicht wird.

Hirt: Hermann Hirt (1865-1936) war Germanist, Indogermanist und Philologe. Er hat das Buch /Etymologie der neuhochdeutschen Sprache/ verfasst, das die Herkunftsgeschichte deutscher Begriffe in andere Sprachen darstellt.

Euphemismus: Dieser Begriff meint die Beschreibung eines beschönigenden mildernden Wortes. In diesem Kontext handelt es sich um das Wort /gift/ in seiner Bedeutung als "Giftstoff", die durch die andere Bedeutung von /gift/ als Geschenk abgemildert wird.

venesnom: Wahrscheinlich /venenom/ als nominative Singularform neben venenum.

Das germanische Recht: Mauss verwendet diesen Sammelausdruck, um vom Stammesrecht der germanischen Völker (5.-9. Jahrhundert nach Christus) zu sprechen. Dieses Recht verband ein mündliches Gewohnheitsrecht mit römischen und kirchlichen Einflüssen.

Die Clans: Im Werk von Mauss und dem seines Onkels Émile Durkheim sind Clans die wichtigsten religiösen und sozialen Kleineinheiten der alten Gesellschaften, die symbolisch von einem Totem (Tier, Pflanze, Naturgegenstand) repräsentiert werden. In Clans herrscht eine starke soziale Kohäsion, die damit verbunden ist, dass die Mitglieder des Clans durch Verwandschaftsbeziehungen geeint werden.

Rückständige Gesellschaften: Mauss verwendet diesen Ausdruck, um von Gesellschaften zu sprechen, die entweder alte Gesellschaften oder Gesellschaften sind, die im Vergleich zu modernen Gesellschaften des 20. Jahrhundert nicht industrialisiert sind und nach anderen -- oft mündlichen -- Rechtsformen leben.

fosterage: Mauss bezieht sich auf das alte englische Wort /fostrian/, das der Bedeutung von "ernähren" nahe kommt.

Die Kelten: Der Begriff bezeichnet Stammesgruppen der Eisenzeit (800 vor Christus bis zum 1. Jahrhundert nach Christus), die gemeinsame soziale, kulturelle und religiöse Bräuche teilten und in Europa von Portugal bis in die Türkei gelebt haben. Den Begriff verwendet Mauss in Anlehnung an die Arbeiten von seinem engen Freund Henri Hubert (1872-1927), der im Bereich der Archeologie und der Geschichte der Kelten geforscht hat.

Chinook: Dieser Begriff bezeichnet die Chinook-Indianer der nordamerikanischen Pazifikküste, die für hochentwickelte Handelstätigkeit berühmt waren.

Sabir: Es handelt sich um das Turkvolk der nomadischen Sabirer (aus dem Arabischen /sabr/, was Geduld bedeutet), das im Kaukasus vom 5. bis 7. Jahrhundert gelebt hat.

Davy: Georges Davy (1883-1976) war ein Mitarbeiter von Marcel Mauss und Émile Durkheim. Er stand sowohl Mauss als auch Durkheim nahe und hat maßgeblich dazu beigetragen, die Rolle der Arbeiten der Durkheim-Schule für die Entwicklung der Soziologie der Nachkriegszeit in Frankreich hervorzuheben. In seiner Dissertation /La Foie Jurée/ antizipiert er Mauss Überlegungen zur Gabe, was zu einer Polemik im Rahmen der Durkheim-Schule führen wird, die wir in unserem Nachwort beschreiben.

Maori Recht: Mauss verweist auf das alte Maori Recht, das ein Gewohnheitsrecht ist und die Verbindung der Maori zur Natur, zum Stamm und dem Sakralen regelt.

Die deutsche Mythologie: Mauss spricht von der Mythologie der alten germanischen Gesellschaften mit ihren Göttern (die Asen), Helden (etwa Dietrich von Bern) und mit ihrer Schöpfungsgeschichte (aus dem Nichts zum Kosmos), die mündlich verbreitet wurde.

Amira: Es handelt sich um Karl von Amira (1848-1930), der "Deutsches Recht und Kirchenrecht" an der Universität Freiburg i.Br. und dann "Staatsrecht" an der Universität in München gelehrt hat.

Maurice Cahen: Maurich Cahen (1884-1926) ist ein französischer Germanist und Sprachwissenschaftler (Nordistik). Er ist der Neffe von Professor Sylvain Lévy, der auch ein enger Freund von Mauss war.

Tacitus: Hier ist der römische Historiker Cornelius Tacitus (58-120 nach Christus) gemeint, der unter anderem für seine Ethnographie der germanischen Völker berühmt geworden ist.

Huvelin: Paul-Louis Huvelin war ein Rechtshistoriker, der sich insbesondere im römischen Recht spezialisiert hat und Mauss sowie der Durkheim-Schule nahe stand.

nexum: Den Begriff nexum verwendet Mauss im Kontext des römischen Rechts mit Bezug auf die Bedeutung vom nexum sowohl als Bindung als auch als Schuldvertrag und Verpflichtung.

Die melanesischen Inseln Trobriands: Gemeint sind hier die Kiriwina-Inseln, eine melanesische Inselgruppe in der Salomonensee, die zu Papua-Neuguinea gehören. Mauss erwähnt sie unter Bezugnahme auf seinen Kollegen Bronisław Malinowski, einem Pionier der modernen Anthropologie, der auf den Trobriand-Inseln Feldforschung betrieben und die Ergebnisse dieser Forschung in seinem berühmten Buch /Argaunoten des westlichen Pazifik/ (1922) veröffentlicht hat, aus dem Mauss in seiner Fußnote 11 in /Gift, Gift/ zitiert.

Fehdehandschuhe: Es handelt sich um eine Redewendung, die eine formelle Herausforderung zum Streit oder zum Kampf bezeichnet. Der Ausdruck geht auf den Brauch zurück, dem Gegner einen Handschuh vor die Füße zu werfen, den dieser bei Annahme der Herausforderung aufhob. Im deutschsprachiger Raum wird diese Redewendung häufig mit Friedrich Schillers Ballade "Der Handschuh" (1798) verbunden.

Indo-europäische Sprachen: Es ist die größte Sprachfamilie der Welt, zu der fast alle Sprachen Europas (z.B. Deutsch, Englisch, Französisch, Russisch, Spanisch) sowie viele Sprachen in Asien (z.B. Hindi, Persisch, Kurdisch) gehören.

Aulu-Gelle: Es handelt sich um den römischen Schriftsteller und Jurist Aulus Gellius (125–nach 180 nach Christus), der im Bereich der Rhetorik und der Grammatik tätig war.

φáρμακον: Das griechische Wort Pharmakon verwendet Mauss als Beispiel der Ambivalenz von /Gift, Gift/, da Pharmakon sowohl Gift als auch Heilmittel bedeutet.

Homer: Homer ist der traditionelle Name des antiken griechischen Dichters, der als Urvater der europäischen Literatur gilt.

Lex Cornelia de Sicariis et Veneficis: Hier handelt es sich um ein römisches Gesetz zur Bestrafung von Tötungsdelikten mit Waffen oder mit Gift. Cicero erwähnt Mauss in diesem Zusammenhang, weil Cicero zu der Definition von Vergiftung als Tötungsdelikt beigetragen hat.

Cicero: Marcus Tullius Cicero (106 vor Christus-43 vor Christus) war der berühmteste Redner des alten Rom sowie Anwalt, Philosoph, Schriftsteller und Politiker. Er hat zur Rezeption der griechischen Philosophie beigetragen.

Φθτρον: Mauss verwendet dieses Wort, um Getränke zu bezeichnen, die aus Pflanzen und Getreide hergestellt wurden.

Emerson: Mauss verweist auf den nordamerikanischen Schriftsteller und Philosophen Ralph Waldo Emerson (1803-1882) in seinem Werk zur Gabe. Er bezieht sich auf Emerson und dessen Arbeiten, um plausibel zu machen, warum die Gabe ein Mittel ist, eine intime Verbindung mit anderen zu entwickeln.

Pro Cluentio: Hierbei handelt es sich um eine berühmte Rede von Cicero. Mauss bezieht sich insbesondere auf den zweiten Teil der Rede, u.a. mit der Erwähnung des Giftmordes.

bonum, sive malum: Der lateinische Ausdruck bedeutet "das Gute oder Böse".

van, vanati: Es handelt sich hier um die verbale Wurzel und die konjugierte Form von /van/, die in Sanskrit lieben, begehren, verehren, gewinnen, erlangen, helfen oder mögen bedeuten kann.

v. Walde: Es handelt sich um den österreichischen Indogermanist, Altphilologen und Sprachwissenschaftler Alois von Walde (1869-1924), der das /Lateinisches etymologisches Wörterbuch/ (1910) herausgegeben hat.
