* Anmerkungen

Ethymologen: Ethymologen sind Wissenschaftler, die sich mit der Geschichte und die Bedeutung von Begriffen beschäftigen. Mauss erinnert hiermit an seine Ausbildung im Kontext der Philologie von alten Sprachen.

Murray: Es handelt sich um den britischen Philologen und Lexikographen James Augustus Henry Murray (1837-1915), der der Hauptherausgeber vom /Oxford English Dictionary/ war.

Kluge: Es handelt sich um den deutschen Sprachissenschaftler und Lexikographen Friedrich Kluge (1856-1926), der der Hersaugeber vom /Etymologisches Wörterbuch der deutschen Sprache/ war, das bis heute veröffentlicht wird.

Hirt: Hermann Hirt (1865-1936) war Germanist, Indogermanist und Philologe. Er hat das Buch /Etymologie der neuhochdeutschen Sprache/ verfasst, das die Herkunftsgeschichte deutscher Begriffe in andere Sprachen darstellt.

Euphemismus: Es ist ein Begriff zur Beschreibung eines beschönigenden mildernden Wortes. In diesem Kontext handelt es sich um das Wort /gift/ in seiner Bedeutung als "Giftstoff", die durch die andere Bedeutung von /gift/ als Geschenk abgemildert wird.

venesnom: Wahrscheinlich /venenom/ als nominative Singularform neben venenum.

Das germanische Recht: Mauss verwendet diesen Sammelausdruck, um vom Stammesrecht der germanischen Völker (5.-9. Jahrhundert nach Christus) zu sprechen. Dieses Recht verband ein mündliches Gewohnheitsrecht mit römischen und kirchlichen Einflüssen.

Die Clans: Im Werk von Mauss und von seinem Onkel Emile Durkheim sind Clans die wichtigsten religiösen und sozialen Kleineinheiten der alten Gesellschaften, die symbolisch von einem Totem (Tier, Pflanze, Naturgegenstand) repräsentiert werden. In Clans herrscht eine starke soziale Kohäsion, die damit verbunden ist, dass die Mitglieder des Clans durch Verwandschaftsbeziehungen geeint werden.

Rückständige Gesellschaften: Mauss verwendet diesen Ausdruck, um von Gesellschaften zu sprechen, die entweder alte Gesellschaften oder Gesellschaften sind, die im Vergleich zu modernen Gesellschaften des 20. Jahrhundert nicht industrialisiert sind und nach anderen -- oft mündlichen -- Rechtsformen leben.

fosterage: Mauss bezieht sich auf das alte englische Wort /fostrian/, das der Bedeutung von "ernähren" nah kommt.

Die Kelten: Der Begriff bezeichnet Stammesgruppen der Eisenzeit (800 vor Christus bis zum 1. Jahrhundert nach Christus), die gemeinsame sozialen, kulturellen und religiösen Bräuche teilten und in Europa vom Portugal bis Türkei gelebt haben. Der Begriff verwendet Mauss in Anlehnung an die Arbeiten von seinem engen Freund Henri Hubert (1872-1927), der im Bereich der Archeologie und der Geschichte der Kelten geforscht hat.

Chinook: Es sind die Chinook-Indianer der nordamerikanischen Pazifikküste, die für hochentwickelte Handelstätigkeit berühmt waren.

Sabir: Es handelt sich um das Turkvolk der nomadischen Sabirer (aus dem Arabischen /sabr/, das Geduld bedeutet), das im Kaukasus vom 5. bis 7. Jahrhundert gelebt haben.

Davy: Georges Davy (1883-1976) war ein Mitarbeiter von Marcel Mauss und Emile Durkheim, der eng mit ihnen verbunden war und dazu beigetragen hat, die Rolle der Arbeiten der Durkheim-Schule für die Entwicklung der Soziologie der Nachkriegszeit in Frankreich hervorzuheben. In seiner Dissertation /La Foie Jurée/ antizipiert er Mauss Überlegungen zur Gabe, was zu einer Polemik im Rahmen der Durkheim-Schule führen wird, die wir in unserem Nachwort beschreiben.

Maori Recht: Mauss verweist auf das alte Maori Recht, das ein Gewohnheitsrecht ist, das die Verbindung der Maori mit Natur, Stamm und dem Sakralen regelt.

Die deutsche Mythologie: Mauss spricht von der Mythologie der alten germanischen Gesellschaften mit ihren Göttern (die Asen), Helden (etwa Dietrich von Bern) und mit ihrer Schöppfungsgeschichte (aus dem Nichts zum Kosmos), die mündlich verbreitet wurde.

Amira: Es handelt sich um Karl von Amira (1848-1930), der das deutsche Recht und das Kirchenrecht an der Universität Freiburg i.Br. und dann das Staatsrecht an der Universität in München gelehrt hat.

Maurice Cahen: Maurich Cahen (1884-1926) ist ein französischer Germanist und Sprachwissenschaftler (Nordistik), der der Neffe vom Professoren und Mauss' engem Freund Sylvain Lévy war.

Tacitus: Es ist der römische Historiker Cornelius Tacitus (58-120 nach Christus), der unter anderem für seine Ethnographie der germanischen Völker berühmt ist.

Huvelin: Paul-Louis Huvelin war ein Rechtshistoriker nah an Mauss und der Durkheim-Schule, der sich insbesondere im römischen Recht spezialisiert hatte.

nexum: Der nexum verwendet Mauss im Kontext des römischen Rechts mit Bezug auf die Bedeutung vom nexum sowohl als Bindung als auch als Schuldvertrag und Verpflichtung.

Die melanesischen Inseln Trobriands: Es sind die Kiriwina-Inseln, die eine melanesische Inselgruppe in der Salomonensee sind und zu Papua-Neuguinea gehören. Mauss erwähnt sie in Verbindung mit seinem Kollegen Bronisław Malinowski, einem Pionier der modernen Anthropologie, der seine Feldforschung auf den Trobriand-Inseln entwickelt hat und daraus sein berühmtes Buch /Argaunoten des westlichen Pazifik/ (1922) veröffentlicht hat, das Mauss in seiner Fußnote 11 in Gift, Gift zitiert.

Fehdehandschuhe: Es ist eine Redewendung, um eine formelle Herausforderung zum Streit oder Kampf zu benennen. Der Ausdruck geht auf den Brauch zurück, dem Gegner einen Handschuh hinzuwerfen, den dieser bei Annahme der Herausforderung aufhob. Im deutschsprachiger Raum wird diese Redewendung häufig mit Friedrich Schillers Ballade "Der Handschuh" (1798) verbunden.

Indo-europäische Sprachen: Es ist die größte Sprachfamilie der Welt, zu der fast alle Sprachen Europas (z.B. Deutsch, Englisch, Französisch, Russisch, Spanisch) sowie viele in Asien (z.B. Hindi, Persisch, Kurdisch) gehören.

Aulu-Gelle: Es handelt sich um der römische Schriftsteller und Jurist Aulus Gellius (125–nach 180 nach Christus), der im Bereich der Rhetorik und der Grammatik tätig war.

φáρμακον: Das griechische Wort Pharmakon verwendet Mauss als Beispiel der Ambivalenz von Gift, Gift, da Pharmakon sowohl Gift als auch Heilmittel bedeutet.

Homer: Homer ist der traditionelle Name des antiken griechischen Dichters, der als Urvater der europäischen Literatur gilt.

Lex Cornelia de Sicariis et Veneficis: Es ist ein römisches Gesetz zur Bestrafung von Tötungsdelikten mit Waffen oder mit Gift. Cicero erwähnt Mauss in diesem Zusammenhang, weil Cicero an der Definition von Vergiftung als Tötungsdelikt beigetragen hat.

Cicero: Marcus Tullius Cicero (106 vor Christus-43 vor Christus) war der berühmteste Redner des alten Rom sowie Anwalt, Philosoph, Schriftsteller und Politiker. Er hat zur Rezeption der griechischen Philosophie beigetragen.

Φθτρον: Mauss verwendet dieses Wort, um Getränke zu bezeichnen, die mit Pflanzen und Getreiden hergestellt wurden.

Emerson: Mauss erwähnt den nordamerikanischen Schriftsteller und Philosophen Ralph Waldo Emerson (1803-1882) für sein Werk zur Gabe als ein Mittel, eine intime Verbindung mit den anderen zu entwickeln.

Pro Cluentio: Eine berühmte Rede von Cicero. Mauss bezieht sich hier insbesondere auf den zweiten Teil der Rede mit u.a. die Erwähnung vom Giftmord.

bonum, sive malum: Der lateinische Ausdruck bedeutet "das Gute oder Böse".

van, vanati: Es sind die verbale Wurzel und die konjugierte Form von /van/, die lieben, begehren, verehren, gewinnen, erlangen, helfen oder mögen im Sanskrit bedeuten können.

v. Walde: Es handelt sich um den österreichischen Indogermanist, Altphilologen und Sprachwissenschaftler Alois von Walde (1869-1924), der das /Lateinisches etymologisches Wörterbuch/ (1910) herausgegeben hat.
