#+Setupfile: /home/cpsoz/OrgTemplates/odt-de.org
#+bibliography: Mauss-Bib.bib
#+bibliography: MMOeuvres.bib
#+bibliography: ToenniesMauss-Bib.bib

* Kommentar

Wann Mauss /Gift, Gift/ verfasst, kann nicht mit Sicherheit ermittelt werden. 1922 erscheint der Text in der Festschrift zu Charles Andler. Aber es bleibt fraglich, ob ihn Mauss speziell für diese Angelegenheit vorbereitet oder schon früher bzw. vor dem Krieg verfasst hat. Inhaltlich behandelt Mauss in /Gift, Gift/ Themen, die in enger Verbindung mit den Themen stehen, die Mauss in seiner jungen Karriere mit Hubert herausgearbeitet hat. Es geht um die magischen und religiösen Phänomenen verschiedener Gesellschaften und Kulturen auf den fünf Kontinenten mit besonderer Berücksichtigung der melanesischen Inseln in der Pazifik, der einheimischen Stämmen Nordamerikas, der alten indoeuropäischen Gesellschaften. Es geht auch speziell um eine Vielfalt von Gabenpraktiken, die Mauss zumindest seit seinen Arbeiten zu den Opferriten und der Magie aus den Jahren 1899-1903 mit Durkheim und Hubert regelmäßig behandelt. Mit der Rückkehr zur Zivilleben und zur Forschung fragt sich Mauss im Dialog mit Hubert,[fn:1] ob ein solches Phänomen wie die Gabe nicht ein eigenes Werk verdienen würde, etwa im Rahmen einer neuen Betrachtung der Magie oder der neuen Behandlung vom unvollendeten Gebettext vertieft werden sollte,[fn:2] den Mauss vor dem Ersten Weltkrieg zu einer Dissertation anfertigen wollte. Aber der Weg zurück an die Arbeit ist steinig. Vom Oktober 1921 bis August 1922 leidet Mauss unter einer Lugenkrankheit, die ihn erschöpft. Wenn er wieder gesund ist, warten auf ihn seine wichtigere Projekte, die er unbedingt zum erfolgreichen Ende bringen will,[fn:3] nämlich sein geplantes Buch zum Thema der Nation und die Nachfolge von /L'Année sociologique/. Die Texte wie /Gift, Gift/, die dazwischen kommen, sind zwar auch nicht unwichtig, weil sie Mauss erlauben, seine Überlegungen zu Gabenpraktiken weiter zu entwickeln. Allerdings sollten sie ihn nicht zu lange aufhalten, weshalb sie eher kurz sein sollten und unmittelbar zum Argument kommen, das Mauss vorschlägt. /Gift, Gift/ zeigt es beispielhaft: Der Text ist kurz und dessen zentrale Botschaft schnell ermittelt: Gaben sind ambivalent bzw. sind Geschenke sowie Giftstoffe. Am Ende von /Gift, Gift/ wird den Status von diesem Text bestätigt: Er soll eine Einführung in die Komplexität von Gaben und Gabenpraktiken liefern, die zu einem späteren Zeitpunkt -- nämlich im späteren Essay /Die Gabe/ (1925) -- weiter entwickelt werden.

/Gift, Gift/ fängt mit der Erwähnung der zwei Bedeutungen von Gift als Geschenk und Giftstoff an, wobei die Verbindung zwischen beiden Begriffen auf Deutsch, Englisch und Holländisch nicht eindeutig geklärt ist. Weil ihn die Literatur zum Begriff "Gift" nicht zufriedenstellt, schlägt Mauss eine Hypothese vor: Die Bedeutungen von "Geschenk" und "Giftstoff" wurden im Begriff "Gift" miteinander verbunden, um die Bedeutung von Gift als Giftstoff abzumildern bzw. um die Gefahr, die die Bedeutung von "Gift" als Giftstoff enthält, zu dämpfen und die Verwendung des Begriffes zu ermöglichen. In diesem Zusammenhang gibt es eine unmittelbare Verbindung zu den Arbeiten vom Studenten und Freunden Mauss' Robert Hertz (1881-1915) insbesondere in Bezug auf die religiöse Polarität und die Sühne in den alten Gesellschaften.[fn:4] Hertz ist nicht nur der Kameraden im Rahmen des politischen Engagements im Sozialismus an der Seite von Mauss. Er ist auch derjenige, davon Mauss wie Durkheim dachten, dass er die Zukunft der Durkheim-Schule darstellen würde.[fn:5] Insbesondere mit seiner Studie zur Vorherrschaft der rechten Hand gibt Hertz Durkheims These der Dualität im Menschen neue Dimensionen. Nach Durkheim ist der Mensch ein /homo duplex/ in diesem Sinne, dass er zwei Bewusstseinzustände einverleibt.[fn:6] Der erste Bewusstseinzustand führt zur Entwicklung einer individuellen Persönlichkeit und der zweite Bewusstseinszustand zur Entwicklung einer sozialen Bewusstsein. Nach Durkheim setzt diese Dualität im Menschen die grundsätzlichere Dualität zwischen dem Sakralen und dem Profanen voraus: Die zwei unterschiedlichen Bewusstseinszustände sind aus dieser grundsätzlichen Unterscheidung zwischen dem Sakralen und dem Profanen entstanden. Hertz verallgemeinert diese These Durkheims insofern, als er die innerliche Dualität im Menschen auf die Ebene einer Dualität zwischen Natur und Gesellschaft bringt. Einerseits gibt es profane Gegenstände, die gleichzeitig symbolisch mit dem Bösen, dem Schlechten, dem Unreinen assoziiert werden, die allesamt Merkmale sind, die mit der linken Hand verbunden sind. Andererseits gibt es das Gegenteil bzw. das Sakrale, das gleichzeitig das Gute, das Reine, das Richtige, die mit der rechten Hand assimiliert werden. Diese Dualität innerhalb vom Menschen spiegelt sich außerhalb von ihm in der Form von Klassifikationssystemen wider, die auf die alltäglichen Gegenstände sowie in der Aufteilung des Raumes und der Zeit, der sozialen Rollen und Berufen, in der Hierarchisierung der Götter, der Teilung der Geschlechter und der Generationen verwendet werden. Wie Mauss in /Gift, Gift/ sagt, die Vielfalt der Gaben ruht auf einem breiten Spektrum an Bedeutungen zwischen dem Sakralen und dem Profanen, davon sie jeweils einen Aspekt des asymmetrischen Verhältnisses zwischen diesen Polaritäten bezeichnen, weil die Gaben immer an diese untrennbare Unterscheidung zwischen dem "Geschenk" und dem "Giftstoff" verweisen, die die untrennbare Beziehung zwischen dem Sakralen und dem Profanen im Alltag der Austauschpraktiken in diesen Gesellschaften der Gabe übersetzt. Zusammen betrachtet, bilden diese Gaben eine Totalität von Dienstleistungen, die an die Totalität der Gesellschaft erinnert, die unmittelbar oder mittelbar an solchen Dienstleistungen teilnimmt.

Deshalb spricht Mauss in /Gift, Gift/ von der Gaben als System der totalen Leistungen bzw. der juristischen, politischen, ökonomischen und religiösen Leistungen. Mit dem Begriff der Leistung verdeutlicht er das rechtliche Merkmal der Gaben: Gaben werden als Folge der Schließung von einem Vertrag getätigt. Mit dem Attribut "total" sagt Mauss, dass diese Leistungen alles betreffen, was in Unterstützung von Dritten getan werden kann. In einem späteren Text erklärt Mauss: "eine Gruppe von Menschen, ob hierarchisch organisiert oder nicht, schuldet einer bestimmten Anzahl anderer Menschen, Verwandten oder Verbündeten, die einen symmetrischen Platz beziehen (übergeordnet oder gleichwertig oder untergeordnet oder unterschiedlich aufgrund des Geschlechts), eine ganze Reihe moralischer und materieller Leistungen (Dienste, Frauen, Männer, militärischer Hilfe, ritueller Speisen, Ehren, usw.), und sogar die ganze Reihe dessen, was ein Mensch für einen anderen tun kann. Im Allgemeinen werden diese totalen Leistungen von Klan zu Klan, von Altersklasse zu Altersklasse, von Generation zu Generation, von Verbündeten zu Verbündeten erbracht. (...) Im Allgemeinen erfolgen diese Leistungen innerhalb dieser Gruppen und von Gruppe zu Gruppe entsprechend dem Rang der einzelnen Personen".[fn:7] In /Gift, Gift/ wie in /Die Gabe/ spricht Mauss von einem "System" der totalen Leistungen, und mit diesem Begriff "System" unterstreicht er zwei Merkmale der Gaben: a) die Gaben bilden in den unterschiedlichen Gesellschaften eine Einheit von sozialen Leistungen, die mehr oder weniger homogen sind und sich von anderen gesellschaftlichen Praktiken unterscheiden; b) diese Einheit entsteht aus der (unmittelbaren oder mittelbaren) Integration aller Menschen einer sozialen Gruppe bzw. einer Gesellschaft in die Gabenpraktiken. Mit dem ersten Merkmal sagt Mauss, dass Gabenpraktiken in der Gesellschaft nicht ständig stattfinden, sondern es gibt Bedingungen, die erfüllt werden müssen, damit Gabenpraktiken entwickelt werden. Diese Bedingungen spiegeln sich in der Vielfalt der Namen von Gaben wider, die geleistet werden, und sie verorten diese Gaben in der Vielfalt der Praktiken in einer Gesellschaft. Etwa die Mitgift, die Mauss in /Gift, Gift/ erwähnt, bezeichnet im Allgemeinen das Heiratsgut der Braut an die Familie des Bräutigames, das in der Hochzeitzeremonie mitgegeben wird. Die Morgengabe ist eine nähere Bezeichnung der Mitgift als das Heiratsgut der Braut, das am Morgen vor der Hochzeitzeremonie geleistet wird. Mit diesem zweiten Merkmal verdeutlicht Mauss, dass die Gabenpraktiken eine Wirkung auf den Zusammenhalt der Gesellschaft haben, den sie stärken. Weil die Gabenpraktiken alle Menschen in einer Gesellschaft direkt oder indirekt einbeziehen, tragen sie entsprechend zur engeren gesellschaftlichen Kohäsion, die die Wirkung auf die Akteure in dieser Gesellschaft hat, dass sie ihre Gesellschaft als Einheit aus der Praxis der Gaben besser wahrnehmen können, sie sich besser vorstellen können. Hier findet man nochmal die Verbindung mit der grundsätzlichen Unterscheidung zwischen dem Sakralen und dem Profanen, die das gesellschaftliche Leben strukturieren: Anhand von Gaben geben sich die Menschen die Möglichkeit, es zu wissen, wo sie sich als gesellschaftliche Einheit in diesem Verhältnis zwischen dem Sakralen und dem Profanen befinden, um Korrekturmechanismen zu verwenden, wenn dieses Verhältnis drohen würde, gestört bzw. geschwächt zu werden. Einer dieser Korrekturmechanismen ist der /potlatch/.

Mauss wird von dem /potlatch/ in /Die Gabe/ ausführlich reden, und in /Gift, Gift/ liefert er eine Zusammenfassung der wesentlichen Merkmale vom dieser Form von Gaben, die er als "agonistische[n] totalen Leistungen" bezeichnet. Solche Leistungen werden im Rahmen von Gabenpraktiken getätigt werden, die alle ein Element der Herausforderung enthalten. Eine Herausforderung kann nur eine Partei des Gabentausches betreffen, der seinen Wert als guter Partner im Gabenaustausch belegen muss. Sie kann beide Parteien betreffen, die sich gegenseitig als gleichwertig im Rahmen von Ehrenkämpfen zeigen müssen. Sie kann auch die ganze Gesellschaft betreffen, die ihre Stärke als Kollektiv belegen muss. Nicht nur die Rivalität und die Revanche stehen auf dem Spiel, die eine Konkurrenz zwischen den Parteien im Gabentausch um die beste Leistung unterstützen, die sie bringen müssen, sondern auch die Formen der Zerstörung von Vermögen als Korrektur von gesellschaftlichen Asymmetrien. Bei Gabenpraktiken in der Form von agonistischen Leistungen geht es nicht ausschließlich nur darum, dass man sich als Herrscher und Gewinner im Tausch zeigt, sondern auch dass man viel Leid und Verlust mit Leichtigkeit und Ausdauerkraft ertragen kann. In beiden Fällen von Gewinnen und Verlusten zeigen die Menschen und Kollektiven nicht nur ihre Durchsetzungskraft im Umgang mit Herausforderungen, die ihnen von ihren Austauschpartnern gestellt werden. Sie belegen auch ihre Zuverlässigkeit als diese Austauschpartner, mit denen es in nächsten Gabenaustauschen gerechnet werden kann, um die Komplexität der Gabenpraktiken und die Gefahren, die mit Gaben einhergehen, zu beherrschen. Im Kontext dieser Einordnung des /potlatch/ in den Gabenpraktiken ist es für Mauss nach wie vor wichtig, es zu präzisieren, dass diese Praktiken nicht nur bei den einheimischen Stämmen Nordamerikas zu finden sind, wie Franz Boas davon in seinem Buch zu den Kwakiutl berichtet hat,[fn:8] sondern auf auf den melanischen Inseln sowie bei den Kelten und den Germanen. Mit diesem Argument geht es bei Mauss darum, es nahezulegen, dass die Gabenpraktiken vielleicht überall in den unterschiedlichen Gesellschaften der Welt entwickelt worden sind. Besonders wichtig ist hier ebenfalls die Aussagen, dass solche Formen von agonistischen Gabenpraktiken bei den Kelten festzustellen seien, und dass sie ihre Spuren bis im alten keltischen Recht hinterlassen haben. In diesem Zusammenhang geht es Mauss nicht darum, an das Organisationsprinzip der soziologischen Untersuchung zu erinnern, die die Besonderheit der Arbeiten der französischen Soziologieschule ausgemacht hat: Unsere Gesellschaften nicht nur mit alten Gesellschaften in der Geschichte zu vergleichen, sondern auch mit Gesellschaften aus anderen Kulturen in der ganzen Welt. Es geht auch ganz konkrete um Korrekturen und Einordnungen von Dissonanzen, die in der Zeit der Veröffentlichung von /Gift, Gift/ Mauss überrascht, weil sie aus dem eignen Stahl kommen und in einer Polemik um die Dissertation von Georges Davy kristallisiert werden.[fn:9] Philippe Besnard hat damals einen berühmten Aufsatz zu dieser Polemik geschrieben und die Lage der Verhältnisse in der zweiten Generation der Durkheim-Schüler vertieft.[fn:10] Diese Generation ist aus den Studierenden entstanden, die bei Durkheim und auch bei Mauss studiert haben. Davy hat bei Mauss an der /Ecole Pratiques des Hautes Etudes/ die Lehrveranstaltungen besucht, in denen Mauss um 1910 von religiösen Begriffen in alten Gesellschaften und darunter vom /potlatch/ spricht. In seiner Dissertation verwendet Davy den /potlatch/, um die Gabenleistungen zwischen Familien in alten Gesellschaften und bei den Einheimischen Nordamerikas zu benennen. Er zeigt, dass solche /potlatch/ nicht nur im Kontext von ritualen Wettbewerben zwischen Klans oder von Festen auftauchen, sondern auch in Bezug auf die Verwandschaft und die Bindung von Allianzen zwischen Familien, die sie strukturieren. Aus dem potlatch entstehen die ersten Formen von durch Gaben formalisierten Allianzen und ferner die Grundlage des Rechtes.

Diese Schlußfolgerung überrascht Mauss, der Davy schreibt: "Sie sind meiner Unterscheidung zwischen Gesellschaften mit umfassenden Verträgen (Phratrie zu Phratrie; Klan zu Klan, die einfach gegeneinander stehen) und solchen mit umfassenden Verträgen agonistischer Art -- oder Potlatch -- nicht gefolgt. Sie verwechseln Gattung und Art. Ihre Überlegungen zur Ehe sind richtig und passen zur Gattung; es ist sinnlos und gefährlich, den Anschein zu erwecken, sie auf den Potlatch, die Art, zu beschränken".[fn:11] Weiter erwähnt Mauss, dass Davy behauptet, die Gesellschaften, die den /potlatch/ praktisieren, wie etwa die von Boas beobachteten Kwakiutl, arm seien. Aber nach Mauss "ist der Potlatch nur in relativ reichen Gesellschaften möglich".[fn:12] Nichtsdestotrotz bleibt Mauss tröstend, und er versichert Davy, dass all dies "zwischen uns" bleibt, "bis ich Gelegenheit habe, öffentlich zu sagen, wie sehr mir Ihr Buch gefällt".[fn:13] Diese Gelegenheit stellt sich nicht alsbald vor, denn Mauss, der als Mitglied der Promotionskommission zur Dissertation Davys fungieren muss, kann nicht kommen. In seinem Brief an Hubert schreibt er: "ich wollte mein Abendessen beschleunigen, ich habe meinen alten Feldkocher angezündet und dabei es geschafft, mich dummerweise die Hälfte meines linken Fußes zu verbrühen. (...) In einem Sinne kommt mir dieser kleine Unfall ganz gelegen. Der hat mir erlaubt, an der Dissertation von Davy nicht teilzunehmen".[fn:14] Auf Bitte von Mauss ersetzt ihn Marcel Granet in der Promotionskommission, der Davy gut kennt, weil sie zusammen an der /Ecole Normale Supérieure/ studiert haben und Stipendiaten der Stiftung Thiers gewesen sind. Beide haben ebenfalls die Lehrveranstaltungen von Mauss besucht, die sie stark beeindruckt haben. Die Verteidigung wird mit der Benotung /très honorable/ (Magna Cum Laude) am 01.04.1922 scheinbar ohne bemerkenswerte Auffälligkeit abgeschlossen. Aber im Dezember 1922 erscheint eine Besprechung von Granet zu den letzten Arbeiten der Mitglieder der Durkheim-Schule und darunter zur Dissertation Davys. In diesem Zusammenhang wiederholt Granet nicht nur die Kritiken, die Mauss in seinem Brief erwähnt hat, sondern Granet betont auch, dass Davy nicht genug erwähnt, von wem er sein Material und seinen Ansatz zur Verbindung des /potlatch/ und des Rechtes zieht. Er legt nah, dass sich Davy bei Mauss bedient und ihm die Vorherrschaft in diesem Feld der Forschung entsprechend geraubt habe. Dass diese Kritik von einem engen Bekannten Davys kommt und Davy in dreister Art bloß stellt, erschüttert Davy. Er schreibt Granet einen Brief, in dem er bereut, dass Granet Unterstellungen in der akademischen Öffentlichkeit verbreitet, "die selbstverständlich dazu tendieren, meine Arbeit zu diskreditieren. (...) ich habe verkündet, all was ich Mauss schulde".[fn:15] Diese Polemik wird verlängert durch eine andere Besprechung von Raymond Lenoir zwei Jahre später in der /Revue philosophique/, der die Kritiken von Granet wieder aufnimmt und seine Unterstellungen unterstreicht, nach denen Davy Mauss mehr oder weniger ausgeraubt habe. Besnard sagt, dass Mauss diese Meinung geteilt habe.[fn:16] Nichtsdestotrotz muss festgestellt werden, dass Mauss in seinen Schriften keine Kritik zu Davy äußert, sondern wie in /Gift, Gift/ die Arbeit von Davy zitiert und später im Essay /Die Gabe/ sogar sagt, dass "Die vorliegende Arbeit Teil einer Reihe von Forschungen [ist], die Herr Davy und ich zu den archaischen Formen des Vertrags seit langem entwickeln", als ob er Davy zu seiner Forschung assoziieren würde.

Im Rahmen einer schrumpfenden Gruppe nach dem Tod von Durkheim und von vielen Mitarbeitern um Durkheim und Mauss im Krieg und in einer Zeit, in der viele der Kollegen und Studenten von Mauss ihm sagen, dass die Arbeit, die in /L'Année sociologique/ investiert wurde, wieder aufgenommen werden sollte, ist es denkbar, dass Mauss nicht zur Zersplitterung der Durkheim-Schule beitragen wollte. Vielleicht haben wir hier ein Grund, weshalb Mauss statt diese Polemik weiter zu füttern Davy so vorstellt, als ob er mit ihm eng an der Forschung zu Gabenphänomenen gearbeitet habe. Dabei versteht man insbesondere, dass Mauss die Verbindung zwischen den neuen Mitgliedern der Durkheim-Schule wichtig ist, davon zudem nicht wenige wie er im französischen Sozialismus engagiert sind. Dies trifft einen inhaltlichen Punkt, der in /Gift, Gift/ hervorgehoben wird: Durch die Entwicklung von Allianzen zwischen Menschen und Kollektiven anhand von Gabenpraktiken gewinnen diese Menschen einen besseren Umgang mit dem, was verboten ist, und dem, was erlaubt ist, als ob diese Gabenpraktiken den Verbotenen und den Erlaubten verdeutlichen würden. In diesem Zusammenhang spielen die Gegenstände, die ausgetauscht werden, eine wichtige Rolle für diese Verdeutlichung des Verbotenen und des Erlaubten, weil sie die Macht von den Akteuren bewahren und verwirklichen, die einen Gegenstand geben, über die Akteure, die diesen Gegenstand empfangen. Damit werden die Grenzen zwischen dem Verbotenen und dem Erlaubten innerhalb des asymmetrischen Verhältnisses gesetzt, die den Umgang mit Tabous und mit der religiösen Polaritäten Sakralen und Profanen regeln. Diese Grenzeziehung und die entsprechende Umverteilung der Akteure im Gabentausch, die von gleichwertigen zu ungleichwertigen Akteuren werden, sieht Mauss besonders in den germanischen und skandinavischen Bräuchen vorhanden. Dabei fokussiert er insbesondere den Austausch von Getränken, die als stark ambivalent wahrgenommen werden. Es können Geschenk- oder Gift-Getränke sein je nachdem, wie, wann, wo und mit wem sie getrunken werden. Um alkoholische Getränke wie das Bier in germanischen Gesellschaften werden, wie es Mauss in einer späteren Notiz zum Buch Georges Dumézil im Bereich der vergleichenden Untersuchungen von Mythologien präzisiert, /potlatch/ in der Form von /Bierpotlatch/ organisiert, um sich kollektiv vom Tod zu schützen.[fn:17] Weil alkoholische Getränke Produkte der Gärung sind, werden sie mit den magischen Praktiken und mit den Magiern assoziiert, die solche Getränke vorbereiten[fn:18] -- daher auch die Wahrnehmung von solchen Getränken als besonders ambivalenten Getränken bzw. als möglichen Zaubertränken, die sowohl eilen und stärken als auch vergiften und töten können. Durch das gegenseitigen Schenken von alkoholischen Getränken wie dem Bier hält man den Austauschpartner in seiner Macht. Das Schenken des Getränkes setzt ihn in einem asymmetrischen Verhältnis zwischen Vertrauen und Misstrauen, daraus er ausgehen kann, wenn er seinen Mut zeigt und dabei seine Zuverlässigkeit als Austauschpartner bestätigt, was in diesem Zusammenhang bedeutet, es zu wagen, das Getränke zu trinken.

Die Getränke illustrieren beispielhaft diese Eigenschaft der Macht des Gebers über den Empfänger der Gabe. Diese Macht ist nicht auf bestimmte Kategorien von Gegenständen eingeschränkt, sondern er wird zu all den Gegenständen kommuniziert werden, die im Gabentausch ausgetauscht werden. In /Gift, Gift/ taucht diese wichtige Auffassung Mauss', dass der Gabentausch alle Gegenstände sowie alle Menschen einbeziehen kann, die dann in der ganzen Gesellschaft von Klan zu Klan, Familien zu Familien zirkulieren, und diese Gesellschaft selbst in Zirkulationen zu anderen Gesellschaften bringen -- dies sieht man besonders gut beim Verwendung des Begriffes "Kreislauf" am Anfang des Textes und bei der expliziten Erwähnung des Begriffes der Zirkulation in der Fußnote 9 zur Zirkulation der Frauen zwischen Familien. Durch eine solche Zirkulation werden alle Gegenstände der Gaben Machtbehälter von Gebern über Empfängern und aufgrund derselben Zirkulation die Gewährleistung, dass die Macht nicht als Besitz von bestimmten Gebern bleibt, sondern in der ganzen Gesellschaft zirkuliert und daher ständig (um)verteilt wird, wie Geber und Empfänger im Laufe dieser Zirkulation ihre Rolle wechseln. Dabei sammeln sich um die Gabenpraktiken immer mehr Gegenstände, die in die Zirkulation der Gaben aufgenommen werden, sei es, weil sie zu Gaben werden und als Gaben zirkulieren, sei es, weil sie die Zirkulation von Gaben begleiten. Dies gilt für den Pfand, den Mauss sowohl wie eine Gabe als auch wie einen Gegenstand betrachtet, der eine Gabe -- wie am Beispiel des Darlehens -- begleitet, der dann am Tag der Rückzahlung des Darlehens erwidert wird. Dies gilt ebenfalls für den Fehdehandschuhe wie etwa in einem Duell, der als persönlicher Gegenstand vom Geber zu den Füßen des Empfängers geworfen wird, um ihm zu signalisieren, dass er herausgefordert wird. Wenn der Empfänger diese Herausforderung akzeptiert und die Herausforderung stattgefunden hat, dann kommt der Fehdehandschuhe zurück zu seinem Besitzer bzw. ist ihm erwidert.

Sei es am Beispiel des Pfandes und der Fehdehandschuhe, zeigt Mauss, wie solche Gegenstände in der Unterstützung der gegenseitigen Gewährleistung des Verhältnisses zwischen Austauschpartnern in der Gabe kommen. Solche Formen der Gewährleistung findet man nicht nur in den Bräuchen von alten germanischen Gesellschaften, sondern auch in vielen anderen Gesellschaften auf der Erde und in der Zeit. Dieser letzte Aspekt von /Gift, Gift/ betrifft einen wichtigen Punkt im Mauss' Diskurs zur Gabe. Diese Formen von Leistungen werden in unseren zeitgenössischen Gesellschaften immer noch anwesend, was man an den Geschenken noch gut beobachten kann, die wir schenken und bekommen und in uns "Reiz" wie "Unannehmlichkeit" erwecken. In den letzten Zeilen von /Gift, Gift/ meldet Mauss schon das Thema an, dass er in den moralischen Schlussfolgerungen in /Die Gabe/ darstellen wird: Selbst in den modernen Vertragsformen unseres Rechtes, im komplexen globalen wirtschaftlichen Handel und im Allgemeinen in unseren zeitgenössischen Gesellschaften überlebt die Bedeutung der Gabe und reguliert wie eine latente reptilienartige Struktur unserer Austauschpraktiken immer noch unsere Handlung. Wir agieren, weil wir geben, und wir geben, weil wir uns den anderen und der Gesellschaft verpflichten, dabei den Unterschied zu den anderen und dieser Gesellschaft entwickeln, die unsere Singularität bestätigt.

* Nachwort

Wenn Marcel Mauss im Laufe Januar 1919 aus dem Kriegsdienst entlastet wird,[fn:19] fängt eine Zeit der schwierigen Rückkehr zum zivilen und akademischen Leben an, oder wie Mauss in einem Brief an seinen "'Arbeitszwilling'" Henri Hubert[fn:20] mitteilt: "Ich bin gerade dabei, mich neu einzurichten, was nicht einfach ist. (...) Es muss mit einer relativ langen Rückkehr zur Barbarei gerechnet werden".[fn:21] Der Erste Weltkrieg ist beendet. Die Lust auf die Wiederaufnahme der wissenschaftlichen Arbeit ist vorhanden, und die Erwartungen sind groß. Schon im September 1919 fragen ihn die ehemaligen Kollegen,[fn:22] ob es nicht gut wäre, die Arbeit an /L'Année sociologique/ -- der Zeitschrift für Soziologie der Mitarbeiter um Emile Durkheim, der Onkel, und Marcel Mauss, der Neffe, die nach 1912 nicht mehr veröffentlicht wurde --, wieder aufzunehmen. Und die alten sozialistischen Kameraden der Genossenschaftsbewegung müssen auch nicht vergessen werden, sowie die persönlichen Projekten, die in dieser Zeit vielleicht mehr als vor dem Krieg an erneuter Bedeutung gewonnen haben -- dabei insbesondere das Projekt von einem Buch zum Thema der Nation, davon Mauss Hubert mit einem kaum enthaltenen Enthusiasmus den schon halb abgeschlossenen Plan mit fortgeschrittenen verfassten Textteilen vorstellt.[fn:23] Es gibt sehr viel zu tun, um den Anschluss an die Ideen vor 1914 wieder herzustellen, viele Leute zu treffen, andere zu würdigen, die ihr Leben auf dem Schlachtfeld verloren haben. Darunter zählt man viele ehemaligen Studenten und Freunden von Mauss, die für /L'Année/ gearbeitet haben oder mit Mauss in der Unterstützung des Sozialismus in Frankreich gewirkt haben. Von diesem Übergang aus den Trümmern des Krieges ins neue freie Leben bezeugt Mauss' /Gift, Gift/. Formal gleicht dieser Text eine Arbeitsnotiz, aber im Intertext von /Gift, Gift/ gibt es sehr viele Verbindungen sowohl mit der Vergangenheit dessen, was das Projekt von Durkheim und Mauss war, und was dieses Projekt in der Zukunft unter der Leitung von Mauss werden sollte.

** Das Projekt der Gründung einer wissenschaftlichen Soziologie

Marcel Israël Mauss ist am 10. Mai 1872 in der Stadt Épinal im Departement Vosges (ehemals Lothringen) geboren. Nach erfolgreicher Abitur (1890) entscheidet er sich für ein Studium der Philosophie und vertieft seine Kenntnisse der Soziologie unter professioneller Begleitung seines Onkels Emile Durkheim. Da Durkheim in dieser Zeit an der Universität in Bordeaux lehrt, schlägt er Mauss vor, sein Studium in Bordeaux aufzunehmen. Dem Vorschlag seines Onkels folgend nimmt Mauss 1890 ein Studium der Philosophie an der Universität Bordeaux auf. Nach Abschluss seiner /licence/ im Fach Philosophie (1892) studiert Mauss weiterhin in Bordeaux und gleichzeitig auch an der Universität Sorbonne in Paris. In Bordeaux nimmt er an den Lehrveranstaltungen seines Onkels teil, den er als "'den sichersten und den angenehmsten aller Redner'" bezeichnet und der sehr schnell zu seinem Mentor wird.[fn:24] In diesen Studienjahren entwickelt Mauss eine tiefe Freundschaft zu zwei weiteren seiner Professoren, dem Soziologen Alfred Espinas und dem Philosophen Octave Hamelin. Bei Espinas, der sich nach seinem Werk /Des sociétés animales/ (1877) mehr und mehr der experimentellen Psychologie und der Frage der Technik widmet, entwickelt Mauss ein ausgeprägtes Interesse für die Biologie, die Evolutionstheorie und die Technik, was ihn davon überzeugt, dass sich die Soziologie nur dann zu einer vollständigen Wissenschaft entwickeln kann, wenn sie auf der experimentellen Psychologie aufbaut. Hamelin dagegen macht Mauss mit seinem Verständnis des Neokantianismus vertraut, den Mauss als eine wichtige Quelle der Erneuerung der Philosophie versteht und der seiner Ansicht nach auch von der Soziologie verwendet und weiter verbreitet werden sollte.

1895 schließt Mauss seine /aggrégation/ im Fach Philosophie ab, was ihm das Recht gewährt, Philosophie in Gymnasien und als Hochschullehrer lehren zu dürfen. Aber Mauss weiss noch nicht, was er beruflich machen möchte. Durkheim nimmt ihn als Hilfskraft im Rahmen der Vorbereitung der Statistiken für sein Buch zum Selbstmord (1897) mit. Mauss arbeitet am /Service de la statistique judiciaire/ von Gabriel Tarde.[fn:25] Es ist eine Zeit des intensiven Austausches zwischen Durkheim und Mauss. Der Onkel bemerkt, dass Mauss Fragen der Religionwissenschaften interessiert, die Durkheim ebenfalls spannend findet und in Verbindung mit seiner Art der soziologischen Untersuchung bringen möchte. Deshalb rät er Mauss, die Lehrveranstaltungen zur Religionwissenschaften an der /École pratique des hautes études/ (EPHE) zu besuchen. Mauss gefallen diese Lehrveranstaltungen, und anschließend immatrikuliert er sich in zwei Sektion der EPHE bzw. in den historischen und philologischen Wissenschaften (IV. Sektion) und in der Religionswissenschaften (V. Sektion). An der EPHE trifft Mauss auf Professoren, die enge Freunde werden, wie etwa Léon Marillier und Antoine Meillet im Bereich der Psychologie, der Philologie und der Linguistik, und insbesondere Sylvain Lévi im Bereich der Judaistik und der Indologie,[fn:26] der für Mauss wie zum zweiten Onkel wird. In diesem Umfeld tauchen die ersten wissenschaftlichen Arbeiten von Mauss sowie die ersten Ideen zur Bildung von einem Kreis von gleichgesinnten Gelehrten und Studierenden auf. Sie würden an der Schnittstelle zwischen Philologie, Geschichte, Religionwissenschaften und Ethnologie eine neue Art der soziologischen Untersuchung entwickeln, deren Ergebnisse mit einem eigenen Medium veröffentlicht werden würden. Das Projekt der Zeitschrift /L'Année sociologique/ war auf dem Papier geboren, im Kern deren Mauss eine Schlüsselrolle als Koordinator spielt,[fn:27] und die er später nach dem Tod von Durkheim leiten wird.

Während Durkheim 1896 mit dem Verlag Alcan in Paris verhandelt, um zu ersuchen, ob Alcan sich vorstellen könnte, eine Zeitschrift für Soziologie in der Form von einem Jahrbuch mit dem Titel /L'Année sociologique/ zu veröffentlichen, arbeitet Mauss an seiner ersten wissenschaftlichen Produktion. Er schreibt eine Rezension zu Adolf Bastian und einen Aufsatz zu Sebald Rudolf Steinmetz für die von Réville und Marillier herausgegebenen Zeitschrift /Revue de l’histoire des religions/, die nicht nur Durkheim, sondern auch Tarde, bei dem Mauss zu dieser Zeit arbeitet, sehr gefallen.[fn:28] Nach erfolgreicher Verhandlung mit Alcan fängt die Arbeit an der Zeitschrift /L'Année sociologique/ an. Mauss leitet die Sektion der /Sociologie religieuse/, die die angesehenste Sektion der Zeitschrift bildet und den Kerngedanken der Durkheim’schen Soziologie unterstützt, wonach die Religion die Matrix der sozialen Tatsachen sei. 1897 stellt /L’Année/ weitere Mitarbeiter aus dem Umfeld der Gruppe ein (Paul Lapie, Emmanuel Lévi, Egard Milhaud, Henri Muffang und Dominique Parodi). Die Arbeit, die Mauss in diesem Zusammenhang leisten muss, verlangt sehr viel Zeit, die Mauss aufgrund von seinen anderen Projekten im Rahmen seines politischen Engagements für die Arbeiterbewegung und mehr und mehr in Unterstützung von Jaurès und dem Sozialismus nicht immer hat. Entsprechend hat Mauss Schwierigkeiten, regelmäßig zur Arbeit zu erscheinen und seine Rezensionen rechtzeitig zu liefern, was Durkheim besonders verärgert. "'Das Übel ist ausweglos; wir haben es mit einem Unheilbaren zu tun'", teilt Durkheim Hubert mit und bezieht sich hierbei auf Mauss, der in seiner gesamten Zeit bei /L’Année/ keine Fristen einhält und manchmal wichtige Rezensionen vergisst, die Durkheim anschließend selbst schreiben muss.[fn:29]

Im Jahre 1898 erscheint das Buch /La Doctrine du sacrifice dans les Brāhmaṇas/ von Sylvain Lévi, das Mauss auf ein entscheidendes Phänomen aufmerksam macht: Opferriten werden ausgeübt, um die Akteure einer Gesellschaft mit der sakralen Welt der Götter in Kontakt treten zu lassen. Gemeinsam mit Hubert will Mauss diese Erkenntnis vertiefen. Von Durkheim übernehmen Mauss und Hubert die Idee der Zerstörung, die in den Opferriten ständig präsent ist, die eine konkrete soziale Funktion hat. Das, was im Opfer geopfert bzw. zerstört wird, dient der Kommunikation mit dem Sakralen und alles was sakral ist, betrifft die Gesellschaft unmittelbar wie mittelbar.[fn:30] Diese These ist der argumentative Gipfelpunkt des /Essays über die Natur und die Funktion des Opfers/ (/Essai sur la nature et la fonction du sacrifice/), den Mauss und Hubert im zweiten Band von /L’Année/ veröffentlichen. Dieser /Essay/ wird in Frankreich und im Ausland als Meisterstück gefeiert. Das Sakrale im Opfer wird als wesentliches Merkmal, nicht nur des religiösen, sondern auch des sozialen Lebens verstanden. Zudem unterstützt diese Erkenntnis Durkheims Auffassung von Religion, die ein Mittel für die Akteure sei, sich die unpersönliche Kraft der Gesellschaft anzueignen. Mauss und Hubert grenzen sich jedoch auch bezüglich eines kleinen, aber wichtigen Details von Durkheims Ansatz ab.[fn:31] Zwar zeigt das Opfer, wie relevant die Gesellschaft für die Akteure ist. Allerdings ist das Individuum mindestens ebenso relevant für die Gesellschaft, was insbesondere daraus hervorgeht, dass das Opfer nicht blind, sondern nach Regeln verwendet und vollzogen wird, die unter anderem darauf abzielen, die Akteure vor der Bestimmungsmacht der Gesellschaft zu schützen.

** Das politische Engagement im Sozialismus

Die Zeit der Veröffentlichung des /Essays/ kennzeichnet eine Wende im Leben von Mauss, der ab 1900 Lehraufträge an der EPHE anbietet und ab 1901 im regelmäßigen Lehrbetrieb der Universität als Professor und Forscher tätig ist.[fn:32] Diese Wende betrifft ebenfalls Mauss' Engagement in die politischen Bewegungen seiner Zeit und insbesondere in den Sozialismus. Mauss' Studienjahre waren gleichzeitig die Jahre seiner politischen Ausbildung. Über Durkheim hat Mauss den Sozialisten Jean Jaurès kennengelernt, der ihm sehr stark prägen wird.[fn:33]. Mauss gehört zu jenen Studierenden, die auf den Marxismus in seiner französischen Spiel- und Lesart aufmerksam werden. In Paris besucht er die entsprechenden Gruppen von politisierten Studierenden. In diesem Zusammenhang lernt er Marcel Cachin kennen, der ebenso ab 1890 in Bordeaux Philosophie studiert, bereits Mitglied der französischen Arbeiterpartei ist und Mauss davon überzeugt, ebenfalls Mitglied dieser Partei zu werden.[fn:34] Für Mauss ist das politische Engagement mindestens ebenso wichtig wie sein Engagement in der Wissenschaft. Es handelt sich dabei um ein ernsthaftes Engagement für die von vielen Bevölkerungsteilen Frankreichs geteilten Ideen des Sozialismus, die er bis zu seinem Lebensende unterstützen wird. In den Jahren 1893-1894 leitet Mauss die /Ligue démocratique des écoles/ und wird zum aktiven Mitglied der /Groupe des étudiants collectivistes/ in Paris, wo er viele anderen Studierenden kennenlernt, davon einige wie Edgar Milhaud, Abel Rey und Paul Fauconnet zu seinen Freunden gehören.[fn:35]

Mauss engagiert sich später in der von Lucien Herr um die /Société nouvelle de librairie et d’édition/ (1899) gegründeten /Groupe de l’unité socialiste/ und unterstützt die Initiativen dieser Gruppe, indem er beispielsweise Lehrveranstaltungen mit Emmanuel Lévy, Simiand und Fauconnet an der /École socialiste/ anbietet.[fn:36] Außerdem unterstützt er die Dreyfusards in der Dreyfus-Affäre. Mehr und mehr interessiert er sich auch für die Genossenschaften und insbesondere die Konsumgenossenschaften. Über die Intensität seines Engagements in diesen unterschiedlichen Bewegungen berichtet die Presse. Neben Spenden in Unterstützung von Arbeitergruppen, die streiken, um Verbesserung ihrer Arbeitsbedingungen zu fordern,[fn:37] organisiert Mauss verschiedene /causeries/ (Plaudereien), die wie kleine öffentliche Konferenzen häufig mit musikalischer Begleitung und anschließendem Beisammensein konzipiert werden. Im Jahr 1899 bietet Mauss im Rahmen dieser /causeries/ eine Reihe von Vorträgen zur "Geschichte der Gewerkschaftsorganisation in England" in Paris, Hallé Str. 65 an.[fn:38] Er veröffentlicht den in den sozialistischen Milieus in Frankreich hoch gelobten Beitrag "L'action socialiste", in dem er für die Vereinheitlichung der unterschiedlichen sozialistischen Bewegungen in Frankreich plädiert.[fn:39] Anschließend schließt sich Mauss der /Fédération des Jeunesses Socialistes-Révolutionnaires Internationalistes/ und der /Coalition des Jeunesses Révolutionnaires/ mit dem Ziel an, beide Bewegungen miteinander zu verbinden und an einer entsprechenden gemeinsamen Satzung für eine neue gemeinsame /Fédération/ zu arbeiten.

Im Frühling 1900 gründet Mauss mit einigen Freunden die /Coopérative socialiste. Boulangerie socialiste de Paris/, die zur Gründung der /Coopérative socialiste/ als eine Produktions- und Konsumgenossenschaft am 05.03.1900 führt.[fn:40] Mauss gehört mit Xavier Guillemin, André Hamelin, dem Dr. Kasimir aus Belgien und mit Philippe Landrieu zum Kontrollorgan und Beirat dieser Genossenschaft. Die Propaganda-Arbeit für die Genossenschaft in der Öffentlichkeit koordinieren Jean Allemane und Jaurès. Der Verwalter der Genossenschaft ist Guillemin in der Zusammenarbeit mit Hamelin, der die /Boulangerie/ leitet. Am 17.05.1900 beschreibt Léon Gérault-Richard, wie die /Boulangerie/ entstanden ist. Er betont insbesondere die bedeutsame Rolle der belgischen Sozialisten um Hector Denis und den Dr. Kasimir, der als Mäzen in Unterstützung der Gründung der /Boulangerie/ einspringt und 100.000.- Franken ausgibt.[fn:41] In dieser Zeit ist es Mauss bewusst, dass die Genossenschaftsbewegung in Frankreich nicht nur innerhalb des Landes entwickelt werden muss. Sie muss ebenfalls mit Genossenschaften in anderen Ländern Europas verbunden werden, damit diese Entwicklung langfristig etabliert und erfolgreich durchgeführt werden kann. Zu diesem Zweck wird entschieden, einen internationalen Kongress in Paris am 07.07.1900 zu organisieren, davon Mauss der Überraschungsgast ist und über die internationalen Beziehungen zwischen Genossenschaften redet.[fn:42] In den Berichten zum Kongress wird die Rolle von Mauss an der internationalen Schnittstelle der Genossenschaftbewegung hervorgehoben. Mauss "glaubt, dass die Organisation landwirtschaftlicher Produktionsgenossenschaften international sein muss. Er stützt sich dabei auf das Beispiel des schottischen Wholesale und der großen englischen Molkereigenossenschaften".[fn:43] Mauss "schlägt nachdrücklich vor, internationale Beziehungen durch den Austausch von Publikationen, Handelsinformationen und Produkten aufzubauen. Auf diese Weise könnte man von gemeinsam abgeschlossenen Verträgen profitieren. Er fordert den Kongress auf, die Gründung einer internationalen Genossenschaftsbank sowie internationaler auf Gegenseitigkeit basierter Versicherungsvereine für Feuer-, Kranken- und Lebensversicherungen zu prüfen".[fn:44] Diese Vorschläge werden von Jaurès nachdrücklich unterstützt, der auf dem Konress sagt: "Es reicht nicht aus, dass die Genossenschaften sozialistisch werden; die Sozialisten müssen Genossenschafter werden, das heißt, die sozialistische Partei muss all ihre Mitglieder auffordern, Genossenschaften beizutreten!".[fn:45] Selbst wenn Charles Gide die Ideen von Jaurès und Mauss nicht vollständig teilt, solidarisiert er sich mit ihnen. Mit Jaurès und in der Folge von Mauss schlägt Gide vor, einen kollektiven Reservefonds zu organisieren, zu dem alle Genossenschafter beitragen würden. Damit könnte Geld gesammelt werden, um andere Genossenschafter und Arbeiter zu unterstützen, wenn sie z.B. streiken und deshalb nicht bezahlt werden würden, oder wenn sie ihre Arbeit verlieren würden.[fn:46] Dieser Reservefonds wäre auch einen ersten Schritt in der Reform der Bezahlung von Genossenschafter, die nicht mehr entlohnt werden würden, sondern, wie es sich Mauss und Jaurès wünschen, mit einem solchen Fonds bezahlt werden würden.[fn:47]

Jedoch lassen sie sich nicht alle Sozialisten von diesem Vorschlag begeistern. Eine Debatte zur Nützlichkeit und Notwendigkeit von einem solchen Reservefonds wird eröffnet. Der Vorschlag wird an vielen Stellen so korrigiert, dass er seine Substanz fast vollständig verliert.[fn:48] Mauss, Jaurès und Gide werden es sich damit bewusst, dass die französischen Sozialisten die Genossenschaftsbewegung nicht unbedingt unterstützen wollen, und dass selbst innerhalb der französischen Genossenschaftsbewegung der Dissens spürbar ist. Es ist keine einheitliche Bewegung, sondern es gibt zumindest drei unterschiedlichen Tendenzen, die erkannt werden können. Einerseits gibt es die Genossenschafter wie Mauss, die das Modell der Konsumgenossenschaft in den Vordergrund der Genossenschaftsbewegung rücken. Diese Konsumgenossenschaften werden von allen Genossenschaftern geleitet, und sie sind im Bereich der Lieferung von Produkten an alle anderen Genossenschaften tätig. Andererseits gibt es die Produktionsgenossenschaften, die im Unterschied zu Konsummgenossenschaften nicht nur Produkte liefern, sondern solche Produkte auch manchmal selbst herstellen. Die Produktionsgenossenschaften werden nicht von allen, sondern von einigen (manchmal von nur einem) Genossenschaftern geleitet, die das Geschäft der Genossenschaft bestimmen. In der Mitte gibt es Genossenschafter wie Gide, die vorschlagen, dass beide Formen der Genossenschaften in einem großen Verband integriert werden sollten. Mauss und Jaurès versuchen, die anderen Genossenschafter davon zu überzeugen, dass ein solcher Verband nur im Sinne von "einem nationalen und internationalen Verband" existieren kann, der nicht bei privaten Firmen auf dem Markt kauft, sondern lediglich nur bei anderen Genossenschaften im In- oder im Ausland.[fn:49] In den Jahren 1901 und 1902 bildet dieses Thema der Kern der Konferenzen und /causeries/ von Mauss,[fn:50] und der Lehrveranstaltungen an der /Ecole socialiste/[fn:51] wie an der Volksuniversität der /Union Mouffetard/ in Paris.[fn:52] Im Jahre 1903 verwirklicht Mauss im Kleinen seine Auffassung von Genossenschaftsverbänden. Mit Landrieu, Henri Jullien und die Mitglieder der /Bourse des coopératives socialistes/ verfasst er die erste Satzung zur Gründung einer /Fédération coopérative de la région parisienne/, die Mauss bei internationalen Ereignissen wie dem internationalen Kongress in Lüttich (1905) vertreten wird.[fn:53] In dieser Zeit zwischen 1902 und 1904 erreicht Mauss vieles nicht nur in Bezug auf seine politischen Ziele, sondern auch auf seine wissenschaftliche Arbeit.

** Die soziale Realität als totale soziale Tatsache

1900 hatte Mauss mit Paul Fauconnet und der Unterstützung von Durkheim den Eintrag "Sociologie" in der /Grande Encyclopédie/ verfasst,[fn:54] der wie ein Manifest für eine wissenschaftliche Soziologie auf der Grundlage der Regeln der soziologischen Methode Durkheims wirkt. Diese zu entwickelnde wissenschaftliche Soziologie erfordere sehr genaue Untersuchungen von allzu alltäglich anmutenden gewöhnlichen Gegenständen in Zusammenarbeit mit anderen Disziplinen der Geistes- und Sozialwissenschaft, insbesondere aber der Geschichte, der Ethnographie, den Sprachwissenschaften und der Psychologie. Eine solche interdisziplinäre Herangehensweise ermöglicht es, die zu untersuchenden Tatsachen so vollständig als irgend möglich zu beschreiben, dass ihr tatsächliches Dasein und ihre Bedeutsamkeit als allumfassende gesellschaftliche Ganzheit, d. h. als "'totale' gesellschaftliche Tatsache[n]",[fn:55] offen zutage tritt. Mauss’ Idee der totalen sozialen Tatsachen beruht auf einem komplexen soziologischen Forschungsprogramm, das nicht zuletzt mit anderen Disziplinen in Dialog treten soll, um die zu untersuchenden sozialen Tatsachen in ihrer ganzheitlichen Verbindung mit dem gesellschaftlichen Zusammenleben zu erklären. Diese Verbindung entwickeln Mauss und Durkheim im Essay /De quelques formes primitives de classification/ (/Über einige primitive Formen der Klassifikation/), der 1903 in /L’Année/ veröffentlicht wird. Für diesen Beitrag sammelt Mauss umfangreiche ethnographische Daten zu den unterschiedlichen Klassifikationssystemen, die die Menschen weltweit verwenden, um nicht nur sich selbst als Menschen, sondern ebenso Götter und Gegenstände sowie Phänomene und Ereignisse ihrer Umwelt einzuordnen. Mauss und Durkheim stellen fest, dass die Klassifikationen von Gegenständen, Göttern und Symbolen einerseits die Klassifikation von Akteuren und andererseits die Hierarchisierung von Menschen und sozialen Gruppen sich reproduzieren und somit unmittelbar wie mittelbar mit der Gesellschaftsstruktur jener Sozialitäten korrespondieren. Damit eröffnen Mauss und Durkheim ein neues Gebiet für die Soziologie nach dem Prinzip, dass die Art und Weise, wie eine Gesellschaft organisiert und strukturiert ist, die Formen der Erkenntnis eben dieser Gesellschaft und zwar ausgehend von der sinnlichen Wahrnehmung maßgeblich bestimmt.[fn:56] Die Überlegungen zu den primitiven Klassifikationsformen führen Mauss auf die Spuren der Magie als möglicher Quelle der Entstehung mentaler Klassifikationsmuster, Kategorien und Repräsentationen.

Der gemeinsam mit Hubert verfasste /Entwurf einer allgemeinen Theorie der Magie/ (/Esquisse d’une théorie générale de la magie/) erscheint im Jahr 1904 in /L'Année/ unmittelbar nach dem Essay mit Durkheim. Nach Mauss und Hubert erweist sich die Magie als eine Sammlung von praktischen Riten, die im Vergleich zu religiösen Riten ungleich einfacher und individueller sind.[fn:57]. Entsprechend handelt es sich bei der Magie um eine Zusammenstellung von praktischen Techniken, die von einem Magier verwendet werden. Zwar agiert er augenscheinlich allein, gleichzeitig jedoch fungiert er insofern als Beauftragter der Gesellschaft, als er von der Gesellschaft und ihren Mitgliedern in Dienst genommen wird, deren Wahrnehmungs- und Erkenntniskategorien er in bedeutsamer Weise gestaltet. In der Magie glauben Mauss und Hubert die Quelle der kollektiven Repräsentationen gefunden zu haben, die die Grundlage des individuellen Verstandes bereitzustellen scheinen. Jedoch stößt die /Esquisse/ auf weniger Resonanz als die anderen Arbeiten von Mauss.[fn:58] Mauss’ und Huberts doppelte Perspektivierung der Quelle kollektiver Repräsentation einerseits und der Grundlagen individueller Verstandestätigkeit andererseits legen grundsätzlich den Schluss nahe, dass die Grundlage der menschlichen Vernunft die Unvernunft bilde. Die Rationalität könne nur in Verbindung mit Gefühlen, Empfindungen und Emotionen entwickelt werden. Dies bestreiten insbesondere die Philosophen und unter ihnen auch diejenige, die Mauss eigentlich schätzen.[fn:59] Mit diesen Kritiken kommen noch die Krisen in den Verhältnissen zwischen Durkheim, Mauss und das Team von /L'Année/ hinzu. Viele der Mitarbeiter unterstützen Durkheims Auffassung der Soziologie nur teilweise, wenn sie sie überhaupt verstehen. In seinem berühmten Aufsatz zum Team von /L'Année/ hat Philippe Besnard deutlich gemacht, dass dieses Team nie homogen um Durkheim und Mauss stand. Mehr als ein "Team" handelt es sich um kleine Gruppen von ehemaligen Studenten, die miteinander und mit Durkheim wenig interagieren.[fn:60] Selten sitzen sie zusammen, und entsprechend sehr unterschiedlich ist das Engagement der verschiedenen Mitarbeiter in Unterstützung der konkreten Arbeit, die in /L'Année/ getan werden muss. In einem solchen Zusammenhang sind Krisen kaum vermeidlich, die unmittelbar nach der Veröffentlichung der ersten Nummer von /L'Année/ im Jahr 1900 auftauchen. Eine erste Krise entwickelt sich um die Frage, ob kritische Rezensionen veröffentlicht werden sollten. Eine zweite Krise folgt im Jahr 1902 um die Frage, ob es nicht besser wäre, in /L'Année/ nur Rezensionen und Besprechungen zu veröffentlichen und die /Mémoires/ der Mitarbeitet bzw. ihre langen eigenen Aufsätzen aus /L'Année/ auszuschließen. Eine dritte Krise kommt 1907 mit der Durchsetzung dieser letzten Maßnahme.[fn:61] Deshalb auch die Haltung von Durkheim, der mehr und mehr Einfluss auf /L'Année/ und auf die inhaltlichen Produktion seiner engsten Mitarbeitern ausübt. Dies betrifft Mauss nicht zuletzt, der in der Zeit nach 1904 versucht, sich von diesem Einfluss mit der Hoffnung zu befreien, dass er seine Kraft und seine Zeit in sein eigenes Pensum investieren kann.

Hubert hat es gut verstanden, der ab 1905 mit Mauss über die Möglichkeit spricht, ihre wichtigsten Studien, die in unterschiedlichen Zeitschriften publiziert wurden, gemeinsam in einem Band zu versammeln, um den roten Faden ihrer Arbeit in gebündelter Form sowohl verständlicher als auch deutlicher hervortreten zu lassen. Hubert schwebt hierfür bereits eine bestimmte Gliederung vor, was wiederum beiden Autoren die Gelegenheit gibt, einige Aussagen und Schlussfolgerungen zu präzisieren, stärker miteinander zu verbinden und gegebenenfalls aneinander anzupassen. Mauss und Hubert geht es in ihren versammelten Schriften in erster Linie um folgende zwei Botschaften: allgemeine Phänomene des sozialen Lebens müssen erstens vergleichend und induktiv untersucht werden; zweitens bilden den Ausgangspunkt solcher Studien insbesondere soziale Institutionen wie das Opfer, die Magie und die Klassifikationsformen. Anders gesagt, legen Mauss und Hubert nahe, dass die soziologische Untersuchung religiöser Phänomene induktiv und vergleichend zu verfahren habe und nach einem makrosoziologischen Ansatz zu entwickeln sei, was im Übrigen auch auf jede Art der soziologischen Untersuchung verallgemeinert werden könne.[fn:62] Ein Zwischenschritt in dieser Überlegung bietet sich mit dem Veröffentlichungsvorhaben, das Maus im Jahre 1905 mit Henri Beuchat zu den Eskimos-Gesellschaften vorbereitet. Zu den Eskimos gibt es wenige Daten, weshalb Mauss diese Lücke beseitigen möchte und nach London mit seinem Studenten und Freund Robert Hertz reist, um mehr Daten im /British Museum/ zu den Eskimos-Gesellschaften zu sammeln und auszuwerten. Dabei entdeckt Mauss einen Zusammenhang zwischen dem Rhythmus der Jahreszeiten und dem Rhythmus des gesellschaftlichen Lebens der Eskimos. Im Winter leben sie eng zusammen. Es ist eine Zeit der Feierlichkeiten, der religiösen Einheit und des sexuellen Kommunismus. Dagegen ist diese Form des Zusammenlebens im Sommer kaum noch spürbar bzw. wird auf ein Minimum reduziert.[fn:63] Diese Abwechslung im Rhythmus des sozialen Lebens entdeckt Mauss nicht nur bei den Eskimos, sondern auch bei den Indianer-Stämmen Nordamerikas und bei kleinen landwirtschaftlichen Gemeinschaften in den europäischen Alpen. Alles scheint zu geschehen, als ob die Gesellschaft hinter ihren Akteuren verschwinde, wenn für diese Akteure die Tätigkeitsfelder zunehmen und sie am umfassendsten beschäftigt sind. Dann verschwinden die Akteure hinter ihrer Gesellschaft im Winter wieder, wenn ihre Betätigungsfelder abnehmen und ihre Tätigkeiten auf ein Minimum reduziert sind. Dieser Essay mit dem Titel /Über den jahreszeitlichen Wandel der Eskimogesellschaften. Eine Studie zur sozialen Morphologie/ (/Essai sur les variations saisonnières des sociétés Eskimos. Étude de morphologie sociale/, 1906) wird mäßig rezipiert. Für Mauss stellt er sich jedoch als ein weiterer Schritt in Richtung der Entwicklung seiner Gedanken zu den religiösen Phänomenen und dahingehend insbesondere zum Verhältnis zwischen Individuen und Gesellschaften dar, welches Mauss und Hubert seit Beginn ihrer Zusammenarbeit und ihrer ersten gemeinsam verfassten Schriften besonders interessiert. Mit der relativen Emanzipation von Mauss zu /L'Année/ und zu seinem Onkel, dem gemeinsamen Vorhaben mit Hubert, das 1909 mit dem Titel /Mélanges d’histoire des religions/ veröffentlicht wird, kommt eine Zeit der beruflichen Selbstverwirklichung und Anerkennung. Auch im Bereich seiner politischen Tätigkeiten gewinnt Mauss an Bedeutung.

** Botschafter der französischen Genossenschaftsbewegung

Seit dem Beginn seines Engagements in Unterstützung der Genossenschaftsbewegung in Frankreich wünscht sich Mauss den Aufbau von einem inter-nationalem Handelsnetzwerk zwischen Genossenschaften und insbesondere Konsumgenossenschaften. Es müssen "Beauftragten" der verschiedenen Genossenschaften ins Ausland gesendet werden, "um die unterschiedlichen Lebensmittel zu kaufen", um "Braunkohle gemeinsam zu kaufen; kurzum alle möglichen Mitteln verwenden, um diesen Verband herzustellen".[fn:64] Diese Botschaft möchte Mauss einem breiteren Publikum unterbreiten, und die Gründung der Zeitung /L’Humanité/ durch seine Bekannten Lucien Lévy-Bruhl, Léon Blum und Lucien Herr mit der Unterstützung von Jaurès[fn:65] wird ihm diese Möglichkeit geben. Mauss beteiligt sich an der Finanzierung der Zeitung und wirkt, gemeinsam mit Landrieu, als Redakteur der Rubrik "Genossenschaften" mit. Für Mauss und Landrieu geht es darum, die Genossenschaftsbewegung in der Öffentlichkeit bekannter zu machen bzw. zu verbreiten. Es müssen von so vielen Genossenschaften wie möglich gesprochen werden, um die Öffentlichkeit von der Bedeutung dieser Bewegung zu überzeugen.[fn:66] Entsprechend reist Mauss innerhalb Frankreich und ins Ausland, um an Ereignissen um die Genossenschaften teilzunehmen, und dabei erscheint er für viele Sozialisten, die wie Mauss die wichtige Rolle der Genossenschaftsbewegung in Unterstützung der Stärkung des Sozialismus hervorheben, als Botschafter der französischen Genossenschaftsbewegung. Mauss berichtet über die wachsende Bedeutung der deutschen Konsumgenossenschaften und der Grosseinkaufgesellschaft in Deutschland (gegründet im Jahr 1894),[fn:67] davon das Modell die britischen Wholesales-Gesellschaften sind.[fn:68] Das deutsche Beispiel zeigt die Bedeutung der Erziehungsrolle der Genossenschaften für die Arbeiter: "es geht vor allem darum, den Arbeiter zu erziehen und ihn dabei zu beeinflussen, die politischen Werkzeuge zu verwenden, um [seine; CP] Situation zu verbessen".[fn:69] Mauss versteht die Genossenschaften im engen Verhältnis mit dem Sozialismus. Die Genossenschaft ist eine "Form der Arbeiterhandlung",[fn:70] die "mit der allgemeinen Bewegung der modernen Gesellschaften zur Abschaffung der Klassen und des Angestelltenverhältnisses verbunden ist".[fn:71] Bis dies tatsächlich stattfinden kann, gibt es jedoch noch einen langen Weg zu beschreiten, wie Mauss bei seinen Reisen feststellt.

1904 findet der internationale Kongress der Genossenschaften in Budapest statt. Mauss reist nach Budapest, und er ist enttäuscht von dem, was er dort beobachtet: "Der Kongress geht weiter, und er ist nicht sehr interessant. (...) Selbst heute schließt er erfolglos, machtlos ab".[fn:72] 1905 reist Mauss nach Schottland zum Kongress der britischen Genossenschaften in Paisley mit dem Mechaniker, Sozialist und Mitglied einer der ältesten Genossenschaften in Frankreich /La Bellevilloise/ Louis Héliès. Im Auftrag der /Bourse des Sociétés coopératives ouvrières de consommation/ muss er insbesondere über die Wholesales berichten, um zu ersuchen, ob ein solches Modell in Frankreich entwickelt werden könnte. Auch mit Héliès reist er anschließend nach Lüttich zum belgischen Kongress der Genossenschaften im Juli 1905. Aus diesen Reisen gewinnt Mauss die Ansicht, dass die Entwicklung der Genossenschaften in Frankreich zu langsam verläuft. Nicht genug wird getan, um für die Genossenschaften als Organisationsform des Klassenkampfes im Dienst der Arbeiter zu werben.[fn:73] Selbst diese Bezeichnung der Genossenschaft als politisierte Organisationsform wird in Frankreich infragegestellt, was Mauss vollkommen verblüfft: "[ich] glaube nicht, definitiv nicht, dass es im Interesse der genossenschaftlichen Arbeiter ist, dass sie ihre Organisationen als neutral verkünden".[fn:74] Diejenige, die es glauben, gehören Gide und den Anhängern seiner Denkschule in Nîmes, der sich von Mauss und Jaurès distanziert hat. Es sind die Unterstützer der "gelben" Genossenschaften, wie Mauss sie bezeichnet und von den "roten" Genossenschaften unterscheidet.[fn:75] Mauss nennt diese Genossenschaften "gelb" in Anlehnung an die französischen gelben Gewerkschaften, die die Gewerkschaften des Arbeitgeberverbandes sind und sich 1899 gegen die traditionellen Arbeitergewerkschaften gebildet haben, um die Arbeitergewerkschaften zu schwächen. Diese gelben Genossenschaften, wie es Mauss bedauert, mehren sich in Frankreich, wobei sie die Sozialisten eigentlich in Konsumgenossenschaften konvertieren sollten. Hinter dieser Unterscheidung zwischen gelben und roten Genossenschaften stellt sich die Frage der Form der Genossenschaft, die in Frankreich herrschen muss. Diese Frage ist nicht neu. Auf dem Kongress der /Union Coopérative/ von 1896 wurde die Möglichkeit erwähnt, die fünf Bereiche der Genossenschaftsbewegung -- Konsum, Produktion, Kredit, Bauwesen und Gewinnbeteiligung -- zusammenzustellen.[fn:76] Dieser Vorschlag wurde jedoch heftig kritisiert. Insbesondere die Vertreter der Pariser Genossenschaft /La Moissonneuse/ werben dafür, dass die Mehrheit der Genossenschaften wie kapitalistische Unternehmen handeln. Das Spannungsverhältnis zwischen Konsum- und Produktionsgenossenschaften gipfelt Anfang des 20. Jahrhunderts im Projekt des /Palais du Travail/. Dieses Bauprojekt, das gemeinsam von den Genossenschaftern der /Bourse/, der /Union/ und der Produktionsgenossenschaft /Chambre Consultative des Association Ouvrières de Production/ vorangetrieben wurde, hatte zum Ziel, Konsum- und Produktionsgenossenschaften mit den Gewerkschaftsorganisationen der /Bourse du Travail/ unter einem Dach zu vereinen. Die Meinungsverschiedenheiten zwischen den Initiatoren des Projekts waren jedoch so groß, dass der Bau des Gebäudes endgültig auf Eis gestellt wurde -- ohne dass der Grund dafür jemals ermittelt wurde.[fn:77]

Mauss wie seine Freunde im Sozialismus stehen jedoch vor einer Realität der Entwicklung von Genossenschaften in Frankreich, die sie nicht weg diskutieren können: Die Produktionsgenossenschaften wachsen, was Guillemin zum Schluss bringt, dass "das Gesamtwesen der französischen Genossenschaften eher egoistisch [ist]".[fn:78] Der Kongress der /Union coopérative/ und der Kongress der französischen Genossenschaften in Nantes (1905) haben an diesem Sachverhalt nichts geändert.[fn:79] Ab 1906 werden die Artikel von Mauss in /L'Humanité/ zu den unterschiedlichen Genossenschaften in und um Frankreich seltener, als ob er sich von der Genossenschaftsbewegung abwenden würde. Ab 1907 erscheint die Rubrik "Genossenschaften" von Mauss und Landrieu unregelmäßig. Mauss trägt jedoch weiter zum Thema der Genossenschaften vor, wie etwa im Rahmen der /Ecole socialiste/ in den Jahren 1910 und 1911, wo er Lehrveranstaltungen zur Ideologien und Geschichte der Genossenschaften anbietet.[fn:80] Im Jahre 1912 am Kongress der französischen Genossenschaften in Tours ist Mauss anwesend. Er widerspricht Gide einmal mehr, wenn dieser darauf besteht, dass die Genossenschaften und insbesondere die Konsumgenossenschaften die Unterstützung von "gelben" Genossenschaften nicht ablehnen, sondern annehmen müssen. Dieser Vorschlag geht gegen die Auffassung der Genossenschaften Mauss', aber die Mitglieder im Kongress unterstützen den Vorschlag von Gide.[fn:81] Damit wird für Mauss ein Kapitel seines Engagements im Sozialismus vorübergehend abgeschlossen. Aber nicht nur im Sozialismus muss Mauss mit Enttäuschungen umgehen, sondern auch in der Akademie.

1907 bewirbt er sich am Lehrstuhl für Geschichte der Religionen (ehemals Albert Révilles Lehrstuhl) am /Collège de France/.[fn:82]. Mit seiner ersten Bewerbung will Mauss insbesondere sein Interesse für den Lehrstuhl Révilles zum Ausdruck bringen. Er rechnet nicht ernsthaft damit, ausgewählt zu werden. Und tatsächlich geht der Lehrstuhl nicht an Mauss, sondern an Jean Réville, den Sohn von Albert Réville. Dennoch ist das Wahlergebnis für Mauss vielversprechend. Bereits in der ersten Wahlrunde erhält er, zur Überraschung seiner Freunde, viele Stimmen und die zweite Wahlrunde, in der der Vertreter des siegreichen Kandidaten gewählt wird, entscheidet er sogar für sich.[fn:83] 1908 stirbt Jean Réville und am Collège de France wird der Lehrstuhl für die Geschichte der Religionen neu ausgeschrieben. Mauss sieht seine Chance gekommen und bewirbt sich erneut auf den Lehrstuhl. Sein Hauptmitstreiter ist der Theologe und Historiker Alfred Loisy, der aufgrund seines "Modernismus" von der katholischen Kirche exkommuniziert wurde. Viele glauben an Mauss’ Chancen und unterstützen seine Bewerbung. Aber Loisy genießt ebenfalls eine starke Unterstützung und erhält schließlich den Lehrstuhl. Mauss, der noch auf die Ehrenstelle als Vertreter Loisys gehofft hatte, verliert auch diese Wahl, was für ihn und seine Freunde eine umso größere Enttäuschung ist, als dass alle um die Seltenheit solcher Gelegenheiten wissen.[fn:84] Zu dieser Enttäuschung kommt eine weitere hinzu, die Mauss' eigene Forschung betrifft: Seine Arbeit an der Dissertation zum Gebet schreitet nicht voran.

Seit mehr als zehn Jahren sammelt Mauss Daten zu positiven Riten wie dem Gebet und in den Jahren zwischen 1907 und 1908 ist er davon überzeugt, dass er sein Manuskript bald fertigstellen kann. Aber die ersten Seiten, die er Durkheim, Espinas und Sylvain Lévi zu lesen gibt, sind enttäuschend. Mauss verliert sich in seinen Daten und findet keinen Ausweg zur Synthese. Zudem entdecken Mauss und Durkheim in Carl Strehlows Arbeiten zu den australischen Aranda- und Loritja-Stämmen viele weitere Daten, die Mauss dazu bewegen, seine Arbeit an dem Gebet stark zu revidieren. Mauss sieht im Gebet eine Kreuzung der wichtigsten religiösen Phänomene, die in einer einfachen bzw. individuellen und mündlichen Form ausgedrückt werden, um unmittelbar auf die sakralen Gegenstände und Akteure zu wirken. Das Gebet versteht Mauss im Lichte der Arbeiten, die er liest, wie eine Handlung auf Distanz, mit der beabsichtigt wird, sakrale Gegenstände und Akteure zum Handeln zu bringen. /Das Gebet/ (/La Prière/) verfasst Mauss in der Zeit, in der Durkheim an /Die elementaren Formen des religiösen Lebens/ (/Les Formes élémentaires de la vie religieuse/, 1912) arbeitet. Beide Werke beziehen sich auf ähnliche Daten zu den australischen Aborigine- und neuseeländischen Maori-Kulturen und stützen sich gegenseitig.[fn:85]. Aber im Jahr der Veröffentlichung von /Die elementaren Formen des religiösen Lebens/ hat Mauss seinen Text zum Gebet noch immer nicht fertiggestellt. Fortwährend den nächsten Schriften von Strehlow auf der Spur, wird Mauss müde und krank. Von der Schrift /Das Gebet/ sind heute 176 Seiten überliefert, die Mauss nie zur Vollendung gebracht hat. Der Krieg wird die letzten Hoffnungen begraben, aus dem Gebet eine Dissertation zu entwickeln.

** Elsass und der Hintergrund von Gift, Gift

"'Ich fühle mich prächtig gut. Ich war dafür und gar nicht für die Soziologie gemacht'".[fn:86] Mauss erlebt an der Front einen ganz anderen Marcel, der sich für lange Spaziergängen und für das Bergsteigen begeistert und den Eindruck bekommt, dass er in diesem gefährlichen Kontext auf einmal selbstständig den Kurs seines Lebens bestimmen kann. Aber die Härte des Krieges wird ihm nicht erspart. Mauss erfährt im Laufe der Jahre den Tod von den vielen Freunden, die mit ihm an der EPHE oder an /L'Année/ mitgearbeitet haben. Ihn treffen die sukzessiven Nachrichten des Todes von André Durkheim dem Sohn seines Onkels und von Durkheim selbst im Jahre 1917 besonders hart. Zurück aus dem Krieg muss sich Mauss im zivilen Alltag wieder abfinden. Es geht primär nicht um die akademische Arbeit, sondern um die letzten gesellschaftlichen und insbesondere politischen Ereignissen, die Frankreich und die Länder Europas nach dem Ersten Weltkrieg beschäftigen. Jaurès ist gestorben, und die sozialistische Partei wurde reformiert. Sie trägt den Namen /Section française de l’Internationale ouvrière/ (SFIO). In Russland hat eine russische Revolution stattgefunden, die den französischen Sozialisten die Frage stellt, ob sie zum Kommunismus überlaufen sollten. In Konkurrenz zur SFIO bildet sich 1920 die erste französische kommunistische Partei (PCF), die auf Anhieb doppelt so viele Mitglieder wie die SFIO (120.000 zu 50.000) registriert.[fn:87]. /L’Humanité/, bei der Mauss Vorstandsmitglied geblieben ist, trennt sich von der SFIO, um zum Veröffentlichungsorgan der PCF zu werden. Mauss, der der russischen Revolution und der kommunistischen Partei kritisch gegenübersteht,[fn:88] wird aus dem Vorstand von /L’Humanité/ ausgeschlossen. Seine politische Haltung formt er am Vorbild von Sidney und Beatrice Webb in Großbritannien, die eine Art von Sozialreformismus unterstützen, der nach Ansicht von Mauss zur nationalen Einheit beitragen kann. Nach dem Ersten Weltkrieg benötigen die Länder Europas vor allem Einheit, weshalb jede Art von Spaltung der Sozialisten vermieden werden sollte, die zur Spaltung Frankreich und wieder zur Spaltung Europa führen könnte. Diese Sorgen von Mauss teilen mehrere Kollegen wie Christian Pfister an der wieder französisch gewordenen Universität Straßburg, der Mauss zur Festschrift für Charles Andler einlädt und /Gift, Gift/ veröffentlicht. /Gift, Gift/ ist nicht nur ein akademischer Text, der Mauss zur Zusammenfassung seiner vergangenen Überlegungen hilft und der Anmeldung seines künftigen Thema zur Gabe dient. Es ist auch ein politischer Text angesichts des Kontextes seiner Veröffentlichung und der inhaltlichen Botschaft in Bezug auf diese erwünschte Einheit der Gesellschaften nach dem Krieg.

Charles Andler wie Christian Pfister sind nicht in Straßburg zufällig. Beide sind Elsässer -- Andler ist in Straßburg geboren. Christian Pfister bekommt den Lehrstuhl für die Geschichte Elsass (1919). Charles Andler ist Professor für deutsche Literatur und deutsche Sprache an der Fakultät für Literatur der Universität in Paris. Eng befreundet mit Lucien Herr, der als Bibliothekar der Durkheim-Schule fungiert, ist Andler im regelmäßigen Austausch mit Durkheim und der Durkheim-Gruppe.[fn:89] Im Ersten Weltkrieg unterstützen Durkheim, Mauss, Sylvain Lévi und Lucien Lévy-Bruhl Andler, der die /Ligue républicaine d'Alsace-Lorraine/ leitet und in diesem Zusammenhang das französische Recht in den besetzen Gebieten in Elsass verbreiten muss. Damit verbunden ist die Idee, eine französische Universität in Straßburg zu gründen, wenn die Deutschen besiegt und Elsass wieder nach Frankreich zurück kommen würde.[fn:90] Diese Idee, die ab 1915 im Rahmen der /Conférence d'Alsace-Lorraine/ -- eines Ausschusses des französischen Außenministeriums -- erwähnt wird, wird konkreter im Jahre 1917, wenn der französische Kriegsminister für die Verwaltung Elsass-Lothringens verantwortlich wird[fn:91] und eine Abteilung /Service d'Alsace Lorraine/ aufbaut, die einen Ausschuss für Hochschulen ins Leben ruft, dazu Pfister und Andler mit fünf anderen Kollegen gehören.[fn:92] Diese sieben Professoren verfassen einen Bericht zur Rekonstruktion der Universität Straßburg, die zu einer der wichtigen Universität in Frankreich werden soll -- und gleichzeitig ein Schaufenster der französischen akademischen Exzellenz in der Rivalität mit dem deutschen Hochschulsystem. Pfister muss entsprechend eine Fakultät für Literaturwissenschaft aufbauen, und innerhalb dieser Fakultät wird 1919 der ehemaligen Lehrstuhl für Soziologie und Pädagogik von Georg Simmel an den Durkheim-Schüler Maurice Halbwachs gegeben, der 1922 den Lehrstuhl zum Lehrstuhl für Soziologie umbenannt.[fn:93] Das ist der erste Lehrstuhl für Soziologie an einer französischen Universität.

Seit seiner Herstellung war die Vergabe dieses Lehrstuhls an die Durkheim-Schule wie selbstverständlich: "Die Soziologie hat (...) unter der Leitung von Meistern wie Durkheim so große Fortschritte gemacht, dass es unerlässlich ist, dass diese Wissenschaft in Straßburg vertreten ist" sagt Pfister.[fn:96] Für die Durkheim-Gruppe kompensiert die Einrichtung des Straßburger Lehrstuhls den Verlust des Lehrstuhls für Sozialphilosophie in Toulouse im Jahr 1921, der seit 1908 zunächst von Bouglé und dann von Fauconnet besetzt war. Pfister gesteht gerne, dass er unter dem Einfluss von ehemaligen Durkheim-Schüler wie etwa Lévy-Bruhl und Salomon Reinach stand.[fn:97]. Als er an der Ecole Normal Supérieure "Quadrat und Kubik war", freute er sich, ehemalige Schüler des Lycée Louis-le-Grand willkommen zu heißen, darunter "insbesondere Durkheim, den bereits mächtigen und kraftvollen Philosophen".[fn:98] Von Oktober 1914 bis Oktober 1918 war Halbwachs auch Professor für Philosophie am Lycée de Nancy in der Stadt, in der Pfister 25 Jahre lang unterrichtet hat. Andler gefällt eine solche Entscheidung, die seiner Vision für die Universität Straßburg entspricht. Wie Pfister und sein Freund Herr "träumten [sie] davon, daraus die Grundlage für eine nationale Reform des Hochschulwesens bereitzustellen. Sie wollten, dass der Forschung mehr Gewicht im Vergleich zur Vorbereitung auf Prüfungen und Auswahlverfahren beigemessen wird. Sie wollten auch die zunehmende Abschottung der Disziplinen bekämpfen, die Forschung und Lehre zunehmend prägte".[fn:94] Die Vorschläge von Andler werden nicht alle aufgenommen, aber die neue französische Universität in Straßburg folgt der allgemeinen Linie, die sich Andler und andere Akademiker wünschen -- in den Worten Craig muss diese Universität "an instrument of nation building" werden.[fn:95] Die Nation aufbauen, bedeutet in diesem Kontext nicht nur Frankreich wieder aufzubauen, sondern über die Universität in Straßburg aus Frankreich hinaus zur Bildung einer europäischen Nation beizutragen, die zeigen würde, wie Frankreich in diesem Gebiet im voraus der anderen europäischen Nation sei und darunter speziell vor Deutschland.

Damit erklärt sich auch die besondere Hervorhebung des deutschen Rechtes und der Vielfalt der deutschen Sprache in /Gift, Gift/, die hier nicht zufällig ausgewählt wurden und auch nicht nur deshalb, weil Andler ein in Frankreich anerkannter Germanist ist. Es geht um die Mitteilung einer Botschaft, die darin besteht, dass Frankreich in der Verbindung zu Deutschland, in der Befriedung der Verhältnisse zu Deutschland und in der Wiederaufnahme des Austauches mit Deutschland die Idee der Nation jenseits von Nationalismen entwickeln kann, sie auf eine andere Ebene der gesellschaftlichen Organisation -- auf der Ebene Europas -- entwickeln kann. Dabei geht es, wie die Gabe zeigt, um Frieden, Austausch, um die gegenseitige Nacheiferung im Aufbau einer geteilten totalen sozialen Tatsache. Diese in /Gift, Gift/ implizite Botschaft zur inter-nationalen Einheit macht Mauss explizit in seinen unterschiedlichen Schriften in der Unterstützung des Sozialismus in Frankreich, dessen Einheit mit der Bildung der französischen kommunistischen Partei zu kippen droht.

** Sozialismus und Genossenschaften nach dem Ersten Weltkrieg

1912 hat Mauss an dem Kongress in Tours teilgenommen, der das Ziel hatte, die Genossenschaften in Frankreich zu vereinheitlichen. Als Beauftragte der /Fédération nationale des coopératives/ arbeitet er seit 1911 an der neuen Strukturierung der Genossenschaften in Elsass und darunter insbesondere der sozialistischen Genossenschaften und Arbeitergenossenschaften, die 1914 im neuen Verband der Genossenschaften Nord-Osten zusammengestellt werden.[fn:99] Unmittelbar nach dem Ersten Weltkrieg nimmt Mauss an dem Pariser Genossenschaftskongress, und er erwähnt die Bedeutung der Propaganda zur Verbreitung der Genossenschaften in Frankreich.[fn:100] Mauss geht es um die Ausbildung der Genossenschafter auf die sozialistischen Ideen an einem Moment, an dem diese Ideen von den Kommunisten in Frankreich und von den Bolschewiken im internationalen Raum herausgefordert werden. Diese Propaganda-Arbeit ist Mauss umso wichtiger, als mit der enttäuschenden Wende der Zeitung /L'Humanité/ zum Kommunismus eine solche Arbeit erschwert wurde. Deshalb auch investiert Mauss ab 1921 die neu gegründete Zeitung /Le Populaire/, die seiner Auffassung nach zum Veröffentlichungsorgan der Sozialisten entwickelt werden sollte. Zwar ist /Le Populaire/ eine kleine Zeitung, aber sie wird zu einem wichtigen Sprachrohr des Widerstandes gegen die kommunistische Ideologie und später auch gegen die faschistische Ideologie. Mit seinen Veröffentlichungen in dieser Zeitung möchte Mauss nicht nur die Einheit der Sozialisten beschwören, sondern ebenso die Einheit zwischen Soziologen und Sozialisten fördern. Die Soziologie steht nach Mauss im Dienste des Sozialismus, der mithilfe der Soziologie die Regierungen über drängende gesellschaftliche Fragen der Gegenwart und die Bevölkerungen über die Handlungen ihrer Regierung exakt informieren kann. Die Soziologie hat die Aufgabe, Regierungen und Bevölkerungen auszubilden und Handlungsformen für ein harmonisches Gesellschaftsleben vorzuschlagen. Solche Handlungsformen bieten Genossenschaften an, wie es Mauss immer wieder wiederholt, weshalb es sehr wichtig ist, die Propaganda in diesem Zusammenhang weiter voran zu treiben.

Mauss unterstützt entsprechend die Gründung



als einer deren größten Fürsprecher in Frankreich er sich selbst sieht und über die er sich in den ersten Jahren nach seiner Rückkehr aus dem Krieg regelmäßig ins Bild setzen lässt. In Frankreich werden Initiativen zur Förderung der Genossenschaften als wirtschaftliche und rechtliche Organisationsform aktiv vorangetrieben. 1921 gründet der Rechtswissenschaftler Bernard Lavergne die Zeitschrift Revue des études coopératives, die Mauss finanziell unterstützt (Fournier 1994, 445). Die Genossenschaften stellen für Mauss das Laboratorium eines gesellschaftlichen Experiments zur Reformierung des gesellschaftlichen Lebens dar – angefangen bei den grundlegenden Problemen der Konsumwirtschaft und der Ausbildung junger Generationen. Seiner Vorstellung nach sollte die Idee der Genossenschaft Teil des Lehrplans in Schulen werden. Jedoch wird Mauss, der sich in dieser Zeit erneut dem Kampf für den Sozialismus widmet, von Hubert daran erinnert, dass er als Neffe Durkheims und Mitarbeiter von L’Année ebenfalls an die weitere Entwicklung des wissenschaftlichen Vorhabens der Durkheimianer zu denken habe und dies seine erste und ungleich wichtigere Pflicht sei.



* Bibliographie

#+cite_export: csl /home/cpsoz/OrgCSL/chicago-author-date.csl
#+print_bibliography:

* Footnotes

[fn:100] Vgl. [cite:@CongresParis1919].
[fn:99] Vgl. [cite:@CongresTours1912; @Petot1914].

[fn:98] Vgl. ebd.
[fn:97] Vgl. [cite:@Bloch1933 551].

[fn:96] Vgl. [cite:@Craig1979 9].
[fn:95] Vgl. [cite:@Craig1984 204].

[fn:94] Vgl. [cite:@Blum1992 32].
[fn:93] Vgl. [cite:@Becker2003 179].

[fn:92] Vgl.[cite:@Hallays1919 242; @Craig1984 406].
[fn:91] Vgl. [cite:@PVCAL1919 3-9].

[fn:90] Vgl. [cite:@Crawford2005 142].
[fn:89] Vgl. [cite:@Fournier2007 865].

[fn:1] Ebd., 495, Brief 407 vom 25.07.1923; ebd., 496, Brief 408 vom 9.08.1923.

[fn:2] Ebd., 484, Brief 396 vom 31.07.1922.

[fn:3] Ebd., 496, Brief 408 vom 9.08.1923.

[fn:4] Vgl. [cite:@Hertz2007].

[fn:5] Vgl. [cite:@Paoletti2012b 345].

[fn:6] Vgl. [cite:@Paoletti2012b 354f.]. Dazu auch vgl. [cite:@Hertz2007 211], in dem Hertz vom /homo duplex/ spricht.

[fn:7] Vgl. [cite:@Mauss1926 109].

[fn:8] Vgl. [cite:@Mauss1921 36], der Boas unmittelbar als seine Quelle zum /potlatch/ erwähnt.

[fn:9] Vgl. [cite:@Davy1922].

[fn:10] Vgl. [cite:@Besnard1985].

[fn:11] Ebd., 248.

[fn:12] Ebd.

[fn:13] Ebd.

[fn:14] Vgl. [cite:@Benthien2021 478-479, Brief 301 vom 26.03.1922].

[fn:15] Vgl. [cite:@Besnard1985 252].

[fn:16] Ebd., 254.

[fn:17] Vgl. [cite:@Mauss1974b].

[fn:18] Vgl. [cite:@Mauss2012c 291].

[fn:19] Vgl. [cite:@Benthien2021 444, Brief 358 vom 21.01.1919].

[fn:20] Vgl. [cite:@Fournier2007 258].

[fn:21] Ebd., 449, Brief 362 vom 3.10.1919.

[fn:22] Ebd., 447, Brief 360 vom 19.10.1919.

[fn:23] Ebd., 454, Brief 366 vom 6.10.1920.

[fn:24] Vgl. [cite:@Fournier2007 157].

[fn:25] Vgl. [cite:@Besnard1987 76].

[fn:26] Vgl. [cite:@Fournier2007 513].

[fn:27] Vgl. [cite:@Besnard1979 17ff.]

[fn:28] Vgl. [cite:@Dumont1991 201; @Moebius2012 629-643].

[fn:29] Vgl. [cite:@Fournier1994 149].

[fn:30] Vgl. [cite:@Paoletti2012b 301].

[fn:31] Vgl. [cite:@Pickering1979 163].

[fn:32] Vgl. [cite:@Fournier2007 463; @Cabanel2017].

[fn:33] Vgl. [cite:@Tarot2003; @Fournier1994].

[fn:34] Vgl. [cite:@Sembel2015b 10].

[fn:35] Vgl. [cite:@Fournier2007 545, Fn. 3].

[fn:36] Vgl. [cite:@Lukes1973 327; @Moebius2006 114f.]

[fn:37] [cite:@Mausspr1898 2; @Mausspr1899 2; @Mausspr1899b 3-4].

[fn:38] Vgl. [cite:@Maussprorgsyndic-1-1899 4; @Maussprorgsyndic-2-1899 3; @Maussprorgsyndic-3-1899 3; @Maussprorgsyndic-4-1899 3; @Maussprorgsyndic-5-1899 4].

[fn:39] Vgl. [cite:@Mauss1997 72-82].

[fn:40] Vgl. [cite:@Maussprgen1900 1].

[fn:41] Vgl. [cite:@GeraultRichardprgen-2-1900 1].

[fn:42] Vgl. [cite:@Guillemin-1900 3].

[fn:43] Vgl. [cite:@Longuet-1900 2].

[fn:44] Vgl. [cite:@Longuet-2-1900 2; vgl. auch @Maussunioncoop1900 4].

[fn:45] Vgl. [cite:@Longuet-1900 2].

[fn:46] Vgl. [cite:@Hamelin-1-1900 3].

[fn:47] Vgl. ebd.

[fn:48] Vgl. [cite:@Hamelin-2-1900 2].

[fn:49] Vgl. ebd.

[fn:50] Vgl. [cite:@NN-1901-4 4].

[fn:51] Vgl. [cite:@NN-1901-1 3].

[fn:52] Vgl. [cite:@NN-1901-2 4; @NN-1901-3 4; @NN-1902-1 4; @NN-1902-2 4; @NN-1902-3 4].

[fn:53] Vgl. [cite:@Guillemin1905 6]

[fn:54] Vgl. [cite:@Cuin1997 12f.; @Karsenti1997 63ff.]

[fn:55] Vgl. [cite:@Mauss1990 176].

[fn:56] Vgl. [cite:@Namer1977; @Paoletti2012].

[fn:57] Vgl. [cite:@Robertson2003 142].

[fn:58] Vgl. [cite:@Paoletti1998 111f.].

[fn:59] Vgl. [cite:@Fournier2007 587].

[fn:60] Vgl. [cite:@Besnard1979 19ff.].

[fn:61] Vgl. ebd., 23-24.

[fn:62] Vgl. [cite:@Fournier2007 705].

[fn:63] Vgl. [cite:@Schuettpelz2017 118; @Hsu2017 91f.]

[fn:64] Vgl. [cite:@Mausscoop1902 5].

[fn:65] Vgl. [cite:@Clark1972 171].

[fn:66] Vgl. [cite:@Mausshuma-1-1904 8].

[fn:67] Vgl. [cite:@Mausshuma-3-1904 1].

[fn:68] Vgl. [cite:@Mausshuma-2-1904 4].

[fn:69] Ebd.

[fn:70] Vgl. [cite:@Mausshuma-4-1904 4].

[fn:71] Vgl. [cite:@Mausshuma-3-1904 1].

[fn:72] Vgl. [cite:@Mausshuma-5-1904 3].

[fn:73] Vgl. [cite:@Mausshuma-1-1905 4].

[fn:74] Vgl. [cite:@Mausshuma-2-1905 4].

[fn:75] Vgl. [cite:@Mausshuma-3-1905 3].

[fn:76] Vgl. [cite:@Gaumont1923 189].

[fn:77] Vgl. ebd., 361.

[fn:78] Vgl. [cite:@Guilleminhuma-1-1906 1].

[fn:79] Vgl. [cite:@NNcoop-1905].

[fn:80] Vgl. [cite:@NNcoop-1910 5; @NNcoop-1911 5].

[fn:81] Vgl. [cite:@NNcoop-1912 5].

[fn:82] Vgl. [cite:@Benthien2015 209ff.].

[fn:83] Vgl. [cite:@Fournier1994 322].

[fn:84] Vgl. ebd., 329f.

[fn:85] Vgl. [cite:@Sembel2015b 17].

[fn:86] Vgl. [cite:@Fournier1994 374].

[fn:87] Vgl. [cite:@Fournier1994 417].

[fn:88] Vgl. [cite:@Steiner2005 203ff.].
