#+Setupfile: /home/cpsoz/OrgTemplates/odt-de.org
#+bibliography: Mauss-Bib.bib

* Kommentar

Wenn Mauss im Laufe Januar 1919 aus dem Kriegsdienst entlastet wird,[fn:1] fängt eine Zeit der schwierigen Rückkehr zum zivilen und akademischen Leben an, oder wie Mauss im Briefwechsel mit Henri Hubert mitteilt: "Ich bin gerade dabei, mich neu einzurichten, was nicht einfach ist. (...) Es muss mit einer relativ langen Rückkehr zur Barbarei gerechnet werden".[fn:2] Der Erste Weltkrieg ist beendet. Die Lust auf die Wiederaufnahme der wissenschaftlichen Arbeit ist vorhanden, und die Erwartungen sind groß. Schon im September 1919 fragen ihn die ehemaligen Kollegen,[fn:3] ob es nicht gut wäre, die Arbeit an /L'Année sociologique/ -- der Zeitschrift für Soziologie der Mitarbeiter um Emile Durkheim und Marcel Mauss, die nach 1912 nicht mehr veröffentlicht wurde --, wieder aufzunehmen. Und die alten sozialistischen Kameraden der Genossenschaftsbewegung müssen auch nicht vergessen werden, sowie die persönlichen Projekten, die in dieser Zeit vielleicht mehr als vor dem Anfang des Krieges an erneuter Bedeutung gewonnen haben -- dabei insbesondere das Projekt von einem Buch zum Thema der Nation, davon Mauss Hubert mit einem kaum enthaltenen Enthusiasmus den schon halb abgeschlossenen Plan mit fortgeschrittenen verfassten Textteilen vorstellt.[fn:4] Es gibt sehr viel zu tun, um den Anschluss an die Ideen vor 1914 wieder herzustellen, viele Leute zu treffen, andere zu würdigen, die ihr Leben auf dem Schlachtfeld verloren haben. Darunter zählt man eine große Anzahl an ehemaligen Studenten und Freunden von Mauss, die für /L'Année/ gearbeitet haben oder mit Mauss in der Unterstützung des Sozialismus in Frankreich gewirkt haben. Von diesem Übergang aus den Trümmern des Krieges ins neue freie Leben bezeugt Mauss' /Gift, Gift/ in seiner Form und in seinem Inhalt, im Text wie im Paratext.

Wann Mauss /Gift, Gift/ verfasst, kann nicht mit Sicherheit ermittelt werden. 1922 erscheint der Text in der Festschrift zu Charles Andler. Aber es bleibt fraglich, ob ihn Mauss speziell für diese Angelegenheit vorbereitet oder schon früher bzw. vor dem Krieg verfasst hat. Inhaltlich behandelt Mauss in /Gift, Gift/ Themen, die in enger Verbindung mit den Themen stehen, die Mauss in seiner jungen Karriere mit Hubert herausgearbeitet hat. Es geht um die magischen und religiösen Phänomenen verschiedener Gesellschaften und Kulturen auf den fünf Kontinenten mit besonderer Berücksichtigung der melanesischen Inseln in der Pazifik, der einheimischen Stämmen Nordamerikas, der alten indoeuropäischen Gesellschaften. Es geht auch speziell um eine Vielfalt von Gabenpraktiken, die Mauss zumindest seit seinen Arbeiten zu den Opferriten und der Magie aus den Jahren 1899-1903 mit Durkheim und Hubert regelmäßig behandelt. Mit der Rückkehr zur Zivilleben und zur Forschung fragt sich Mauss im Dialog mit Hubert,[fn:5] ob ein solches Phänomen wie die Gabe nicht ein eigenes Werk verdienen würde, etwa im Rahmen einer neuen Betrachtung der Magie oder der neuen Behandlung vom unvollendeten Gebettext vertieft werden sollte,[fn:6] den Mauss vor dem Ersten Weltkrieg zu einer Dissertation anfertigen wollte. Aber der Weg zurück an die Arbeit ist steinig. Vom Oktober 1921 bis August 1922 leidet Mauss unter einer Lugenkrankheit, die ihn erschöpft. Wenn er wieder gesund ist, warten auf ihn seine wichtigere Projekte, die er unbedingt zum erfolgreichen Ende bringen will,[fn:7] nämlich sein geplantes Buch zum Thema der Nation und die Nachfolge von /L'Année sociologique/. Die Texte wie /Gift, Gift/, die dazwischen kommen, sind zwar auch nicht unwichtig, weil sie Mauss erlauben, seine Überlegungen zu Gabenpraktiken weiter zu entwickeln. Allerdings sollten sie ihn nicht zu lange aufhalten, weshalb sie eher kurz sein sollten und unmittelbar zum Argument kommen, das Mauss vorschlägt. /Gift, Gift/ zeigt es beispielhaft: Der Text ist kurz und dessen zentrale Botschaft schnell ermittelt: Gaben sind ambivalent bzw. sind Geschenke sowie Giftstoffe. Am Ende von /Gift, Gift/ wird den Status von diesem Text bestätigt: Er soll eine Einführung in die Komplexität von Gaben und Gabenpraktiken liefern, die zu einem späteren Zeitpunkt -- nämlich im späteren Essay /Die Gabe/ (1925) -- weiter entwickelt werden.

/Gift, Gift/ fängt mit der Erwähnung der zwei Bedeutungen von Gift als Geschenk und Giftstoff an, wobei die Verbindung zwischen beiden Begriffen auf Deutsch, Englisch und Holländisch nicht eindeutig geklärt ist. Weil ihn die Literatur zum Begriff "Gift" nicht zufriedenstellt, schlägt Mauss eine Hypothese vor: Die Bedeutungen von "Geschenk" und "Giftstoff" wurden im Begriff "Gift" miteinander verbunden, um die Bedeutung von Gift als Giftstoff abzumildern bzw. um die Gefahr, die die Bedeutung von "Gift" als Giftstoff enthält, zu dämpfen und die Verwendung des Begriffes zu ermöglichen. In diesem Zusammenhang gibt es eine unmittelbare Verbindung zu den Arbeiten vom Studenten und Freunden Mauss' Robert Hertz (1881-1915) insbesondere in Bezug auf die religiöse Polarität und die Sühne in den alten Gesellschaften.[fn:8] Hertz ist nicht nur der Kameraden im Rahmen des politischen Engagements im Sozialismus an der Seite von Mauss. Er ist auch derjenige, davon Mauss wie Durkheim dachten, dass er die Zukunft der Durkheim-Schule darstellen würde.[fn:9] Insbesondere mit seiner Studie zur Vorherrschaft der rechten Hand gibt Hertz Durkheims These der Dualität im Menschen neue Dimensionen. Nach Durkheim ist der Mensch ein /homo duplex/ in diesem Sinne, dass er zwei Bewusstseinzustände einverleibt.[fn:10] Der erste Bewusstseinzustand führt zur Entwicklung einer individuellen Persönlichkeit und der zweite Bewusstseinszustand zur Entwicklung einer sozialen Bewusstsein. Nach Durkheim setzt diese Dualität im Menschen die grundsätzlichere Dualität zwischen dem Sakralen und dem Profanen voraus: Die zwei unterschiedlichen Bewusstseinszustände sind aus dieser grundsätzlichen Unterscheidung zwischen dem Sakralen und dem Profanen entstanden. Hertz verallgemeinert diese These Durkheims insofern, als er die innerliche Dualität im Menschen auf die Ebene einer Dualität zwischen Natur und Gesellschaft bringt. Einerseits gibt es profane Gegenstände, die gleichzeitig symbolisch mit dem Bösen, dem Schlechten, dem Unreinen assoziiert werden, die allesamt Merkmale sind, die mit der linken Hand verbunden sind. Andererseits gibt es das Gegenteil bzw. das Sakrale, das gleichzeitig das Gute, das Reine, das Richtige, die mit der rechten Hand assimiliert werden. Diese Dualität innerhalb vom Menschen spiegelt sich außerhalb von ihm in der Form von Klassifikationssystemen wider, die auf die alltäglichen Gegenstände sowie in der Aufteilung des Raumes und der Zeit, der sozialen Rollen und Berufen, in der Hierarchisierung der Götter, der Teilung der Geschlechter und der Generationen verwendet werden. Wie Mauss in /Gift, Gift/ sagt, die Vielfalt der Gaben ruht auf einem breiten Spektrum an Bedeutungen zwischen dem Sakralen und dem Profanen, davon sie jeweils einen Aspekt des asymmetrischen Verhältnisses zwischen diesen Polaritäten bezeichnen, weil die Gaben immer an diese untrennbare Unterscheidung zwischen dem "Geschenk" und dem "Giftstoff" verweisen, die die untrennbare Beziehung zwischen dem Sakralen und dem Profanen im Alltag der Austauschpraktiken in diesen Gesellschaften der Gabe übersetzt. Zusammen betrachtet, bilden diese Gaben eine Totalität von Dienstleistungen, die an die Totalität der Gesellschaft erinnert, die unmittelbar oder mittelbar an solchen Dienstleistungen teilnimmt.

Deshalb spricht Mauss in /Gift, Gift/ von der Gaben als System der totalen Leistungen bzw. der juristischen, politischen, ökonomischen und religiösen Leistungen. Mit dem Begriff der Leistung verdeutlicht er das rechtliche Merkmal der Gaben: Gaben werden als Folge der Schließung von einem Vertrag getätigt. Mit dem Attribut "total" sagt Mauss, dass diese Leistungen alles betreffen, was in Unterstützung von Dritten getan werden kann. In einem späteren Text erklärt Mauss: "eine Gruppe von Menschen, ob hierarchisch organisiert oder nicht, schuldet einer bestimmten Anzahl anderer Menschen, Verwandten oder Verbündeten, die einen symmetrischen Platz beziehen (übergeordnet oder gleichwertig oder untergeordnet oder unterschiedlich aufgrund des Geschlechts), eine ganze Reihe moralischer und materieller Leistungen (Dienste, Frauen, Männer, militärischer Hilfe, ritueller Speisen, Ehren, usw.), und sogar die ganze Reihe dessen, was ein Mensch für einen anderen tun kann. Im Allgemeinen werden diese totalen Leistungen von Klan zu Klan, von Altersklasse zu Altersklasse, von Generation zu Generation, von Verbündeten zu Verbündeten erbracht. (...) Im Allgemeinen erfolgen diese Leistungen innerhalb dieser Gruppen und von Gruppe zu Gruppe entsprechend dem Rang der einzelnen Personen".[fn:11] In /Gift, Gift/ wie in /Die Gabe/ spricht Mauss von einem "System" der totalen Leistungen, und mit diesem Begriff "System" unterstreicht er zwei Merkmale der Gaben: a) die Gaben bilden in den unterschiedlichen Gesellschaften eine Einheit von sozialen Leistungen, die mehr oder weniger homogen sind und sich von anderen gesellschaftlichen Praktiken unterscheiden; b) diese Einheit entsteht aus der (unmittelbaren oder mittelbaren) Integration aller Menschen einer sozialen Gruppe bzw. einer Gesellschaft in die Gabenpraktiken. Mit dem ersten Merkmal sagt Mauss, dass Gabenpraktiken in der Gesellschaft nicht ständig stattfinden, sondern es gibt Bedingungen, die erfüllt werden müssen, damit Gabenpraktiken entwickelt werden. Diese Bedingungen spiegeln sich in der Vielfalt der Namen von Gaben wider, die geleistet werden, und sie verorten diese Gaben in der Vielfalt der Praktiken in einer Gesellschaft. Etwa die Mitgift, die Mauss in /Gift, Gift/ erwähnt, bezeichnet im Allgemeinen das Heiratsgut der Braut an die Familie des Bräutigames, das in der Hochzeitzeremonie mitgegeben wird. Die Morgengabe ist eine nähere Bezeichnung der Mitgift als das Heiratsgut der Braut, das am Morgen vor der Hochzeitzeremonie geleistet wird. Mit diesem zweiten Merkmal verdeutlicht Mauss, dass die Gabenpraktiken eine Wirkung auf den Zusammenhalt der Gesellschaft haben, den sie stärken. Weil die Gabenpraktiken alle Menschen in einer Gesellschaft direkt oder indirekt einbeziehen, tragen sie entsprechend zur engeren gesellschaftlichen Kohäsion, die die Wirkung auf die Akteure in dieser Gesellschaft hat, dass sie ihre Gesellschaft als Einheit aus der Praxis der Gaben besser wahrnehmen können, sie sich besser vorstellen können. Hier findet man nochmal die Verbindung mit der grundsätzlichen Unterscheidung zwischen dem Sakralen und dem Profanen, die das gesellschaftliche Leben strukturieren: Anhand von Gaben geben sich die Menschen die Möglichkeit, es zu wissen, wo sie sich als gesellschaftliche Einheit in diesem Verhältnis zwischen dem Sakralen und dem Profanen befinden, um Korrekturmechanismen zu verwenden, wenn dieses Verhältnis drohen würde, gestört bzw. geschwächt zu werden. Einer dieser Korrekturmechanismen ist der /potlatch/.

Mauss wird von dem /potlatch/ in /Die Gabe/ ausführlich reden, und in /Gift, Gift/ liefert er eine Zusammenfassung der wesentlichen Merkmale vom dieser Form von Gaben, die er als "agonistische[n] totalen Leistungen" bezeichnet. Solche Leistungen werden im Rahmen von Gabenpraktiken getätigt werden, die alle ein Element der Herausforderung enthalten. Eine Herausforderung kann nur eine Partei des Gabentausches betreffen, der seinen Wert als guter Partner im Gabenaustausch belegen muss. Sie kann beide Parteien betreffen, die sich gegenseitig als gleichwertig im Rahmen von Ehrenkämpfen zeigen müssen. Sie kann auch die ganze Gesellschaft betreffen, die ihre Stärke als Kollektiv belegen muss. Nicht nur die Rivalität und die Revanche stehen auf dem Spiel, die eine Konkurrenz zwischen den Parteien im Gabentausch um die beste Leistung unterstützen, die sie bringen müssen, sondern auch die Formen der Zerstörung von Vermögen als Korrektur von gesellschaftlichen Asymmetrien. Bei Gabenpraktiken in der Form von agonistischen Leistungen geht es nicht ausschließlich nur darum, dass man sich als Herrscher und Gewinner im Tausch zeigt, sondern auch dass man viel Leid und Verlust mit Leichtigkeit und Ausdauerkraft ertragen kann. In beiden Fällen von Gewinnen und Verlusten zeigen die Menschen und Kollektiven nicht nur ihre Durchsetzungskraft im Umgang mit Herausforderungen, die ihnen von ihren Austauschpartnern gestellt werden. Sie belegen auch ihre Zuverlässigkeit als diese Austauschpartner, mit denen es in nächsten Gabenaustauschen gerechnet werden kann, um die Komplexität der Gabenpraktiken und die Gefahren, die mit Gaben einhergehen, zu beherrschen. Im Kontext dieser Einordnung des /potlatch/ in den Gabenpraktiken ist es für Mauss nach wie vor wichtig, es zu präzisieren, dass diese Praktiken nicht nur bei den einheimischen Stämmen Nordamerikas zu finden sind, wie Franz Boas davon in seinem Buch zu den Kwakiutl berichtet hat,[fn:12] sondern auf auf den melanischen Inseln sowie bei den Kelten und den Germanen. Mit diesem Argument geht es bei Mauss darum, es nahezulegen, dass die Gabenpraktiken vielleicht überall in den unterschiedlichen Gesellschaften der Welt entwickelt worden sind. Besonders wichtig ist hier ebenfalls die Aussagen, dass solche Formen von agonistischen Gabenpraktiken bei den Kelten festzustellen seien, und dass sie ihre Spuren bis im alten keltischen Recht hinterlassen haben. In diesem Zusammenhang geht es Mauss nicht darum, an das Organisationsprinzip der soziologischen Untersuchung zu erinnern, die die Besonderheit der Arbeiten der französischen Soziologieschule ausgemacht hat: Unsere Gesellschaften nicht nur mit alten Gesellschaften in der Geschichte zu vergleichen, sondern auch mit Gesellschaften aus anderen Kulturen in der ganzen Welt. Es geht auch ganz konkrete um Korrekturen und Einordnungen von Dissonanzen, die in der Zeit der Veröffentlichung von /Gift, Gift/ Mauss überrascht, weil sie aus dem eignen Stahl kommen und in einer Polemik um die Dissertation von Georges Davy kristallisiert werden.[fn:13] Philippe Besnard hat damals einen berühmten Aufsatz zu dieser Polemik geschrieben und die Lage der Verhältnisse in der zweiten Generation der Durkheim-Schüler vertieft.[fn:14] Diese Generation ist aus den Studierenden entstanden, die bei Durkheim und auch bei Mauss studiert haben. Davy hat bei Mauss an der /Ecole Pratiques des Hautes Etudes/ die Lehrveranstaltungen besucht, in denen Mauss um 1910 von religiösen Begriffen in alten Gesellschaften und darunter vom /potlatch/ spricht. In seiner Dissertation verwendet Davy den /potlatch/, um die Gabenleistungen zwischen Familien in alten Gesellschaften und bei den Einheimischen Nordamerikas zu benennen. Er zeigt, dass solche /potlatch/ nicht nur im Kontext von ritualen Wettbewerben zwischen Klans oder von Festen auftauchen, sondern auch in Bezug auf die Verwandschaft und die Bindung von Allianzen zwischen Familien, die sie strukturieren. Aus dem potlatch entstehen die ersten Formen von durch Gaben formalisierten Allianzen und ferner die Grundlage des Rechtes.

Diese Schlußfolgerung überrascht Mauss, der Davy schreibt: "Sie sind meiner Unterscheidung zwischen Gesellschaften mit umfassenden Verträgen (Phratrie zu Phratrie; Klan zu Klan, die einfach gegeneinander stehen) und solchen mit umfassenden Verträgen agonistischer Art -- oder Potlatch -- nicht gefolgt. Sie verwechseln Gattung und Art. Ihre Überlegungen zur Ehe sind richtig und passen zur Gattung; es ist sinnlos und gefährlich, den Anschein zu erwecken, sie auf den Potlatch, die Art, zu beschränken".[fn:15] Weiter erwähnt Mauss, dass Davy behauptet, die Gesellschaften, die den /potlatch/ praktisieren, wie etwa die von Boas beobachteten Kwakiutl, arm seien. Aber nach Mauss "ist der Potlatch nur in relativ reichen Gesellschaften möglich".[fn:16] Nichtsdestotrotz bleibt Mauss tröstend, und er versichert Davy, dass all dies "zwischen uns" bleibt, "bis ich Gelegenheit habe, öffentlich zu sagen, wie sehr mir Ihr Buch gefällt".[fn:17] Diese Gelegenheit stellt sich nicht alsbald vor, denn Mauss, der als Mitglied der Promotionskommission zur Dissertation Davys fungieren muss, kann nicht kommen. In seinem Brief an Hubert schreibt er: "ich wollte mein Abendessen beschleunigen, ich habe meinen alten Feldkocher angezündet und dabei es geschafft, mich dummerweise die Hälfte meines linken Fußes zu verbrühen. (...) In einem Sinne kommt mir dieser kleine Unfall ganz gelegen. Der hat mir erlaubt, an der Dissertation von Davy nicht teilzunehmen".[fn:18] Auf Bitte von Mauss ersetzt ihn Marcel Granet in der Promotionskommission, der Davy gut kennt, weil sie zusammen an der /Ecole Normale Supérieure/ studiert haben und Stipendiaten der Stiftung Thiers gewesen sind. Beide haben ebenfalls die Lehrveranstaltungen von Mauss besucht, die sie stark beeindruckt haben. Die Verteidigung wird mit der Benotung /très honorable/ (Magna Cum Laude) am 01.04.1922 scheinbar ohne bemerkenswerte Auffälligkeit abgeschlossen. Aber im Dezember 1922 erscheint eine Besprechung von Granet zu den letzten Arbeiten der Mitglieder der Durkheim-Schule und darunter zur Dissertation Davys. In diesem Zusammenhang wiederholt Granet nicht nur die Kritiken, die Mauss in seinem Brief erwähnt hat, sondern Granet betont auch, dass Davy nicht genug erwähnt, von wem er sein Material und seinen Ansatz zur Verbindung des /potlatch/ und des Rechtes zieht. Er legt nah, dass sich Davy bei Mauss bedient und ihm die Vorherrschaft in diesem Feld der Forschung entsprechend geraubt habe. Dass diese Kritik von einem engen Bekannten Davys kommt und Davy in dreister Art bloß stellt, erschüttert Davy. Er schreibt Granet einen Brief, in dem er bereut, dass Granet Unterstellungen in der akademischen Öffentlichkeit verbreitet, "die selbstverständlich dazu tendieren, meine Arbeit zu diskreditieren. (...) ich habe verkündet, all was ich Mauss schulde".[fn:19] Diese Polemik wird verlängert durch eine andere Besprechung von Raymond Lenoir zwei Jahre später in der /Revue philosophique/, der die Kritiken von Granet wieder aufnimmt und seine Unterstellungen unterstreicht, nach denen Davy Mauss mehr oder weniger ausgeraubt habe. Besnard sagt, dass Mauss diese Meinung geteilt habe.[fn:20] Nichtsdestotrotz muss festgestellt werden, dass Mauss in seinen Schriften keine Kritik zu Davy äußert, sondern wie in /Gift, Gift/ die Arbeit von Davy zitiert und später im Essay /Die Gabe/ sogar sagt, dass "Die vorliegende Arbeit Teil einer Reihe von Forschungen [ist], die Herr Davy und ich zu den archaischen Formen des Vertrags seit langem entwickeln", als ob er Davy zu seiner Forschung assoziieren würde.

Im Rahmen einer schrumpfenden Gruppe nach dem Tod von Durkheim und von vielen Mitarbeitern um Durkheim und Mauss im Krieg und in einer Zeit, in der viele der Kollegen und Studenten von Mauss ihm sagen, dass die Arbeit, die in /L'Année sociologique/ investiert wurde, wieder aufgenommen werden sollte, ist es denkbar, dass Mauss nicht zur Zersplitterung der Durkheim-Schule beitragen wollte. Vielleicht haben wir hier ein Grund, weshalb Mauss statt diese Polemik weiter zu füttern Davy so vorstellt, als ob er mit ihm eng an der Forschung zu Gabenphänomenen gearbeitet habe. Dabei versteht man insbesondere, dass Mauss die Verbindung zwischen den neuen Mitgliedern der Durkheim-Schule wichtig ist, davon zudem nicht wenige wie er im französischen Sozialismus engagiert sind. Dies trifft einen inhaltlichen Punkt, der in /Gift, Gift/ hervorgehoben wird: Durch die Entwicklung von Allianzen zwischen Menschen und Kollektiven anhand von Gabenpraktiken gewinnen diese Menschen einen besseren Umgang mit dem, was verboten ist, und dem, was erlaubt ist, als ob diese Gabenpraktiken den Verbotenen und den Erlaubten verdeutlichen würden. In diesem Zusammenhang spielen die Gegenstände, die ausgetauscht werden, eine wichtige Rolle für diese Verdeutlichung des Verbotenen und des Erlaubten, weil sie die Macht von den Akteuren bewahren und verwirklichen, die einen Gegenstand geben, über die Akteure, die diesen Gegenstand empfangen. Damit werden die Grenzen zwischen dem Verbotenen und dem Erlaubten innerhalb des asymmetrischen Verhältnisses gesetzt, die den Umgang mit Tabous und mit der religiösen Polaritäten Sakralen und Profanen regeln. Diese Grenzeziehung und die entsprechende Umverteilung der Akteure im Gabentausch, die von gleichwertigen zu ungleichwertigen Akteuren werden, sieht Mauss besonders in den germanischen und skandinavischen Bräuchen vorhanden. Dabei fokussiert er insbesondere den Austausch von Getränken, die als stark ambivalent wahrgenommen werden. Es können Geschenk- oder Gift-Getränke sein je nachdem, wie, wann, wo und mit wem sie getrunken werden. Um alkoholische Getränke wie das Bier in germanischen Gesellschaften werden, wie es Mauss in einer späteren Notiz zum Buch Georges Dumézil im Bereich der vergleichenden Untersuchungen von Mythologien präzisiert, /potlatch/ in der Form von /Bierpotlatch/ organisiert, um sich kollektiv vom Tod zu schützen.[fn:21] Weil alkoholische Getränke Produkte der Gärung sind, werden sie mit den magischen Praktiken und mit den Magiern assoziiert, die solche Getränke vorbereiten[fn:22] -- daher auch die Wahrnehmung von solchen Getränken als besonders ambivalenten Getränken bzw. als möglichen Zaubertränken, die sowohl eilen und stärken als auch vergiften und töten können. Durch das gegenseitigen Schenken von alkoholischen Getränken wie dem Bier hält man den Austauschpartner in seiner Macht. Das Schenken des Getränkes setzt ihn in einem asymmetrischen Verhältnis zwischen Vertrauen und Misstrauen, daraus er ausgehen kann, wenn er seinen Mut zeigt und dabei seine Zuverlässigkeit als Austauschpartner bestätigt, was in diesem Zusammenhang bedeutet, es zu wagen, das Getränke zu trinken.

Die Getränke illustrieren beispielhaft diese Eigenschaft der Macht des Gebers über den Empfänger der Gabe. Diese Macht ist nicht auf bestimmte Kategorien von Gegenständen eingeschränkt, sondern er wird zu all den Gegenständen kommuniziert werden, die im Gabentausch ausgetauscht werden. In /Gift, Gift/ taucht diese wichtige Auffassung Mauss', dass der Gabentausch alle Gegenstände sowie alle Menschen einbeziehen kann, die dann in der ganzen Gesellschaft von Klan zu Klan, Familien zu Familien zirkulieren, und diese Gesellschaft selbst in Zirkulationen zu anderen Gesellschaften bringen -- dies sieht man besonders gut beim Verwendung des Begriffes "Kreislauf" am Anfang des Textes und bei der expliziten Erwähnung des Begriffes der Zirkulation in der Fußnote 9 zur Zirkulation der Frauen zwischen Familien. Durch eine solche Zirkulation werden alle Gegenstände der Gaben Machtbehälter von Gebern über Empfängern und aufgrund derselben Zirkulation die Gewährleistung, dass die Macht nicht als Besitz von bestimmten Gebern bleibt, sondern in der ganzen Gesellschaft zirkuliert und daher ständig (um)verteilt wird, wie Geber und Empfänger im Laufe dieser Zirkulation ihre Rolle wechseln. Dabei sammeln sich um die Gabenpraktiken immer mehr Gegenstände, die in die Zirkulation der Gaben aufgenommen werden, sei es, weil sie zu Gaben werden und als Gaben zirkulieren, sei es, weil sie die Zirkulation von Gaben begleiten. Dies gilt für den Pfand, den Mauss sowohl wie eine Gabe als auch wie einen Gegenstand betrachtet, der eine Gabe -- wie am Beispiel des Darlehens -- begleitet, der dann am Tag der Rückzahlung des Darlehens erwidert wird. Dies gilt ebenfalls für den Fehdehandschuhe wie etwa in einem Duell, der als persönlicher Gegenstand vom Geber zu den Füßen des Empfängers geworfen wird, um ihm zu signalisieren, dass er herausgefordert wird. Wenn der Empfänger diese Herausforderung akzeptiert und die Herausforderung stattgefunden hat, dann kommt der Fehdehandschuhe zurück zu seinem Besitzer bzw. ist ihm erwidert.

Sei es am Beispiel des Pfandes und der Fehdehandschuhe, zeigt Mauss, wie solche Gegenstände in der Unterstützung der gegenseitigen Gewährleistung des Verhältnisses zwischen Austauschpartnern in der Gabe kommen. Solche Formen der Gewährleistung findet man nicht nur in den Bräuchen von alten germanischen Gesellschaften, sondern auch in vielen anderen Gesellschaften auf der Erde und in der Zeit. Dieser letzte Aspekt von /Gift, Gift/ betrifft einen wichtigen Punkt im Mauss' Diskurs zur Gabe. Diese Formen von Leistungen werden in unseren zeitgenössischen Gesellschaften immer noch anwesend, was man an den Geschenken noch gut beobachten kann, die wir schenken und bekommen und in uns "Reiz" wie "Unannehmlichkeit" erwecken. In den letzten Zeilen von /Gift, Gift/ meldet Mauss schon das Thema an, dass er in den moralischen Schlussfolgerungen in /Die Gabe/ darstellen wird: Selbst in den modernen Vertragsformen unseres Rechtes, im komplexen globalen wirtschaftlichen Handel und im Allgemeinen in unseren zeitgenössischen Gesellschaften überlebt die Bedeutung der Gabe und reguliert wie eine latente reptilienartige Struktur unserer Austauschpraktiken immer noch unsere Handlung. Wir agieren, weil wir geben, und wir geben, weil wir uns den anderen und der Gesellschaft verpflichten, dabei den Unterschied zu den anderen und dieser Gesellschaft entwickeln, die unsere Singularität bestätigt.

* Footnotes
[fn:22] Vgl. [cite:@Mauss2012c 291].

[fn:21] Vgl. [cite:@Mauss1974b].
[fn:20] Ebd., 254.

[fn:19] Vgl. [cite:@Besnard1985 252].
[fn:18] Vgl. [cite:@Benthien2021 478-479, Brief 301 vom 26.03.1922].

[fn:17] Ebd.
[fn:16] Ebd.

[fn:15] Ebd., 248.
[fn:14] Vgl. [cite:@Besnard1985].

[fn:13] Vgl. [cite:@Davy1922].
[fn:12] Vgl. [cite:@Mauss1921 36], der Boas unmittelbar als seine Quelle zum /potlatch/ erwähnt.

[fn:11] Vgl. [cite:@Mauss1926 109].
[fn:10] Vgl. [cite:@Paoletti2012b 354f.]. Dazu auch vgl. [cite:@Hertz2007 211], in dem Hertz vom /homo duplex/ spricht.

[fn:9] Vgl. [cite:@Paoletti2012b 345].
[fn:8] Vgl. [cite:@Hertz2007].

[fn:7] Ebd., 496, Brief 408 vom 9.08.1923.
[fn:6] Ebd., 484, Brief 396 vom 31.07.1922.

[fn:5] Ebd., 495, Brief 407 vom 25.07.1923; ebd., 496, Brief 408 vom 9.08.1923.
[fn:4] Ebd., 454, Brief 366 vom 6.10.1920.

[fn:3] Ebd., 447, Brief 360 vom 19.10.1919.
[fn:2] Ebd., 449, Brief 362 vom 3.10.1919.

[fn:1] Vgl. [cite:@Benthien2021 444, Brief 358 vom 21.01.1919].

* Bibliographie

#+cite_export: csl /home/cpsoz/OrgCSL/chicago-author-date.csl
#+print_bibliography:
