#+Setupfile: /home/cpsoz/OrgTemplates/odt-de.org
#+bibliography: Mauss-Bib.bib
#+bibliography: MMOeuvres.bib
#+bibliography: ToenniesMauss-Bib.bib

* Kommentar :noexport:

Wann genau Mauss /Gift, Gift/ verfasst, kann nicht mit Sicherheit ermittelt werden. 1922 erscheint der Text in der Festschrift zu Charles Andler. Aber es bleibt fraglich, ob ihn Mauss speziell für diese Angelegenheit vorbereitet oder schon früher bzw. vor dem Krieg verfasst hat. Inhaltlich behandelt Mauss in /Gift, Gift/ Themen, die in enger Verbindung mit den Fragen stehen, die er in seiner jungen Karriere mit Hubert herausgearbeitet hat. Es geht um die magischen und religiösen Phänomenen verschiedener Gesellschaften und Kulturen auf den fünf Kontinenten mit besonderer Berücksichtigung der melanesischen Inseln im Pazifik, der einheimischen Stämmen Nordamerikas und der alten indoeuropäischen Gesellschaften. Es geht auch speziell um eine Vielfalt von Gabenpraktiken, die Mauss zumindest seit seinen Arbeiten zu den Opferriten und der Magie aus den Jahren 1899-1903 mit Durkheim und Hubert regelmäßig behandelt. Mit der Rückkehr zum Zivilleben und zur Forschung fragt sich Mauss im Dialog mit Hubert,[fn:1] ob ein solches Phänomen wie die Gabe nicht ein eigenes Werk verdiene, etwa im Rahmen einer neuen Betrachtung zur Magie, oder innerhalb der unvollendeten Abhandlung /Das Gebet/ vertieft werden sollte,[fn:2] die Mauss vor dem Ersten Weltkrieg als seine Dissertationsschrift anzufertigen beginnt. Aber der Weg zurück an die Arbeit ist steinig. Von Oktober 1921 bis August 1922 leidet Mauss unter einer Lungenerkrankung, die ihn erschöpft. Zudem warten nach seiner vollständigen Genesung seine wichtigeren Projekte auf ihn, die er unbedingt zum erfolgreichen Ende bringen möchte,[fn:3] nämlich sein geplantes Buch zum Thema der Nation und die Nachfolge von /L'Année sociologique/. Texte wie /Gift, Gift/, die dazwischen kommen, sind zwar auch nicht unwichtig, weil sie Mauss erlauben, seine Überlegungen zu Gabenpraktiken weiterzuentwickeln. Allerdings sollten sie ihn nicht zu lange aufhalten, weshalb sie eher kurz gehalten sind und unmittelbar zum Argument kommen, das Mauss vorschlägt. /Gift, Gift/ zeigt dies beispielhaft: Der Text ist kurz und dessen zentrale Botschaft schnell ermittelt: Gaben sind ambivalent, sie sind sowohl Geschenke als auch Giftstoffe. Am Ende von /Gift, Gift/ wird der Status von diesem Text bestätigt: Er soll eine Einführung in die Komplexität von Gaben und Gabenpraktiken liefern, die zu einem späteren Zeitpunkt -- nämlich im späteren Essay /Die Gabe/ (1925) -- weiter entwickelt werden.

/Gift, Gift/ fängt mit der Erwähnung der zwei Bedeutungen von Gift als Geschenk und Giftstoff an, wobei die Verbindung zwischen beiden Begriffen auf Deutsch, Englisch und Holländisch nicht eindeutig geklärt ist. Weil ihn die Literatur zum Begriff "Gift" nicht zufriedenstellt, schlägt Mauss eine Hypothese vor: Die Bedeutungen von "Geschenk" und "Giftstoff" wurden im Begriff "Gift" miteinander verbunden, um die Bedeutung von Gift als Giftstoff abzumildern bzw. um die Gefahr, die die Bedeutung von "Gift" als Giftstoff enthält, zu dämpfen und die Verwendung des Begriffes zu ermöglichen. In diesem Zusammenhang gibt es eine unmittelbare Verbindung zu den Arbeiten von Mauss' Student und Freund Robert Hertz (1881-1915) insbesondere in Bezug auf die religiöse Polarität und die Sühne in den alten Gesellschaften.[fn:4] Hertz ist nicht nur der Kamerad im Rahmen des politischen Engagements im Sozialismus an der Seite von Mauss. Er ist auch derjenige, von dem Mauss wie Durkheim dachten, er würde die Zukunft der Durkheim-Schule darstellen.[fn:5] Diese Auffassung aufseiten Mauss' und Durkheims unterstützt Hertz insbesondere mit seiner Studie zur Vorherrschaft der rechten Hand, in der er Durkheims These zur Dualität im Menschen neue Dimensionen gibt. Nach Durkheim ist der Mensch ein /homo duplex/ in dem Sinne, dass er zwei Bewusstseinzustände einverleibt.[fn:6] Der erste Bewusstseinzustand führt zur Entwicklung einer individuellen Persönlichkeit und der zweite Bewusstseinszustand zur Entwicklung eines sozialen Bewusstseins. Nach Durkheim setzt diese Dualität im Menschen die grundsätzlichere Dualität zwischen dem Sakralen und dem Profanen voraus: Die zwei unterschiedlichen Bewusstseinszustände sind aus dieser grundsätzlichen Unterscheidung zwischen dem Sakralen und dem Profanen entstanden. Hertz verallgemeinert diese These Durkheims insofern, als er die innerliche Dualität im Menschen auf die Ebene einer Dualität zwischen Natur und Gesellschaft hebt. Einerseits gibt es profane Gegenstände, die gleichzeitig symbolisch mit dem Bösen, dem Schlechten, dem Unreinen assoziiert werden und allesamt Merkmale bilden, die mit der linken Hand verbunden sind. Andererseits gibt es das Gegenteil bzw. das Sakrale, das gleichzeitig das Gute, das Reine, das Richtige symbolisiert und mit der rechten Hand assimiliert wird. Diese Dualität innerhalb vom Menschen spiegelt sich außerhalb von ihm in der Form von Klassifikationssystemen wider, die auf die alltäglichen Gegenstände sowie in der Aufteilung des Raumes und der Zeit, der sozialen Rollen und Berufen, in der Hierarchisierung der Götter, der Teilung der Geschlechter und der Generationen verwendet werden. Wie Mauss in /Gift, Gift/ sagt, ruht die Vielfalt der Gaben auf einem breiten Spektrum an Bedeutungen zwischen dem Sakralen und dem Profanen, wovon sie jeweils einen Aspekt des asymmetrischen Verhältnisses zwischen diesen Polaritäten bezeichnen, weil Gaben immer an diese untrennbare Unterscheidung zwischen dem "Geschenk" und dem "Giftstoff" verweisen, die wiederum die untrennbare Beziehung zwischen dem Sakralen und dem Profanen im Alltag der Austauschpraktiken in den Gesellschaften der Gabe übersetzt. Zusammen betrachtet, bilden diese Gaben eine Totalität von Dienstleistungen, die an die Totalität der Gesellschaft erinnert, die unmittelbar oder mittelbar an solchen Dienstleistungen teilnimmt.

Deshalb spricht Mauss in /Gift, Gift/ von der Gabe als System der totalen Leistungen bzw. der juristischen, politischen, ökonomischen und religiösen Leistungen. Mit dem Begriff der Leistung verdeutlicht er das rechtliche Merkmal der Gaben: Gaben werden als Folge der Schließung von einem Vertrag getätigt. Mit dem Attribut "total" sagt Mauss, dass diese Leistungen alles betreffen, was in Unterstützung von Dritten getan werden kann. In einem späteren Text erklärt Mauss: "eine Gruppe von Menschen, ob hierarchisch organisiert oder nicht, schuldet einer bestimmten Anzahl anderer Menschen, Verwandten oder Verbündeten, die einen symmetrischen Platz beziehen (übergeordnet oder gleichwertig oder untergeordnet oder unterschiedlich aufgrund des Geschlechts), eine ganze Reihe moralischer und materieller Leistungen (Dienste, Frauen, Männer, militärischer Hilfe, ritueller Speisen, Ehren, usw.), und sogar die ganze Reihe dessen, was ein Mensch für einen anderen tun kann. Im Allgemeinen werden diese totalen Leistungen von Klan zu Klan, von Altersklasse zu Altersklasse, von Generation zu Generation, von Verbündeten zu Verbündeten erbracht. (...) Im Allgemeinen erfolgen diese Leistungen innerhalb dieser Gruppen und von Gruppe zu Gruppe entsprechend dem Rang der einzelnen Personen".[fn:7] In /Gift, Gift/ wie in /Die Gabe/ spricht Mauss von einem "System" der totalen Leistungen, wobei er mit dem Begriff des "Systems" zwei Merkmale der Gaben unterstreicht: a) die Gaben bilden in den unterschiedlichen Gesellschaften eine Einheit von sozialen Leistungen, die mehr oder weniger homogen sind und sich von anderen gesellschaftlichen Praktiken unterscheiden; b) diese Einheit entsteht aus der (unmittelbaren oder mittelbaren) Integration aller Menschen einer sozialen Gruppe bzw. einer Gesellschaft in die Gabenpraktiken. Mit dem ersten Merkmal sagt Mauss, dass Gabenpraktiken in der Gesellschaft nicht ständig stattfinden, sondern es gibt Bedingungen, die erfüllt werden müssen, damit Gabenpraktiken entwickelt werden. Diese Bedingungen spiegeln sich in der Vielfalt der Namen von Gaben wider, die geleistet werden, und sie verorten diese Gaben in der Vielfalt der Praktiken in einer Gesellschaft. Etwa die Mitgift, die Mauss in /Gift, Gift/ erwähnt, bezeichnet im Allgemeinen das Heiratsgut der Braut an die Familie des Bräutigames, das in der Hochzeitzeremonie mitgegeben wird. Die Morgengabe ist eine nähere Bezeichnung der Mitgift als das Heiratsgut der Braut, das am Morgen vor der Hochzeitzeremonie geleistet wird. Mit diesem zweiten Merkmal verdeutlicht Mauss, dass die Gabenpraktiken eine Wirkung auf den Zusammenhalt der Gesellschaft haben, den sie stärken. Weil die Gabenpraktiken alle Menschen in einer Gesellschaft direkt oder indirekt einbeziehen, tragen sie entsprechend zur engeren gesellschaftlichen Kohäsion mit der Wirkung bei, dass die Akteure in dieser Gesellschaft ihre Gesellschaft als Einheit aus der Praxis der Gaben besser wahrnehmen und sich diese Einheit besser vorstellen können. Hier findet man nochmal die Verbindung mit der grundsätzlichen Unterscheidung zwischen dem Sakralen und dem Profanen wieder, die das gesellschaftliche Leben strukturieren: Anhand von Gaben geben sich die Menschen die Möglichkeit zu wissen, wo sie sich als gesellschaftliche Einheit in diesem Verhältnis zwischen dem Sakralen und dem Profanen befinden und um Korrekturmechanismen zu verwenden, wenn dieses Verhältnis drohen würde, gestört bzw. geschwächt zu werden. Einer dieser Korrekturmechanismen ist der /potlatch/.

Mauss wird von dem /potlatch/ in /Die Gabe/ ausführlich reden, und in /Gift, Gift/ liefert er eine Zusammenfassung der wesentlichen Merkmale vom dieser Form von Gaben, die er als "agonistische[n] totale[n] Leistungen" bezeichnet. Solche Leistungen werden im Rahmen von Gabenpraktiken getätigt, die alle ein Element der Herausforderung enthalten. Eine Herausforderung kann entweder nur eine Partei des Gabentausches betreffen, die ihren Wert als guter Partner im Gabenaustausch belegen muss, oder sie kann beide Parteien betreffen, die sich gegenseitig als gleichwertig im Rahmen von Ehrenkämpfen zeigen müssen. Sie kann aber auch die ganze Gesellschaft betreffen, die ihre Stärke als Kollektiv belegen muss. Nicht nur die Rivalität und die Revanche stehen auf dem Spiel, die eine Konkurrenz zwischen den Parteien im Gabentausch um die beste Leistung, die sie bringen müssen, unterstützen, sondern auch die Formen der Zerstörung von Vermögen als Korrektur von gesellschaftlichen Asymmetrien. Bei Gabenpraktiken in der Form von agonistischen Leistungen geht es also nicht ausschließlich nur darum, dass man sich als Herrscher und Gewinner im Tausch zeigt. Vielmehr geht es ebenso darum, dass man viel Leid und Verlust mit Leichtigkeit und Ausdauerkraft ertragen kann. In beiden Fällen von Gewinnen und Verlusten zeigen die Menschen und Kollektive nicht nur ihre Durchsetzungskraft im Umgang mit Herausforderungen, die ihnen von ihren Austauschpartnern gestellt werden. Sie belegen zudem ihre Zuverlässigkeit als diese Austauschpartner, mit denen im nächsten Gabenaustauschen gerechnet werden kann, um die Komplexität der Gabenpraktiken und die Gefahren, die mit Gaben einhergehen können, zu beherrschen. Im Kontext dieser Einordnung des /potlatch/ in die Gabenpraktiken ist es für Mauss nach wie vor wichtig zu präzisieren, dass diese Praktiken nicht nur bei den einheimischen Stämmen Nordamerikas zu finden sind, wie Franz Boas in seinem Buch über die Kwakiutl berichtet hat,[fn:8] sondern auch auf den melanischen Inseln sowie bei den Kelten und den Germanen. Mit diesem Argument geht es bei Mauss darum nahezulegen, dass die Gabenpraktiken vielleicht überall in den unterschiedlichen Gesellschaften der Welt entwickelt worden sind. Besonders wichtig ist hier ebenfalls die Aussage, dass solche Formen von antagonistischen Gabepraktiken bei den Kelten nicht nur festzustellen sind, sondern obendrein ihre Spuren im alten keltischen Recht hinterlassen haben. In diesem Zusammenhang geht es Mauss nicht darum, an das Organisationsprinzip der soziologischen Untersuchung zu erinnern, die die Besonderheit der Arbeiten der französischen Soziologieschule ausgemacht hat: Unsere Gesellschaften nicht nur mit alten Gesellschaften in der Geschichte zu vergleichen, sondern auch mit Gesellschaften aus anderen Kulturen in der ganzen Welt. Es geht auch ganz konkrete um Korrekturen und Einordnungen von Dissonanzen, die Mauss in der Zeit der Veröffentlichung von /Gift, Gift/ überrascht haben, weil sie aus dem eignen Stall kommen und in einer Polemik um die Dissertation von Georges Davy kristallin werden.[fn:9] Philippe Besnard hat damals einen berühmten Aufsatz zu dieser Polemik geschrieben und die Lage der Verhältnisse in der zweiten Generation der Durkheim-Schüler vertieft.[fn:10] Diese Generation ist aus den Studierenden entstanden, die bei Durkheim und auch bei Mauss studiert haben. Davy hat bei Mauss an der /Ecole Pratiques des Hautes Etudes/ die Lehrveranstaltungen besucht, in denen Mauss um 1910 von religiösen Begriffen in alten Gesellschaften und darunter vom /potlatch/ spricht. In seiner Dissertation verwendet Davy den /potlatch/, um die Gabenleistungen zwischen Familien in alten Gesellschaften und bei den Einheimischen Nordamerikas zu benennen. Er zeigt, dass solche /potlatch/ nicht nur im Kontext von ritualen Wettbewerben zwischen Klans oder von Festen auftauchen, sondern auch in Bezug auf die Verwandschaft und die Bindung von Allianzen zwischen Familien, die sie strukturieren. Aus dem potlatch entstehen die ersten Formen von durch Gaben formalisierten Allianzen und ferner die Grundlage des Rechts.

Diese Schlußfolgerung überrascht Mauss, der Davy schreibt: "Sie sind meiner Unterscheidung zwischen Gesellschaften mit umfassenden Verträgen (Phratrie zu Phratrie; Klan zu Klan, die einfach gegeneinander stehen) und solchen mit umfassenden Verträgen agonistischer Art -- oder Potlatch -- nicht gefolgt. Sie verwechseln Gattung und Art. Ihre Überlegungen zur Ehe sind richtig und passen zur Gattung; es ist sinnlos und gefährlich, den Anschein zu erwecken, sie auf den Potlatch, die Art, zu beschränken".[fn:11] Weiter erwähnt Mauss, dass Davy behauptet, die Gesellschaften, die den /potlatch/ praktisieren, wie etwa die von Boas beobachteten Kwakiutl, arm seien. Aber nach Mauss "ist der Potlatch nur in relativ reichen Gesellschaften möglich".[fn:12] Nichtsdestotrotz bleibt Mauss versöhnlich, und er versichert Davy, dass all dies "zwischen uns" bleibt, "bis ich Gelegenheit habe, öffentlich zu sagen, wie sehr mir Ihr Buch gefällt".[fn:13] Diese Gelegenheit stellt sich nicht alsbald ein, denn Mauss, der als Mitglied der Promotionskommission zur Dissertation Davys fungieren muss, kann nicht kommen. In seinem Brief an Hubert schreibt er: "ich wollte mein Abendessen beschleunigen, ich habe meinen alten Feldkocher angezündet und es dabei geschafft, mir dummerweise die Hälfte meines linken Fußes zu verbrühen. (...) In einem Sinne kommt mir dieser kleine Unfall ganz gelegen. Der hat mir erlaubt, an der Disputation von Davy nicht teilzunehmen".[fn:14] Auf Bitte von Mauss ersetzt ihn Marcel Granet in der Promotionskommission, der Davy gut kennt, weil sie zusammen an der /Ecole Normale Supérieure/ studiert haben und Stipendiaten der Stiftung Thiers gewesen sind. Beide haben ebenfalls die Lehrveranstaltungen von Mauss besucht, die sie stark beeindruckt haben. Die Verteidigung wird mit der Benotung /très honorable/ (Magna Cum Laude) am 01.04.1922 scheinbar ohne bemerkenswerte Auffälligkeit abgeschlossen. Aber im Dezember 1922 erscheint eine Besprechung von Granet zu den letzten Arbeiten der Mitglieder der Durkheim-Schule und darunter zur Dissertation Davys. In diesem Zusammenhang wiederholt Granet nicht nur die Kritiken, die Mauss in seinem Brief erwähnt hat, sondern er betont auch, dass Davy nicht ausreichend kenntlich macht, auf welches Material und auf welchen Ansatz er sich hinsichtlich der Verbindung des /potlatch/ und des Rechtes bezieht. Er legt nahe, dass sich Davy bei Mauss bedient und ihm die Vorherrschaft in diesem Feld der Forschung entsprechend geraubt habe. Dass diese Kritik von einem engen Bekannten Davys kommt und Davy in dreister Art bloßstellt, erschüttert Davy. Er schreibt Granet einen Brief, in dem er bereut, dass Granet Unterstellungen in der akademischen Öffentlichkeit verbreitet, "die selbstverständlich dazu tendieren, meine Arbeit zu diskreditieren. (...) ich habe verkündet, was ich alles Mauss schulde".[fn:15] Diese Polemik wird verlängert durch eine andere Besprechung von Raymond Lenoir zwei Jahre später in der /Revue philosophique/, der die Kritiken von Granet wieder aufnimmt und seine Unterstellungen unterstreicht, nach denen Davy Mauss mehr oder weniger bestohlen habe. Besnard sagt, dass Mauss diese Meinung geteilt habe.[fn:16] Nichtsdestotrotz muss festgestellt werden, dass Mauss in seinen Schriften keine Kritik zu Davy äußert, sondern wie in /Gift, Gift/ die Arbeit von Davy zitiert und später im Essay /Die Gabe/ sogar sagt, dass "Die vorliegende Arbeit Teil einer Reihe von Forschungen [ist], die Herr Davy und ich zu den archaischen Formen des Vertrags seit langem entwickeln", als ob er Davy zu seiner Forschung assoziieren würde.

Im Rahmen einer schrumpfenden Gruppe nach dem Tod von Durkheim und von vielen Mitarbeitern um Durkheim und Mauss im Krieg und in einer Zeit, in der viele der Kollegen und Studenten von Mauss ihm sagen, dass die Arbeit, die in /L'Année sociologique/ investiert wurde, wieder aufgenommen werden sollte, ist es denkbar, dass Mauss nicht zur Zersplitterung der Durkheim-Schule beitragen wollte. Vielleicht haben wir hier einen Grund, weshalb Mauss, anstatt diese Polemik weiter zu füttern, Davy so vorstellt, als ob er mit ihm eng an der Forschung zu Gabenphänomenen gearbeitet habe. Vor diesem Hintergrund ist es nur verständlich, dass Mauss die Verbindung zwischen den neuen Mitgliedern der Durkheim-Schule wichtig ist, von denen zudem nicht wenige, ebenso wie er, im französischen Sozialismus engagiert waren. Dies trifft einen inhaltlichen Punkt, der in /Gift, Gift/ hervorgehoben wird: Durch die Entwicklung von Allianzen zwischen Menschen und Kollektiven anhand von Gabenpraktiken gewinnen diese Menschen einen besseren Umgang mit dem, was verboten ist, und dem, was erlaubt ist, als ob diese Gabenpraktiken das Verbotene und das Erlaubte verdeutlichen würden. Für diese Verdeutlichung des Verbotenen und des Erlaubten spielen die Gegenstände, die ausgetauscht werden, eine wichtige Rolle, weil sie die Macht einerseits von den Akteuren, die einen Gegenstand geben, und andererseits über die Akteure, die diesen Gegenstand empfangen, bewahren und verwirklichen. Damit werden die Grenzen zwischen dem Verbotenen und dem Erlaubten innerhalb des asymmetrischen Verhältnisses gesetzt, die wiederum den Umgang mit Tabus und mit den religiösen Polaritäten des Sakralen und des Profanen regeln. Diese Grenzziehung und die entsprechende Umverteilung der Akteure im Gabentausch, die von gleichwertigen zu ungleichwertigen Akteuren werden, sieht Mauss besonders in den germanischen und skandinavischen Bräuchen vorhanden. Dabei fokussiert er insbesondere den Austausch von Getränken, die als stark ambivalent wahrgenommen werden. Es können Geschenk- oder Gift-Getränke sein je nachdem, wie, wann, wo und mit wem sie getrunken werden. Um alkoholische Getränke wie das Bier in germanischen Gesellschaften werden, wie es Mauss in einer späteren Notiz zum Buch von Georges Dumézil im Bereich der vergleichenden Untersuchungen von Mythologien präzisiert, /potlatch/ in der Form von /Bierpotlatch/ organisiert, um sich kollektiv vor dem Tode zu schützen.[fn:17] Weil alkoholische Getränke Produkte der Gärung sind, werden sie mit den magischen Praktiken und mit den Magiern assoziiert, die solche Getränke vorbereiten[fn:18] -- daher auch die Wahrnehmung von solchen Getränken als besonders ambivalente Getränke bzw. als mögliche Zaubertränke, die sowohl heilen und stärken als auch vergiften und töten können. Durch das gegenseitige Schenken von alkoholischen Getränken wie dem Bier hält man den Austauschpartner in seiner Macht. Das Schenken des Getränkes setzt ihn in ein asymmetrisches Verhältnis zwischen Vertrauen und Misstrauen, aus dem er herausgehen kann, wenn er seinen Mut zeigt und dabei seine Zuverlässigkeit als Austauschpartner bestätigt, was in diesem Zusammenhang bedeutet, es zu wagen, das Getränk zu trinken.

Die Getränke illustrieren beispielhaft diese Eigenschaft der Macht des Gebers über den Empfänger der Gabe. Diese Macht ist nicht auf bestimmte Kategorien von Gegenständen eingeschränkt, sondern sie wird zu all den Gegenständen kommuniziert, die im Gabentausch ausgetauscht werden. In /Gift, Gift/ taucht diese wichtige Auffassung Mauss', dass der Gabentausch alle Gegenstände sowie alle Menschen einbeziehen kann, die dann in der ganzen Gesellschaft von Klan zu Klan, von Familien zu Familien zirkulieren, und diese Gesellschaft selbst in Zirkulationen zu anderen Gesellschaften bringen, auf -- dies sieht man besonders gut bei der Verwendung des Begriffes "Kreislauf" am Anfang des Textes und bei der expliziten Erwähnung des Begriffes der Zirkulation in der Fußnote 9 zur Zirkulation der Frauen zwischen Familien. Durch eine solche Zirkulation werden alle Gegenstände der Gaben Machtbehälter von Gebern über Empfänger und aufgrund derselben Zirkulation zur Gewährleistung, dass die Macht nicht im Besitz von bestimmten Gebern bleibt, sondern in der ganzen Gesellschaft zirkuliert und daher ständig (um)verteilt wird, wie Geber und Empfänger im Laufe dieser Zirkulation ihre Rolle wechseln. Dabei sammeln sich um die Gabepraktiken immer mehr Gegenstände, die in die Zirkulation der Gaben aufgenommen werden, sei es, weil sie zu Gaben werden und als Gaben zirkulieren, sei es, weil sie die Zirkulation von Gaben begleiten. Dies gilt für den Pfand, den Mauss sowohl als Gabe als auch als Gegenstand behandelt, der eine Gabe -- wie am Beispiel des Darlehens -- begleitet, der am Tag der Rückzahlung des Darlehens erwidert wird. Dies gilt ebenfalls für den Fehdehandschuh wie etwa in einem Duell, der als persönlicher Gegenstand vom Geber zu den Füßen des Empfängers geworfen wird, um ihm zu signalisieren, dass er herausgefordert wird. Wenn der Empfänger diese Herausforderung akzeptiert und die Herausforderung stattgefunden hat, dann kommt der Fehdehandschuh zurück zu seinem Besitzer bzw. ist ihm erwidert.

Sei es am Beispiel des Pfandes und des Fehdehandschuhs, Mauss zeigt, wie solche Gegenstände in der Unterstützung der gegenseitigen Gewährleistung des Verhältnisses zwischen Austauschpartnern in der Gabe kommen. Solche Formen der Gewährleistung findet man nicht nur in den Bräuchen von alten germanischen Gesellschaften, sondern auch in vielen anderen Gesellschaften auf der Erde und in der Zeit. Dieser letzte Aspekt von /Gift, Gift/ betrifft einen wichtigen Punkt in Mauss' Diskurs zur Gabe. Diese Formen von Leistungen sind in unseren zeitgenössischen Gesellschaften immer noch anwesend, was man an den Geschenken noch gut beobachten kann, die wir schenken und bekommen und in uns "Reiz" wie "Unannehmlichkeit" erwecken. In den letzten Zeilen von /Gift, Gift/ meldet Mauss schon das Thema an, dass er in den moralischen Schlussfolgerungen in /Die Gabe/ darstellen wird: Selbst in den modernen Vertragsformen unseres Rechtes, im komplexen globalen wirtschaftlichen Handel und im Allgemeinen in unseren zeitgenössischen Gesellschaften überlebt die Bedeutung der Gabe und reguliert wie eine latente reptilienartige Struktur unserer Austauschpraktiken immer noch unsere Handlung. Wir agieren, weil wir geben, und wir geben, weil wir uns den anderen und der Gesellschaft verpflichten, und weil wir dabei den Unterschied zu den anderen und dieser Gesellschaft entwickeln, die unsere Singularität bestätigt.

* Nachwort

Als Marcel Mauss im Januar 1919 aus dem Kriegsdienst entlasen wird,[fn:19] fängt eine Zeit der schwierigen Rückkehr zum zivilen und akademischen Leben an, oder wie Mauss in einem Brief an seinen "'Arbeitszwilling'" Henri Hubert[fn:20] mitteilt: "Ich bin gerade dabei, mich neu einzurichten, was nicht einfach ist. (...) Es muss mit einer relativ langen Rückkehr zur Barbarei gerechnet werden".[fn:21] Der Erste Weltkrieg ist beendet. Die Lust auf die Wiederaufnahme der wissenschaftlichen Arbeit ist vorhanden, und die Erwartungen sind groß. Schon im September 1919 fragen ihn die ehemaligen Kollegen,[fn:22] ob es nicht gut wäre, die Arbeit an /L'Année sociologique/ -- der Zeitschrift für Soziologie der Mitarbeiter um Emile Durkheim, der Onkel, und Marcel Mauss, der Neffe, die nach 1912 nicht mehr veröffentlicht wurde --, wieder aufzunehmen. Und die alten sozialistischen Kameraden der Genossenschaftsbewegung dürfen ebenso nicht vergessen werden, wie die persönlichen Projekte, die in dieser Zeit vielleicht mehr als vor dem Krieg an erneuter Bedeutung gewonnen haben -- darunter insbesondere das Buchprojekt zum Thema der Nation, dessen schon halb abgeschlossenen Plan mit fortgeschrittenen Textteilen Mauss mit einem kaum zu haltendem Enthusiasmus Henri vorstellt.[fn:23] Es gibt sehr viel zu tun, um den Anschluss an die Ideen vor 1914 wiederzufinden, viele Leute zu treffen, andere zu würdigen, die ihr Leben auf dem Schlachtfeld verloren haben. Darunter zählt man viele ehemaligen Studenten und Freunde von Mauss, die für /L'Année/ gearbeitet oder mit Mauss in der Unterstützung des Sozialismus in Frankreich gewirkt haben. Von diesem Übergang aus den Trümmern des Krieges ins neue freie Leben zeugt Mauss' /Gift, Gift/. Formal gleicht dieser Text einer Arbeitsnotiz, aber im Intertext von /Gift, Gift/ gibt es sehr viele Verbindungen sowohl mit der Vergangenheit dessen, was das Projekt von Durkheim und Mauss war, als auch was dieses Projekt in der Zukunft unter der Leitung von Mauss werden sollte.[fn:24]

** Das kollektive Projekt der Gründung einer wissenschaftlichen Soziologie

Marcel Israël Mauss ist am 10. Mai 1872 in der Stadt Épinal im Departement Vosges (ehemals Lothringen) geboren. Nach erfolgreicher Abitur (1890) entscheidet er sich für ein Studium der Philosophie und vertieft seine Kenntnisse der Soziologie unter professioneller Begleitung seines Onkels Emile Durkheim. Da Durkheim in dieser Zeit an der Universität in Bordeaux lehrt, schlägt er Mauss vor, sein Studium in Bordeaux aufzunehmen. Dem Vorschlag seines Onkels folgend nimmt Mauss 1890 ein Studium der Philosophie an der Universität Bordeaux auf. Nach Abschluss seiner /licence/ im Fach Philosophie (1892) studiert Mauss weiterhin in Bordeaux und gleichzeitig auch an der Universität Sorbonne in Paris. In Bordeaux nimmt er an den Lehrveranstaltungen seines Onkels teil, den er als "'den sichersten und den angenehmsten aller Redner'" bezeichnet und der sehr schnell zu seinem Mentor wird.[fn:25] In diesen Studienjahren entwickelt Mauss eine tiefe Freundschaft zu zwei weiteren seiner Professoren, dem Soziologen Alfred Espinas und dem Philosophen Octave Hamelin. Bei Espinas, der sich nach seinem Werk /Des sociétés animales/ (1877) mehr und mehr der experimentellen Psychologie und der Frage der Technik widmet, entwickelt Mauss ein ausgeprägtes Interesse für die Biologie, die Evolutionstheorie und die Technik, was ihn davon überzeugt, dass sich die Soziologie nur dann zu einer vollständigen Wissenschaft entwickeln kann, wenn sie auf der experimentellen Psychologie aufbaut. Hamelin dagegen macht Mauss mit seinem Verständnis des Neokantianismus vertraut, den Mauss als eine wichtige Quelle der Erneuerung der Philosophie versteht und der seiner Ansicht nach auch von der Soziologie verwendet und weiter verbreitet werden sollte.

1895 schließt Mauss seine /aggrégation/ im Fach Philosophie ab, was ihm das Recht gewährt, Philosophie in Gymnasien und als Hochschullehrer an der Universität lehren zu dürfen. Aber Mauss weiss noch nicht, was er beruflich machen möchte. Durkheim nimmt ihn als Hilfskraft im Rahmen der Vorbereitung der Statistiken für sein Buch zum Selbstmord (1897) mit. Mauss arbeitet am /Service de la statistique judiciaire/ von Gabriel Tarde.[fn:26] Es ist eine Zeit des intensiven Austausches zwischen Durkheim und Mauss. Der Onkel bemerkt, dass Mauss Fragen der Religionwissenschaften interessiert, die Durkheim ebenfalls spannend findet und in Verbindung mit seiner Art der soziologischen Untersuchung bringen möchte. Deshalb rät er Mauss, die Lehrveranstaltungen zur Religionwissenschaften an der /École pratique des hautes études/ (EPHE) zu besuchen. Mauss gefallen diese Lehrveranstaltungen, und anschließend immatrikuliert er sich in zwei Sektion der EPHE bzw. in den historischen und philologischen Wissenschaften (IV. Sektion) und in der Religionswissenschaften (V. Sektion). An der EPHE trifft Mauss auf Professoren, die enge Freunde werden, wie etwa Léon Marillier und Antoine Meillet im Bereich der Psychologie, der Philologie und der Linguistik, und insbesondere Sylvain Lévi im Bereich der Judaistik und der Indologie,[fn:27] der für Mauss wie zum zweiten Onkel wird. In diesem Umfeld tauchen die ersten wissenschaftlichen Arbeiten von Mauss sowie die ersten Ideen zur Bildung von einem Kreis von gleichgesinnten Gelehrten und Studierenden auf. Sie würden an der Schnittstelle zwischen Philologie, Geschichte, Religionwissenschaften und Ethnologie eine neue Art der soziologischen Untersuchung entwickeln, deren Ergebnisse mit einem eigenen Medium veröffentlicht werden würden. Das Projekt der Zeitschrift /L'Année sociologique/ war auf dem Papier geboren, im Kern deren Mauss eine Schlüsselrolle als Koordinator spielen sollte,[fn:28] und die er später nach dem Tod von Durkheim leiten sollte.

Während Durkheim 1896 mit dem Verlag Alcan in Paris verhandelt, um zu ersuchen, ob Alcan sich vorstellen könnte, eine Zeitschrift für Soziologie in der Form von einer Zeitschrift mit dem Titel /L'Année sociologique/ zu veröffentlichen, arbeitet Mauss an seiner ersten wissenschaftlichen Produktion. Er schreibt eine Rezension zu Adolf Bastian und einen Aufsatz zu Sebald Rudolf Steinmetz für die von Réville und Marillier herausgegebenen Zeitschrift /Revue de l’histoire des religions/, die nicht nur Durkheim, sondern auch Tarde, bei dem Mauss zu dieser Zeit arbeitet, sehr gefallen.[fn:29] Nach erfolgreicher Verhandlung mit Alcan fängt die Arbeit an /L'Année sociologique/ an. Mauss leitet die Sektion der /Sociologie religieuse/, die die angesehenste Sektion der Zeitschrift bildet und den Kerngedanken der Durkheim’schen Soziologie unterstützt, wonach die Religion die Matrix der sozialen Tatsachen sei. 1897 stellt /L’Année/ weitere Mitarbeiter aus dem Umfeld der Gruppe ein (Paul Lapie, Emmanuel Lévi, Egard Milhaud, Henri Muffang und Dominique Parodi). Die Arbeit, die Mauss in diesem Zusammenhang leisten muss, verlangt sehr viel Zeit, die er aufgrund von seinen anderen Projekten im Rahmen seines politischen Engagements für die Arbeiterbewegung und mehr und mehr in Unterstützung von Jaurès und dem Sozialismus nicht immer hat. Entsprechend hat Mauss Schwierigkeiten, regelmäßig zur Arbeit zu erscheinen und seine Rezensionen rechtzeitig zu liefern, was Durkheim besonders verärgert. "'Das Übel ist ausweglos; wir haben es mit einem Unheilbaren zu tun'", teilt Durkheim Hubert mit und bezieht sich hierbei auf Mauss, der in seiner gesamten Zeit bei /L’Année/ keine Fristen einhält und manchmal wichtige Rezensionen vergisst, die Durkheim anschließend selbst schreiben muss.[fn:30]

Im Jahre 1898 erscheint das Buch /La Doctrine du sacrifice dans les Brāhmaṇas/ von Sylvain Lévi, das Mauss auf ein entscheidendes Phänomen aufmerksam macht: Opferriten werden ausgeübt, um die Akteure einer Gesellschaft mit der sakralen Welt der Götter in Kontakt treten zu lassen. Gemeinsam mit Hubert will Mauss diese Erkenntnis vertiefen. Von Durkheim übernehmen Mauss und Hubert die Idee der Zerstörung, die in den Opferriten ständig präsent ist, die eine konkrete soziale Funktion hat. Das, was im Opfer geopfert bzw. zerstört wird, dient der Kommunikation mit dem Sakralen und alles was sakral ist, betrifft die Gesellschaft unmittelbar wie mittelbar.[fn:31] Diese These ist der argumentative Gipfelpunkt des /Essays über die Natur und die Funktion des Opfers/ (/Essai sur la nature et la fonction du sacrifice/), den Mauss und Hubert im zweiten Band von /L’Année/ veröffentlichen. Dieser /Essay/ wird in Frankreich und im Ausland als Meisterstück gefeiert. Das Sakrale im Opfer wird als wesentliches Merkmal nicht nur des religiösen, sondern auch des sozialen Lebens verstanden. Zudem unterstützt diese Erkenntnis Durkheims Auffassung von Religion, die ein Mittel für die Akteure sei, sich die unpersönliche Kraft der Gesellschaft anzueignen. Mauss und Hubert grenzen sich jedoch auch bezüglich eines kleinen, aber wichtigen Details von Durkheims Ansatz ab.[fn:32] Zwar zeigt das Opfer, wie relevant die Gesellschaft für die Akteure ist. Allerdings ist das Individuum mindestens ebenso relevant für die Gesellschaft, was insbesondere daraus hervorgeht, dass das Opfer nicht blind, sondern nach Regeln verwendet und vollzogen wird, die unter anderem darauf abzielen, die Akteure vor der Bestimmungsmacht der Gesellschaft zu schützen.

** Das politische Engagement im Sozialismus

Die Zeit der Veröffentlichung des /Essays/ kennzeichnet eine Wende im Leben von Mauss, der ab 1900 Lehraufträge an der EPHE anbietet und ab 1901 im regelmäßigen Lehrbetrieb der Universität als Professor und Forscher tätig ist.[fn:33] Diese Wende betrifft ebenfalls Mauss' Engagement in die politischen Bewegungen seiner Zeit und insbesondere im Sozialismus. Mauss' Studienjahre waren gleichzeitig die Jahre seiner politischen Ausbildung. Über Durkheim hat Mauss den Sozialisten Jean Jaurès kennengelernt, der ihm sehr stark prägen wird.[fn:34]. Mauss gehört zu jenen Studierenden, die auf den Marxismus in seiner französischen Spiel- und Lesart aufmerksam werden. In Paris besucht er die entsprechenden Gruppen von politisierten Studierenden. In diesem Zusammenhang lernt er Marcel Cachin kennen, der ebenso ab 1890 in Bordeaux Philosophie studiert, bereits Mitglied der französischen Arbeiterpartei ist und Mauss davon überzeugt, ebenfalls Mitglied dieser Partei zu werden.[fn:35] Für Mauss ist das politische Engagement mindestens ebenso wichtig wie sein Engagement in der Wissenschaft. Es handelt sich dabei um ein ernsthaftes Engagement für die von vielen Bevölkerungsteilen Frankreichs geteilten Ideen des Sozialismus, die er bis zu seinem Lebensende unterstützen wird. In den Jahren 1893-1894 leitet Mauss die /Ligue démocratique des écoles/ und wird zum aktiven Mitglied der /Groupe des étudiants collectivistes/ in Paris, wo er viele anderen Studierenden kennenlernt, davon einige wie Edgar Milhaud, Abel Rey und Paul Fauconnet zu seinen Freunden gehören.[fn:36]

Mauss engagiert sich später in der von Lucien Herr um die /Société nouvelle de librairie et d’édition/ (1899) gegründeten /Groupe de l’unité socialiste/ und unterstützt die Initiativen dieser Gruppe, indem er beispielsweise Lehrveranstaltungen mit Emmanuel Lévy, Simiand und Fauconnet an der /École socialiste/ anbietet.[fn:37] Außerdem unterstützt er die Dreyfusards in der Dreyfus-Affäre. Mehr und mehr interessiert er sich auch für die Genossenschaften und insbesondere die Konsumgenossenschaften. Über die Intensität seines Engagements in diesen unterschiedlichen Bewegungen berichtet die Presse. Neben Spenden in Unterstützung von Arbeitergruppen, die streiken, um Verbesserung ihrer Arbeitsbedingungen zu fordern,[fn:38] organisiert Mauss verschiedene /causeries/ (Plaudereien), die wie kleine öffentlichen Konferenzen häufig mit musikalischer Begleitung und anschließendem Beisammensein konzipiert werden. Im Jahr 1899 bietet Mauss im Rahmen dieser /causeries/ eine Reihe von Vorträgen zur "Geschichte der Gewerkschaftsorganisation in England" in Paris, Hallé Str. 65 an.[fn:39] Er veröffentlicht den in den sozialistischen Milieus in Frankreich hoch gelobten Beitrag "L'action socialiste", in dem er für die Vereinheitlichung der unterschiedlichen sozialistischen Bewegungen in Frankreich plädiert.[fn:40] Ebenfalls schließt sich Mauss der /Fédération des Jeunesses Socialistes-Révolutionnaires Internationalistes/ und der /Coalition des Jeunesses Révolutionnaires/ mit dem Ziel an, beide Bewegungen miteinander zu verbinden und an einer entsprechenden gemeinsamen Satzung für eine neue gemeinsame /Fédération/ zu arbeiten.

Im Frühling 1900 gründet Mauss mit einigen Freunden die /Coopérative socialiste. Boulangerie socialiste de Paris/, die zur Gründung der /Coopérative socialiste/ als eine Produktions- und Konsumgenossenschaft am 05.03.1900 führt.[fn:41] Mauss gehört mit Xavier Guillemin, André Hamelin, dem Dr. Kasimir aus Belgien und mit Philippe Landrieu zum Kontrollorgan und zum Beirat dieser Genossenschaft. Die Propaganda-Arbeit für die Genossenschaft in der Öffentlichkeit koordinieren Jean Allemane und Jaurès. Der Verwalter der Genossenschaft ist Guillemin in der Zusammenarbeit mit Hamelin, der die /Boulangerie/ leitet. Am 17.05.1900 beschreibt Léon Gérault-Richard, wie die /Boulangerie/ entstanden ist. Er betont insbesondere die bedeutsame Rolle der belgischen Sozialisten um Hector Denis und den Dr. Kasimir, der als Mäzen in Unterstützung der Gründung der /Boulangerie/ einspringt und 100.000.- Franken ausgibt.[fn:42] In dieser Zeit ist es Mauss bewusst, dass die Genossenschaftsbewegung in Frankreich nicht nur innerhalb des Landes entwickelt werden muss. Sie muss ebenfalls mit Genossenschaften in anderen Ländern Europas verbunden werden, damit diese Entwicklung langfristig etabliert und erfolgreich durchgeführt werden kann. Zu diesem Zweck wird entschieden, einen internationalen Kongress in Paris am 07.07.1900 zu organisieren, davon Mauss der Überraschungsgast ist und über die internationalen Beziehungen zwischen Genossenschaften redet.[fn:43] In den Berichten zum Kongress wird die Rolle von Mauss an der internationalen Schnittstelle der Genossenschaftbewegung hervorgehoben. Mauss "glaubt, dass die Organisation landwirtschaftlicher Produktionsgenossenschaften international sein muss. Er stützt sich dabei auf das Beispiel des schottischen Wholesale und der großen englischen Molkereigenossenschaften".[fn:44] Mauss "schlägt nachdrücklich vor, internationale Beziehungen durch den Austausch von Publikationen, Handelsinformationen und Produkten aufzubauen. Auf diese Weise könnte man von gemeinsam abgeschlossenen Verträgen profitieren. Er fordert den Kongress auf, die Gründung einer internationalen Genossenschaftsbank sowie internationaler auf Gegenseitigkeit basierter Versicherungsvereine für Feuer-, Kranken- und Lebensversicherungen zu prüfen".[fn:45] Diese Vorschläge werden von Jaurès nachdrücklich unterstützt, der auf dem Konress sagt: "Es reicht nicht aus, dass die Genossenschaften sozialistisch werden; die Sozialisten müssen Genossenschafter werden, das heißt, die sozialistische Partei muss all ihre Mitglieder auffordern, Genossenschaften beizutreten!".[fn:46] Selbst wenn Charles Gide die Ideen von Jaurès und Mauss nicht vollständig teilt, solidarisiert er sich mit ihnen. Mit Jaurès und in der Folge von Mauss schlägt Gide vor, einen kollektiven Reservefonds zu organisieren, zu dem alle Genossenschafter beitragen würden. Damit könnte Geld gesammelt werden, um andere Genossenschafter und Arbeiter zu unterstützen, wenn sie z.B. streiken und deshalb nicht bezahlt werden würden, oder wenn sie ihre Arbeit verlieren würden.[fn:47] Dieser Reservefonds wäre auch einen ersten Schritt in der Reform der Bezahlung von Genossenschafter, die nicht mehr entlohnt werden würden, sondern, wie es sich Mauss und Jaurès wünschen, mit einem solchen Fonds bezahlt werden würden.[fn:48]

Jedoch lassen sie sich nicht alle Sozialisten von diesem Vorschlag begeistern. Eine Debatte zur Nützlichkeit und Notwendigkeit von einem solchen Reservefonds wird eröffnet. Der Vorschlag wird an vielen Stellen so korrigiert, dass er seine Substanz fast vollständig verliert.[fn:49] Mauss, Jaurès und Gide werden sich damit bewusst, dass die französischen Sozialisten die Genossenschaftsbewegung nicht unbedingt unterstützen wollen, und dass selbst innerhalb der französischen Genossenschaftsbewegung der Dissens spürbar ist. Es ist keine einheitliche Bewegung, sondern es gibt zumindest drei unterschiedlichen Tendenzen, die erkannt werden können. Einerseits gibt es die Genossenschafter wie Mauss, die das Modell der Konsumgenossenschaft in den Vordergrund der Genossenschaftsbewegung rücken. Diese Konsumgenossenschaften werden von allen Genossenschaftern geleitet, und sie sind im Bereich der Lieferung von Produkten an alle anderen Genossenschaften nach dem Modell der Wholesales tätig. Andererseits gibt es die Produktionsgenossenschaften, die im Unterschied zu Konsummgenossenschaften nicht nur Produkte liefern, sondern solche Produkte auch manchmal selbst herstellen. Die Produktionsgenossenschaften werden nicht von allen, sondern von einigen (manchmal von nur einem) Genossenschaftern geleitet, die das Geschäft der Genossenschaft bestimmen. In der Mitte gibt es Genossenschafter wie Gide, die vorschlagen, dass beide Formen der Genossenschaften in einem großen Verband integriert werden sollten. Mauss und Jaurès versuchen, die anderen Genossenschafter davon zu überzeugen, dass ein solcher Verband nur im Sinne von "einem nationalen und internationalen Verband" existieren kann, der nicht bei privaten Firmen auf dem Markt kauft, sondern lediglich nur bei anderen Genossenschaften im In- oder im Ausland.[fn:50] In den Jahren 1901 und 1902 bildet dieses Thema der Kern der Konferenzen und /causeries/ von Mauss,[fn:51] und der Lehrveranstaltungen an der /Ecole socialiste/[fn:52] wie an der Volksuniversität der /Union Mouffetard/ in Paris.[fn:53] Im Jahre 1903 verwirklicht Mauss im Kleinen seine Auffassung von Genossenschaftsverbänden. Mit Landrieu, Henri Jullien und die Mitglieder der /Bourse des coopératives socialistes/ verfasst er die erste Satzung zur Gründung einer /Fédération coopérative de la région parisienne/, die Mauss bei internationalen Ereignissen wie dem internationalen Kongress in Lüttich (1905) vertreten wird.[fn:54] In dieser Zeit zwischen 1902 und 1904 erreicht Mauss vieles nicht nur in Bezug auf seine politischen Ziele, sondern auch auf seine wissenschaftliche Arbeit.

** Die soziale Realität als totale soziale Tatsache

1900 hatte Mauss mit Paul Fauconnet und der Unterstützung von Durkheim den Eintrag "Sociologie" in der /Grande Encyclopédie/ verfasst,[fn:55] der wie ein Manifest für eine wissenschaftliche Soziologie auf der Grundlage der Regeln der soziologischen Methode Durkheims wirkt. Diese zu entwickelnde wissenschaftliche Soziologie erfordere sehr genaue Untersuchungen von allzu alltäglich anmutenden gewöhnlichen Gegenständen in Zusammenarbeit mit anderen Disziplinen der Geistes- und Sozialwissenschaft, insbesondere aber der Geschichte, der Ethnographie, den Sprachwissenschaften und der Psychologie. Eine solche interdisziplinäre Herangehensweise ermöglicht es, die zu untersuchenden Tatsachen so vollständig als irgend möglich zu beschreiben, dass ihr tatsächliches Dasein und ihre Bedeutsamkeit als allumfassende gesellschaftliche Ganzheit, d. h. als "'totale' gesellschaftliche Tatsache[n]",[fn:56] offen zutage tritt. Mauss' Idee der totalen sozialen Tatsachen beruht auf einem komplexen soziologischen Forschungsprogramm, das nicht zuletzt mit anderen Disziplinen in Dialog treten soll, um die zu untersuchenden sozialen Tatsachen in ihrer ganzheitlichen Verbindung mit dem gesellschaftlichen Zusammenleben zu erklären. Diese Verbindung entwickeln Mauss und Durkheim im Essay /Über einige primitive Formen der Klassifikation/ (/De quelques formes primitives de classification)/, der 1903 in /L’Année/ veröffentlicht wird. Für diesen Beitrag sammelt Mauss umfangreiche ethnographische Daten zu den unterschiedlichen Klassifikationssystemen, die die Menschen weltweit verwenden, um nicht nur sich selbst als Menschen, sondern ebenso Götter und Gegenstände sowie Phänomene und Ereignisse ihrer Umwelt einzuordnen. Mauss und Durkheim stellen fest, dass die Klassifikationen von Gegenständen, Göttern und Symbolen einerseits die Klassifikation von Akteuren und andererseits die Hierarchisierung von Menschen und sozialen Gruppen sich reproduzieren und somit unmittelbar wie mittelbar mit der Gesellschaftsstruktur jener Sozialitäten korrespondieren. Damit eröffnen Mauss und Durkheim ein neues Gebiet für die Soziologie nach dem Prinzip, dass die Art und Weise, wie eine Gesellschaft organisiert und strukturiert ist, die Formen der Erkenntnis eben dieser Gesellschaft und zwar ausgehend von der sinnlichen Wahrnehmung maßgeblich bestimmt.[fn:57] Die Überlegungen zu den primitiven Klassifikationsformen führen Mauss auf die Spuren der Magie als möglicher Quelle der Entstehung mentaler Klassifikationsmuster, Kategorien und Repräsentationen.

Der gemeinsam mit Hubert verfasste /Entwurf einer allgemeinen Theorie der Magie/ (/Esquisse d’une théorie générale de la magie/) erscheint im Jahr 1904 in /L'Année/ unmittelbar nach dem Essay mit Durkheim. Nach Mauss und Hubert erweist sich die Magie als eine Sammlung von praktischen Riten, die im Vergleich zu religiösen Riten ungleich einfacher und individueller sind.[fn:58]. Entsprechend handelt es sich bei der Magie um eine Zusammenstellung von praktischen Techniken, die von einem Magier verwendet werden. Zwar agiert er augenscheinlich allein, gleichzeitig jedoch fungiert er insofern als Beauftragter der Gesellschaft, als er von der Gesellschaft und ihren Mitgliedern in Dienst genommen wird, deren Wahrnehmungs- und Erkenntniskategorien er in bedeutsamer Weise gestaltet. In der Magie glauben Mauss und Hubert die Quelle der kollektiven Repräsentationen gefunden zu haben, die die Grundlage des individuellen Verstandes bereitzustellen scheinen. Jedoch stößt die /Esquisse/ auf weniger Resonanz als die anderen Arbeiten von Mauss.[fn:59] Mauss' und Huberts doppelte Perspektivierung der Quelle kollektiver Repräsentation einerseits und der Grundlagen individueller Verstandestätigkeit andererseits legen grundsätzlich den Schluss nahe, dass die Grundlage der menschlichen Vernunft die Unvernunft bilde. Die Rationalität könne nur in Verbindung mit Gefühlen, Empfindungen und Emotionen entwickelt werden. Dies bestreiten insbesondere die Philosophen und unter ihnen auch diejenige, die Mauss eigentlich schätzen.[fn:60] Mit diesen Kritiken kommen noch die Krisen in den Verhältnissen zwischen Durkheim, Mauss und das Team von /L'Année/ hinzu. Viele der Mitarbeiter unterstützen Durkheims Auffassung der Soziologie nur teilweise, wenn sie sie überhaupt verstehen. In seinem berühmten Aufsatz zum Team von /L'Année/ hat Philippe Besnard deutlich gemacht, dass dieses Team nie homogen um Durkheim und Mauss stand. Mehr als ein "Team" handelt es sich um kleine Gruppen von ehemaligen Studenten, die miteinander und mit Durkheim wenig interagieren.[fn:61] Selten sitzen sie zusammen, und entsprechend sehr unterschiedlich ist das Engagement der verschiedenen Mitarbeiter in Unterstützung der konkreten Arbeit, die in /L'Année/ getan werden muss. In einem solchen Zusammenhang sind Krisen kaum vermeidlich, die unmittelbar nach der Veröffentlichung der ersten Nummer von /L'Année/ im Jahr 1900 auftauchen. Eine erste Krise entwickelt sich um die Frage, ob kritische Rezensionen veröffentlicht werden sollten. Eine zweite Krise folgt im Jahr 1902 um die Frage, ob es nicht besser wäre, in /L'Année/ nur Rezensionen und Besprechungen zu veröffentlichen und die /Mémoires/ der Mitarbeitet bzw. ihre langen eigenen Aufsätzen aus /L'Année/ auszuschließen. Eine dritte Krise kommt 1907 mit der Durchsetzung dieser letzten Maßnahme.[fn:62] Deshalb auch die Haltung von Durkheim, der mehr und mehr Einfluss auf /L'Année/ und auf die inhaltlichen Produktion seiner engsten Mitarbeitern ausübt. Dies betrifft Mauss nicht zuletzt, der in der Zeit nach 1904 versucht, sich von diesem Einfluss mit der Hoffnung zu befreien, dass er seine Kraft und seine Zeit in sein eigenes Pensum investieren kann.

Hubert hat es gut verstanden, der ab 1905 mit Mauss über die Möglichkeit spricht, ihre wichtigsten Studien, die in unterschiedlichen Zeitschriften publiziert wurden, gemeinsam in einem Band zu versammeln, um den roten Faden ihrer Arbeit in gebündelter Form sowohl verständlicher als auch deutlicher hervortreten zu lassen. Hubert schwebt hierfür bereits eine bestimmte Gliederung vor, was wiederum beiden Autoren die Gelegenheit gibt, einige Aussagen und Schlussfolgerungen zu präzisieren, stärker miteinander zu verbinden und gegebenenfalls aneinander anzupassen. Mauss und Hubert geht es in ihren versammelten Schriften in erster Linie um folgende zwei Botschaften: allgemeine Phänomene des sozialen Lebens müssen erstens vergleichend und induktiv untersucht werden; zweitens bilden den Ausgangspunkt solcher Studien insbesondere soziale Institutionen wie das Opfer, die Magie und die Klassifikationsformen. Anders gesagt, legen Mauss und Hubert nahe, dass die soziologische Untersuchung religiöser Phänomene induktiv und vergleichend zu verfahren habe und nach einem makrosoziologischen Ansatz zu entwickeln sei, was im Übrigen auch auf jede Art der soziologischen Untersuchung verallgemeinert werden könne.[fn:63] Ein Zwischenschritt in dieser Überlegung bietet sich mit dem Veröffentlichungsvorhaben, das Maus im Jahre 1905 mit Henri Beuchat zu den Eskimos-Gesellschaften vorbereitet. Zu den Eskimos gibt es wenige Daten, weshalb Mauss diese Lücke beseitigen möchte und nach London mit seinem Studenten und Freund Robert Hertz reist, um mehr Daten im /British Museum/ zu den Eskimos-Gesellschaften zu sammeln und auszuwerten. Dabei entdeckt Mauss einen Zusammenhang zwischen dem Rhythmus der Jahreszeiten und dem Rhythmus des gesellschaftlichen Lebens der Eskimos. Im Winter leben sie eng zusammen. Es ist eine Zeit der Feierlichkeiten, der religiösen Einheit und des sexuellen Kommunismus. Dagegen ist diese Form des Zusammenlebens im Sommer kaum noch spürbar bzw. wird auf ein Minimum reduziert.[fn:64] Diese Abwechslung im Rhythmus des sozialen Lebens entdeckt Mauss nicht nur bei den Eskimos, sondern auch bei den Indianer-Stämmen Nordamerikas und bei kleinen landwirtschaftlichen Gemeinschaften in den europäischen Alpen. Alles scheint zu geschehen, als ob die Gesellschaft hinter ihren Akteuren verschwinde, wenn für diese Akteure die Tätigkeitsfelder zunehmen und sie am umfassendsten beschäftigt sind. Dann verschwinden die Akteure hinter ihrer Gesellschaft im Winter wieder, wenn ihre Betätigungsfelder abnehmen und ihre Tätigkeiten auf ein Minimum reduziert sind. Dieser Essay mit dem Titel /Über den jahreszeitlichen Wandel der Eskimogesellschaften. Eine Studie zur sozialen Morphologie/ (/Essai sur les variations saisonnières des sociétés Eskimos. Étude de morphologie sociale/, 1906) wird mäßig rezipiert. Für Mauss stellt er sich jedoch als ein weiterer Schritt in Richtung der Entwicklung seiner Gedanken zu den religiösen Phänomenen und dahingehend insbesondere zum Verhältnis zwischen Individuen und Gesellschaften dar, welches Mauss und Hubert seit Beginn ihrer Zusammenarbeit und ihrer ersten gemeinsam verfassten Schriften besonders interessiert. Mit der relativen Emanzipation von Mauss zu /L'Année/ und zu seinem Onkel, dem gemeinsamen Vorhaben mit Hubert, das 1909 mit dem Titel /Mélanges d’histoire des religions/ veröffentlicht wird, kommt eine Zeit der beruflichen Selbstverwirklichung und Anerkennung. Auch im Bereich seiner politischen Tätigkeiten gewinnt Mauss an Bedeutung.

** Mauss als Botschafter der französischen Genossenschaftsbewegung

Seit dem Beginn seines Engagements in Unterstützung der Genossenschaftsbewegung in Frankreich wünscht sich Mauss den Aufbau von einem inter-nationalem Handelsnetzwerk zwischen Genossenschaften und insbesondere Konsumgenossenschaften. Es müssen "Beauftragten" der verschiedenen Genossenschaften ins Ausland gesendet werden, "um die unterschiedlichen Lebensmittel zu kaufen", um "Braunkohle gemeinsam zu kaufen; kurzum alle möglichen Mitteln verwenden, um diesen Verband herzustellen".[fn:65] Diese Botschaft möchte Mauss einem breiteren Publikum unterbreiten, und die Gründung der Zeitung /L’Humanité/ durch seine Bekannten Lucien Lévy-Bruhl, Léon Blum und Lucien Herr mit der Unterstützung von Jaurès[fn:66] wird ihm diese Möglichkeit geben. Mauss beteiligt sich an der Finanzierung der Zeitung und wirkt, gemeinsam mit Landrieu, als Redakteur der Rubrik "Genossenschaften" mit. Für Mauss und Landrieu geht es darum, die Genossenschaftsbewegung in der Öffentlichkeit bekannter zu machen bzw. zu verbreiten. Es müssen von so vielen Genossenschaften wie möglich gesprochen werden, um die Öffentlichkeit von der Bedeutung dieser Bewegung zu überzeugen.[fn:67] Entsprechend reist Mauss innerhalb Frankreich und ins Ausland, um an Ereignissen um die Genossenschaften teilzunehmen, und dabei erscheint er für viele Sozialisten, die wie Mauss die wichtige Rolle der Genossenschaftsbewegung in Unterstützung der Stärkung des Sozialismus hervorheben, als Botschafter der französischen Genossenschaftsbewegung. Mauss berichtet über die wachsende Bedeutung der deutschen Konsumgenossenschaften und der Grosseinkaufgesellschaft in Deutschland (gegründet im Jahr 1894),[fn:68] davon das Modell die britischen Wholesales-Gesellschaften sind.[fn:69] Das deutsche Beispiel zeigt die Bedeutung der Erziehungsrolle der Genossenschaften für die Arbeiter: "es geht vor allem darum, den Arbeiter zu erziehen und ihn dabei zu beeinflussen, die politischen Werkzeuge zu verwenden, um [seine; CP] Situation zu verbessen".[fn:70] Mauss versteht die Genossenschaften im engen Verhältnis mit dem Sozialismus. Die Genossenschaft ist eine "Form der Arbeiterhandlung",[fn:71] die "mit der allgemeinen Bewegung der modernen Gesellschaften zur Abschaffung der Klassen und des Angestelltenverhältnisses verbunden ist".[fn:72] Bis dies tatsächlich stattfinden kann, gibt es jedoch noch einen langen Weg zu beschreiten, wie Mauss bei seinen Reisen feststellt.

1904 findet der internationale Kongress der Genossenschaften in Budapest statt. Mauss reist nach Budapest, und er ist enttäuscht von dem, was er dort beobachtet: "Der Kongress geht weiter, und er ist nicht sehr interessant. (...) Selbst heute schließt er erfolglos, machtlos ab".[fn:73] 1905 reist Mauss nach Schottland zum Kongress der britischen Genossenschaften in Paisley mit dem Mechaniker, Sozialist und Mitglied einer der ältesten Genossenschaften in Frankreich /La Bellevilloise/ Louis Héliès. Im Auftrag der /Bourse des Sociétés coopératives ouvrières de consommation/ muss er insbesondere über die Wholesales berichten, um zu ersuchen, ob ein solches Modell in Frankreich implementiert werden könnte. Auch mit Héliès reist er anschließend nach Lüttich zum belgischen Kongress der Genossenschaften im Juli 1905. Aus diesen Reisen gewinnt Mauss die Ansicht, dass die Entwicklung der Genossenschaften in Frankreich zu langsam verläuft. Nicht genug wird getan, um für die Genossenschaften als Organisationsform des Klassenkampfes im Dienst der Arbeiter zu werben.[fn:74] Selbst diese Bezeichnung der Genossenschaft als politisierte Organisationsform wird in Frankreich infragegestellt, was Mauss vollkommen verblüfft: "[ich] glaube nicht, definitiv nicht, dass es im Interesse der genossenschaftlichen Arbeiter ist, dass sie ihre Organisationen als neutral verkünden".[fn:75] Diejenige, die es glauben, gehören Gide und den Anhängern seiner Denkschule in Nîmes, der sich von Mauss und Jaurès distanziert hat. Es sind die Unterstützer der "gelben" Genossenschaften, wie Mauss sie bezeichnet und von den "roten" Genossenschaften unterscheidet.[fn:76] Mauss nennt diese Genossenschaften "gelb" in Anlehnung an die französischen gelben Gewerkschaften, die die Gewerkschaften des Arbeitgeberverbandes sind und sich 1899 gegen die traditionellen Arbeitergewerkschaften gebildet haben, um die Arbeitergewerkschaften zu schwächen. Diese gelben Genossenschaften, wie es Mauss bedauert, mehren sich in Frankreich, wobei sie die Sozialisten eigentlich in Konsumgenossenschaften konvertieren sollten. Hinter dieser Unterscheidung zwischen gelben und roten Genossenschaften stellt sich die Frage der Form der Genossenschaft, die in Frankreich herrschen muss. Diese Frage ist nicht neu. Auf dem Kongress der /Union Coopérative/ von 1896 wurde die Möglichkeit erwähnt, die fünf Bereiche der Genossenschaftsbewegung -- Konsum, Produktion, Kredit, Bauwesen und Gewinnbeteiligung -- zusammenzustellen.[fn:77] Dieser Vorschlag wurde jedoch heftig kritisiert. Insbesondere die Vertreter der Pariser Genossenschaft /La Moissonneuse/ werben dafür, dass die Mehrheit der Genossenschaften wie kapitalistische Unternehmen handeln. Das Spannungsverhältnis zwischen Konsum- und Produktionsgenossenschaften gipfelt Anfang des 20. Jahrhunderts im Projekt des /Palais du Travail/. Dieses Bauprojekt, das gemeinsam von den Genossenschaftern der /Bourse coopérative/, der /Union coopérative/ und der Produktionsgenossenschaft /Chambre Consultative des Association Ouvrières de Production/ vorangetrieben wurde, hatte zum Ziel, Konsum- und Produktionsgenossenschaften mit den Gewerkschaftsorganisationen der /Bourse du Travail/ unter einem Dach zu vereinen. Die Meinungsverschiedenheiten zwischen den Initiatoren des Projekts waren jedoch so groß, dass der Bau des Gebäudes ohne weitere Begründung endgültig auf Eis gestellt wurde.[fn:78]

Mauss wie seine Freunde im Sozialismus stehen also vor einer Realität der Entwicklung von Genossenschaften in Frankreich, die sie nicht weg diskutieren können: Die Produktionsgenossenschaften wachsen tatsächlich, was Guillemin zum Schluss bringt, dass "das Gesamtwesen der französischen Genossenschaften eher egoistisch [ist]".[fn:79] Der Kongress der /Union coopérative/ und der Kongress der französischen Genossenschaften in Nantes (1905) haben an diesem Sachverhalt nichts geändert.[fn:80] Ab 1906 werden die Artikel von Mauss in /L'Humanité/ zu den unterschiedlichen Genossenschaften in und um Frankreich seltener, als ob er sich von der Genossenschaftsbewegung abwenden würde. Ab 1907 erscheint die Rubrik "Genossenschaften" von Mauss und Landrieu unregelmäßig. Mauss trägt jedoch weiter zum Thema der Genossenschaften vor, wie etwa im Rahmen der /Ecole socialiste/ in den Jahren 1910 und 1911, wo er Lehrveranstaltungen zur Ideologie und Geschichte der Genossenschaften anbietet.[fn:81] Im Jahre 1912 am Kongress der französischen Genossenschaften in Tours ist Mauss anwesend. Er widerspricht Gide einmal mehr, wenn dieser darauf besteht, dass die Genossenschaften und insbesondere die Konsumgenossenschaften die Unterstützung von "gelben" Genossenschaften nicht ablehnen, sondern annehmen müssen. Dieser Vorschlag geht gegen die Auffassung der Genossenschaften Mauss', aber die Mitglieder im Kongress unterstützen den Vorschlag von Gide.[fn:82] Damit wird für Mauss ein Kapitel seines Engagements im Sozialismus vorübergehend abgeschlossen. Aber nicht nur im Sozialismus muss Mauss mit Enttäuschungen umgehen, sondern auch in der Akademie.

1907 bewirbt er sich am Lehrstuhl für Geschichte der Religionen (ehemals Albert Révilles Lehrstuhl) am /Collège de France/.[fn:83]. Mit seiner ersten Bewerbung will Mauss insbesondere sein Interesse für den Lehrstuhl Révilles zum Ausdruck bringen. Er rechnet nicht ernsthaft damit, ausgewählt zu werden. Und tatsächlich geht der Lehrstuhl nicht an Mauss, sondern an Jean Réville, den Sohn von Albert Réville. Dennoch ist das Wahlergebnis für Mauss vielversprechend. Bereits in der ersten Wahlrunde erhält er, zur Überraschung seiner Freunde, viele Stimmen und die zweite Wahlrunde, in der der Vertreter des siegreichen Kandidaten gewählt wird, entscheidet er sogar für sich.[fn:84] 1908 stirbt Jean Réville und am /Collège de France/ wird der Lehrstuhl für die Geschichte der Religionen neu ausgeschrieben. Mauss sieht seine Chance gekommen und bewirbt sich erneut auf den Lehrstuhl. Sein Hauptmitstreiter ist der Theologe und Historiker Alfred Loisy, der aufgrund seines "Modernismus" von der katholischen Kirche exkommuniziert wurde. Viele glauben an Mauss' Chancen und unterstützen seine Bewerbung. Aber Loisy genießt ebenfalls eine starke Unterstützung und erhält schließlich den Lehrstuhl. Mauss, der noch auf die Ehrenstelle als Vertreter Loisys gehofft hatte, verliert auch diese Wahl, was für ihn und seine Freunde eine umso größere Enttäuschung ist, als dass alle um die Seltenheit solcher Gelegenheiten wissen.[fn:85] Zu dieser Enttäuschung kommt eine weitere hinzu, die Mauss' eigene Forschung betrifft: Seine Arbeit an der Dissertation zum Gebet schreitet nicht voran.

Seit mehr als zehn Jahren sammelt Mauss Daten zu positiven Riten wie dem Gebet und in den Jahren zwischen 1907 und 1908 ist er davon überzeugt, dass er sein Manuskript bald fertigstellen kann. Aber die ersten Seiten, die er Durkheim, Espinas und Sylvain Lévi zu lesen gibt, sind enttäuschend. Mauss verliert sich in seinen Daten und findet keinen Ausweg zur Synthese. Zudem entdecken Mauss und Durkheim in Carl Strehlows Arbeiten zu den australischen Aranda- und Loritja-Stämmen viele weitere Daten, die Mauss dazu bewegen, seine Arbeit an dem Gebet stark zu revidieren. Mauss sieht im Gebet eine Kreuzung der wichtigsten religiösen Phänomene, die in einer einfachen bzw. individuellen und mündlichen Form ausgedrückt werden, um unmittelbar auf die sakralen Gegenstände und Akteure zu wirken. Das Gebet versteht Mauss im Lichte der Arbeiten, die er liest, wie eine Handlung auf Distanz, mit der beabsichtigt wird, sakrale Gegenstände und Akteure zum Handeln zu bringen. /Das Gebet/ (/La Prière/) verfasst Mauss in der Zeit, in der Durkheim an /Die elementaren Formen des religiösen Lebens/ (/Les Formes élémentaires de la vie religieuse/, 1912) arbeitet. Beide Werke beziehen sich auf ähnliche Daten zu den australischen Aborigine- und neuseeländischen Maori-Kulturen und stützen sich gegenseitig.[fn:86]. Aber im Jahr der Veröffentlichung von /Die elementaren Formen des religiösen Lebens/ hat Mauss seinen Text zum Gebet immer noch nicht fertiggestellt. Fortwährend den nächsten Schriften von Strehlow auf der Spur, wird Mauss müde und krank. Von der Schrift /Das Gebet/ sind heute 176 Seiten überliefert, die Mauss nie zur Vollendung gebracht hat. Der Krieg wird die letzten Hoffnungen begraben, aus dem Gebet eine Dissertation zu entwickeln.

** Elsass im Hintergrund von Gift, Gift

"'Ich fühle mich prächtig gut. Ich war dafür und gar nicht für die Soziologie gemacht'".[fn:87] Mauss erlebt an der Front einen ganz anderen Marcel, der sich für lange Spaziergängen und für das Bergsteigen begeistert und den Eindruck bekommt, dass er in diesem gefährlichen Kontext einmal selbstständig den Kurs seines Lebens bestimmen kann. Aber die Härte des Krieges wird ihm nicht erspart. Mauss erfährt im Laufe der Jahre den Tod von den vielen Freunden, die mit ihm an der EPHE oder an /L'Année/ mitgearbeitet haben. Ihn treffen die sukzessiven Nachrichten des Todes von André Durkheim dem Sohn seines Onkels und von Durkheim selbst im Jahre 1917 besonders hart. Zurück aus dem Krieg muss sich Mauss im zivilen Alltag wieder abfinden. Es geht primär nicht um die akademische Arbeit, sondern um die letzten gesellschaftlichen und insbesondere politischen Ereignissen, die Frankreich und die Länder Europas nach dem Ersten Weltkrieg beschäftigen. Jaurès ist gestorben, und die sozialistische Partei wurde reformiert. Sie trägt den Namen /Section française de l’Internationale ouvrière/ (SFIO). In Russland hat eine russische Revolution stattgefunden, die die französischen Sozialisten vor der Frage setzt, ob sie zum Kommunismus überlaufen sollten. In Konkurrenz zur SFIO bildet sich 1920 die erste französische kommunistische Partei (PCF), die auf Anhieb doppelt so viele Mitglieder wie die SFIO (120.000 zu 50.000) registriert.[fn:88]. /L’Humanité/, bei der Mauss Vorstandsmitglied geblieben ist, trennt sich von der SFIO, um zum Veröffentlichungsorgan der PCF zu werden. Mauss, der der russischen Revolution und der kommunistischen Partei kritisch gegenübersteht,[fn:89] wird aus dem Vorstand von /L’Humanité/ ausgeschlossen. Seine politische Haltung definiert er am Vorbild von Sidney und Beatrice Webb in Großbritannien, die eine Art von Sozialreformismus unterstützen, der nach Ansicht von Mauss zur nationalen Einheit beitragen kann. Nach dem Ersten Weltkrieg benötigen die Länder Europas vor allem Einheit, weshalb jede Art von Spaltung der Sozialisten vermieden werden sollte, die zur Spaltung Frankreichs und zur erneuten Spaltung Europas führen könnte. Diese Sorgen von Mauss teilen mehrere Kollegen wie Christian Pfister an der französisch gewordenen Universität Straßburg, der Mauss zur Festschrift für Charles Andler einlädt und /Gift, Gift/ veröffentlicht. /Gift, Gift/ ist nicht nur ein akademischer Text, der Mauss zur Zusammenfassung seiner vergangenen Überlegungen hilft und der Anmeldung seines künftigen Thema zur Gabe dient. Es ist auch ein politischer Text angesichts des Kontextes seiner Veröffentlichung und der inhaltlichen Botschaft in Bezug auf diese erwünschte Einheit der Gesellschaften nach dem Krieg.

Charles Andler wie Christian Pfister sind nicht in Straßburg zufällig. Beide sind Elsässer -- Andler ist in Straßburg geboren. Christian Pfister bekommt den Lehrstuhl für die Geschichte Elsass (1919). Charles Andler ist Professor für deutsche Literatur und deutsche Sprache an der Fakultät für Literatur der Universität in Paris. Eng befreundet mit Lucien Herr, der als Bibliothekar der Durkheim-Schule fungiert, ist Andler im regelmäßigen Austausch mit Durkheim und der Durkheim-Gruppe.[fn:90] Im Ersten Weltkrieg unterstützen Durkheim, Mauss, Sylvain Lévi und Lucien Lévy-Bruhl Andler, der die /Ligue républicaine d'Alsace-Lorraine/ leitet und in diesem Zusammenhang das französische Recht in den besetzen Gebieten in Elsass zu verbreiten versucht. Damit verbunden ist die Idee, eine französische Universität in Straßburg zu gründen, wenn die Deutschen besiegt werden und Elsass wieder französisch wird.[fn:91] Diese Idee, die ab 1915 im Rahmen der /Conférence d'Alsace-Lorraine/ -- eines Ausschusses des französischen Außenministeriums -- erwähnt wird, wird konkreter im Jahre 1917, wenn der französische Kriegsminister für die Verwaltung Elsass-Lothringens verantwortlich wird[fn:92] und eine Abteilung /Service d'Alsace Lorraine/ eröffnet, die einen Ausschuss für Hochschulen ins Leben ruft, dazu Pfister und Andler mit fünf anderen Kollegen gehören.[fn:93] Diese sieben Professoren verfassen einen Bericht zur Rekonstruktion der Universität Straßburg, die zu einer der wichtigsten Universität Frankreichs werden soll -- und gleichzeitig ein Schaufenster der französischen akademischen Exzellenz in der Rivalität zum deutschen Hochschulsystem. Pfister muss entsprechend eine Fakultät für Literaturwissenschaft gründen, und innerhalb dieser Fakultät wird 1919 der ehemaligen Lehrstuhl für Soziologie und Pädagogik von Georg Simmel an den Durkheim-Schüler Maurice Halbwachs vergeben, der 1922 ihn zum Lehrstuhl für Soziologie umbenannt.[fn:94] Das ist der erste Lehrstuhl für Soziologie an einer Universität in Frankreich.

Seit seiner Herstellung war die Vergabe dieses Lehrstuhls an die Durkheim-Schule wie selbstverständlich: "Die Soziologie hat (...) unter der Leitung von Meistern wie Durkheim so große Fortschritte gemacht, dass es unerlässlich ist, diese Wissenschaft in Straßburg vertreten zu lassen" sagt Pfister.[fn:95] Für die Durkheim-Gruppe kompensiert die Einrichtung des Straßburger Lehrstuhls den Verlust des Lehrstuhls für Sozialphilosophie in Toulouse im Jahr 1921, der seit 1908 zunächst von Bouglé und dann von Fauconnet besetzt war. Pfister gesteht gerne, dass er unter dem Einfluss von ehemaligen Durkheim-Schülern wie etwa Lévy-Bruhl und Salomon Reinach stand.[fn:96]. Als er an der /Ecole Normal Supérieure/ "Quadrat und Kubik war", freute er sich, ehemalige Schüler des Lycée Louis-le-Grand willkommen zu heißen, darunter "insbesondere Durkheim, den bereits mächtigen und kraftvollen Philosophen".[fn:97] Zudem war Halbwachs von Oktober 1914 bis Oktober 1918 Professor für Philosophie am Lycée de Nancy in der Stadt, in der Pfister 25 Jahre lang unterrichtet hat. Andler gefällt eine solche Entscheidung, die seiner Vision für die Universität Straßburg entspricht. Wie Pfister und sein Freund Herr "träumten [sie] davon, daraus die Grundlage für eine nationale Reform des Hochschulwesens bereitzustellen. Sie wollten, dass der Forschung mehr Gewicht im Vergleich zur Vorbereitung auf Prüfungen und Auswahlverfahren beigemessen wird. Sie wollten auch die zunehmende Abschottung der Disziplinen bekämpfen, die Forschung und Lehre zunehmend prägte".[fn:98] Die Vorschläge von Andler werden nicht alle aufgenommen, aber die neue französische Universität in Straßburg folgt der allgemeinen Linie, die sich Andler und andere Akademiker wünschen -- in den Worten Craig muss diese Universität "an instrument of nation building" werden.[fn:99] Die Nation aufbauen, bedeutet in diesem Kontext nicht nur Frankreich wieder aufzubauen, sondern über die Universität in Straßburg aus Frankreich hinaus zur Bildung einer europäischen Nation beizutragen, die zeigen würde, wie Frankreich im voraus der anderen europäischen Nation sei und darunter speziell vor Deutschland.

Damit erklärt sich auch die besondere Hervorhebung des deutschen Rechtes und der Vielfalt der deutschen Sprache in /Gift, Gift/, die nicht zufällig behandelt werden und auch nicht nur deshalb, weil Andler ein in Frankreich anerkannter Germanist ist. Es geht um die Mitteilung einer Botschaft, die darin besteht, dass Frankreich in der Verbindung zu Deutschland, in der Befriedung der Verhältnisse zu Deutschland und in der Wiederaufnahme des Austauches mit Deutschland die Idee der Nation jenseits von Nationalismen entwickeln kann, sie auf eine andere Ebene der gesellschaftlichen Organisation -- auf der Ebene Europas -- bringen kann. Dabei geht es, wie Mauss einige Jahre später mit /Die Gabe/ zeigen wird, um Frieden, Austausch, um die gegenseitige Nacheiferung im Aufbau einer geteilten totalen sozialen Tatsache. Diese in /Gift, Gift/ implizite Botschaft zur inter-nationalen Einheit macht Mauss explizit in seinen unterschiedlichen Schriften in der Unterstützung des Sozialismus in Frankreich, dessen Einheit mit der Bildung der französischen kommunistischen Partei zu kippen droht.

** Sozialismus und Genossenschaften nach dem Ersten Weltkrieg

1912 hat Mauss an dem Kongress in Tours teilgenommen, der das Ziel erreichen sollte, die Genossenschaften in Frankreich zu vereinheitlichen. Als Beauftragte der /Fédération nationale des coopératives/ arbeitet er seit 1911 an der neuen Strukturierung der Genossenschaften in Elsass und darunter insbesondere der sozialistischen Genossenschaften und Arbeitergenossenschaften, die 1914 im neuen Verband der Genossenschaften Nord-Osten zusammengestellt werden.[fn:100] Unmittelbar nach dem Ersten Weltkrieg nimmt Mauss an dem Pariser Genossenschaftskongress teil, und in diesem Zusammenhang erwähnt er die Bedeutung der Propaganda zur Verbreitung der Genossenschaften in Frankreich.[fn:101] Mauss geht es um die Ausbildung der Genossenschafter auf die sozialistischen Ideen in einem Moment, in dem diese Ideen von den Kommunisten in Frankreich und von den Bolschewiken im internationalen Raum herausgefordert werden. Diese Propaganda-Arbeit ist Mauss umso wichtiger, als mit der enttäuschenden Wende der Zeitung /L'Humanité/ zum Medium der kommunistischen Partei eine solche Arbeit erschwert wird. Deshalb auch investiert Mauss ab 1921 die neu gegründete Zeitung /Le Populaire/, die seiner Auffassung nach zum Veröffentlichungsorgan der Sozialisten entwickelt werden sollte und tatsächlich entwickelt wird. Zwar ist /Le Populaire/ eine kleine regionale Zeitung, aber sie wird zu einem wichtigen Sprachrohr des Widerstandes gegen die kommunistische Ideologie und später auch gegen die faschistische Ideologie. Mit seinen Veröffentlichungen in dieser Zeitung möchte Mauss nicht nur die Einheit der Sozialisten beschwören, sondern ebenso die Einheit zwischen Soziologen und Sozialisten fördern. Die Soziologie versteht Mauss im Dienste des Sozialismus, der mithilfe der Soziologie die Regierungen über drängende gesellschaftliche Fragen der Gegenwart und die Bevölkerungen über die Handlungen ihrer Regierung exakt informieren kann. Die Soziologie hat die Aufgabe, Regierungen und Bevölkerungen auszubilden und Handlungsformen für ein harmonisches Gesellschaftsleben vorzuschlagen. Solche Handlungsformen bieten Genossenschaften an, wie es Mauss immer wieder wiederholt, weshalb es sehr wichtig sei, die Propaganda in diesem Zusammenhang weiter voran zu treiben. Im Kongress der französischen Genossenschaften in Marseille (1922) wird Mauss von Gide, dem ehemaligen Mitstreiter, gelobt.[fn:102] Gide sieht in Mauss eine anerkannte Autoritätsfigur des Sozialismus, der besonders die Ausbildung auf die Genossenschaften gefördert hat und sie in dem Unterricht in Schulen und Hochschulen in Frankreich etablieren will. Gide unterstützt Mauss maßgeblich: Das Bildungsministerium müsse aufgefordert werden, einem solchen Unterricht auf alle Ebenen des französischen Ausbildungssystem zu verbreiten und ihm ein bedeutsames Gewicht zu verleihen. Diese Arbeit von Mauss und anderen im Dienst der sozialistischen Propaganda bringt kleine Erfolge: Seit dem 18. August 1920 findet an den französischen Grundschulen eine einstündige Lehrveranstaltung zur Wirtschaftssoziologie wöchentlich statt, die als Pflichtlehrveranstaltung gilt.[fn:103]

Vor seinem Engagement in /Le Populaire/ unterstützt Mauss die 1916 neue Zeitschrift /L'Avenir. Revue du socialisme/, die Jean-Baptiste Séverac gründet und als die Zeitschrift versteht, die entscheidend in Unterstützung der Einheit des französischen Sozialismus arbeiten muss.[fn:104] Auf Séverac wird Mauss wegen Séveracs Brochüre /Le Socialisme moderne/ aufmerksam, die er in der Zeitung /L'Aurore/ erwähnt.[fn:105] Séverac und Mauss fürchten gleichermaßen die Schwächung des Sozialismus durch die Tendenz von einigen der französischen Sozialisten, eine Allianz nicht nur mit der französischen kommunistischen Partei, sondern auch mit der III. Internationale zu befürworten. Nach Mauss und Séverac, die mit anderen Sozialisten einen Protestbrief unterschreiben, um eine solche Allianz zu kritisieren, würde diese Allianz die Prinzipien des französischen Sozialismus verraten, die "die Demokratie, die gewerkschaftlichen Organisation und die nationale Verteidigung" seien.[fn:106] Séverac wird anschließend zum Mitglied des "Widerstandskomitees" der sozialistischen Partei, und er verfasst ein Manifest gegen die Spaltung der Sozialisten.[fn:107] Mauss unterzeichnet dieses Manifest nicht. Dennoch veröffentlicht er in /L'Humanité/ einen Text mit dem Titel "Avant le congrès. Double question", in dem er die Sozialisten warnt, die für eine Allianz mit den Kommunisten und mit der III. Internationale plädieren würden: Sie würden die Verantwortung für das Ende des französischen Sozialismus tragen. Im gleichen Kontext wird Séverac zum Mitglied der Redaktion und des Verwaltungsbeirates von /Le Populaire/, und wie Mauss schreibt er für die von Bernard Lavergne neu gegründete /Revue des études coopératives/, die Mauss finanziell unterstützt.[fn:108] Die Postionen von Séverac und Mauss sind jedoch nicht in Stein gemeißelt -- ihre Opposition zielt nicht darauf ab, Fronten im Sozialismus zu verhärten, sondern sich die Frage zu stellen, welche Art der Einheit die französischen Sozialisten sich wünschen. Wie Mauss sagt: "Wir sind keine begeisterten Anhänger der einheitlichen 'Front', aber wir sind begeisterte Verfechter der einheitlichen Internationale".[fn:109] Was Mauss mit dem Ausdruck "einheitliche Internationale" meint, macht er ein Jahr später deutlich: Es ist "eine Aktion gegen die Besetzung des Ruhrgebiets, gegen die Unterdrückung durch die Regierung und gegen die Gefahr eines neuen imperialistischen Krieges".[fn:110] Diese Botschaft verbindet Mauss und Séverac in diesen Jahren, und sie wird in den Artikeln widerspiegelt, die sie 1923 und 1924 für /Le Populaire/ verfassen. Beide verstehen die Einheit der Sozialisten im Zusammenhang der Arbeit an der Befriedung der internationalen Beziehungen. Beide erklären dem Kapitalismus den Kampf, dessen Entwicklung in einen Finanzkapitalismus mündet, der weit entfernt von den realen Leistungen in der Arbeitswelt wächst und immer mehr rein in Bezug auf die Vermehrung von Geld auf dem Rücken der gerechten Verteilung dieses Geldes in der Gesellschaft aufgebaut wird. Mauss versteht diese Entwicklung als eine der Hauptursachen des Ersten Weltkrieges. Dies analysiert er in seinen Artikeln über Geld, Wechselkurse und vor allem das Problem der schwankenden Schulden, die nach dem Ersten Weltkrieg den Boden für alle Arten von Spekulationsgeschäften bilden und zur Schwächung des Wertes vom Franc beitragen.[fn:111] Für Mauss geht es darum, dass die Sozialisten das Problem des Faschismus und seine Verbindungen zu den Banken ernst nehmen und eine solche Konstellation verhindern.[fn:112] Eine andere Art des Zusammenlebens ist möglich, und ein Modell davon liefern Gesellschaften in anderen Kulturen, die nach dem Austausch von Gaben strukturiert werden. Diese Botschaft, die im Kern von /Gift, Gift/ steht, entwickelt Mauss in seinem Essay /Die Gabe/ (1925) weit und breit.

Bei der Gabe handelt es sich um eine Tauschpraxis zwischen Freiheit und Verpflichtung, Eigennützigkeit und Uneigennützigkeit. Sie verbindet nicht nur die Akteure innerhalb einer Gesellschaft oder verschiedene Gesellschaften miteinander, sondern sie hierarchisiert sie auch auf dynamische Art und Weise entsprechend dem Geben, Empfangen und Erwidern der Gabe. Während also Mauss' Untersuchungen der religiösen Phänomene die Bedeutung des Verhältnisses von Gesellschaft, Göttern und Natur und im Anschluss daran zwischen Individuum und Gesellschaft unterstreicht, verallgemeinert /Die Gabe/ die Ergebnisse dieser Untersuchungen und hebt sie gleichsam auf eine höhere Ebene. So zeigt /Die Gabe/, dass ein solches Verhältnis einerseits Folgen für die Grenzziehung bzw. Unterscheidung zwischen Gruppen von Akteuren und andererseits Konsequenzen für die Verteilung der Akteure auf Positionen in ihrer Gesellschaft zeitigt. In den Gabepraktiken geht es somit gleichzeitig um das Selbst, seine Gruppe und seine Gesellschaft. Deshalb stellt die Gabe grundsätzlich sowohl eine individuelle als auch eine kollektive Herausforderung dar.

** Die Gabe als gesellschaftliches Modell

Die Gabepraktiken werden von Akteuren und Kollektiven getätigt, die sich mittels dieser Praxis gegenseitig verpflichten und ihre Interessen verteidigen. Diesen Sachverhalt hat Mauss bereits in dem mit Henri Hubert gemeinsam verfassten /Essai sur la nature et la fonction du sacrifice/ (1899) thematisiert. Das Opfer ist, wie die Autoren betonen, sowohl "ein nützlicher Akt" als auch "eine Verpflichtung".[fn:113] Der Profane hat "Interesse daran", sich dem Sakralen anzunähern, "da sich dort die Voraussetzungen seiner Existenz befinden".[fn:114] Mit der Ausnahme des Götteropfers, das der einzige Fall ist, "bei dem jede egoistische Berechnung fehlt",[fn:115] schließen die Opferpraktiken das egoistische Kalkül nicht aus. Denn es geht um das eigene Selbst, um die eigene Gruppe und um die Bewahrung der eigenen Identität sowie der gesellschaftlichen Regeln und Normen. Die Gabepraktiken zeichnen sich durch dieselben Grundmechanismen aus, und sie sind ebenfalls nicht frei von den Gefahren, die das Opfer umgeben. Wenn in der Gabe etwas von sich selbst gegeben wird, ist dieses "etwas" deshalb wichtig, weil es signalisiert, dass der Geber nicht alles von sich selbst gibt. Dieses "etwas" ist das, was Mauss mit dem /hau/, dem Geist des Gebers im gegebenen Gegenstand bezeichnet und das seine Zweideutigkeit und seine mögliche Gefährlichkeit als Gegenstand ausmacht, der zwar gegeben wird, gleichzeitig jedoch immer mit seinem Besitzer verbunden bleibt.[fn:116]

Zu dieser Erklärung kommen Mauss und Hubert bereits in ihrem Essay über das Opfer, wenn sie von den sakralen Gegenständen sprechen. Einen sakralen Gegenstand zu besitzen, ist sowohl begehrenswert als auch gefährlich, ebenso wie der Kontakt mit den Dingen und Wesen, die mit diesem sakralen Gegenstand verbunden sind, gefährlich ist. Deshalb müssen Rituale entwickelt werden, die es erlauben, sich solche Gegenstände ohne Gefahr anzueignen. Doch warum wollen die Akteure sich solche gefährlichen Gegenstände überhaupt aneignen? Wie die Opferpraktiken zeigen, wird bei ihrer Aneignung das Sakrale bzw. die Sakralität dieser Gegenstände auf die Akteure übertragen. Dieser Aspekt findet Mauss in der Gabe des /vaygu’a/ bei den Bevölkerungen der Trobriand-Inseln erneut vor: "Aber man kann nicht umhin, ihre erhabene und sakrale Natur zu erkennen. Sie zu besitzen, 'ist erheiternd, tröstlich und besänftigend an sich'. Ihre Besitzer befühlen und betrachten sie stundenlang. Durch bloße Berührung werden ihre Kräfte übertragen".[fn:117] In der Gabe ist also das Eigentum in Form des angeeigneten Gegenstandes nicht weniger ambivalent als die in den Opferpraktiken aufgeopferten Gegenstände. Diese Gegenstände werden angeeignet, weil sie einerseits Macht bringen und andererseits die Position des Akteurs im Austausch mit anderen Akteuren stärken. Jedoch haben die Gabepraktiken nicht zur Folge, dass sich die Akteure und ihre Gruppen von anderen Akteuren und Gruppen egoistisch zum Zweck der Bewahrung ihrer Macht und Stärke entfernen. Diese Praktiken führen die Akteure vielmehr dazu, sich gegenüber anderen Akteuren und Gruppen zu behaupten und sich in der Öffentlichkeit als kühne Austauschpartner zu zeigen, um den Austausch mit anderen Akteuren und Gruppen weiterhin zu fördern. Diese Selbstbehauptung der Akteure im Gabentausch gewährleistet die Selbsterhaltung der Akteure und Gruppen im Fluss des Tausches mit anderen Akteuren und Gruppen. In der Gabe werden Tauschmöglichkeiten maximiert, die von relationalem Wert sind und die zur Stärkung der kollektiven Praktiken und der daraus entstandenen individuellen und sozialen Identitäten beitragen. Diese Maximierung von Tauschmöglichkeiten ruht auf das Geben, Empfangen und Erwidern der Gaben, die als die drei Operationen des Gabentausches mit entsprechenden Rechten und Pflichten verstanden werden.

Bei den Hausa in Libyen wird den Armen und den Kindern nicht nur gegeben, um die Verstorbenen zu erfreuen, sondern auch, um sie "an dem Übermaß an Glück und Reichtum einiger Menschen [zu rächen], die sich seiner entledigen müssen: es ist die alte Gabenmoral, die zum Gerechtigkeitsprinzip geworden ist".[fn:118] Bei einer solchen Verteilung von Gaben geht es allerdings nicht nur um ein Gerechtigkeitsprinzip, das in Form von Almosen zutage tritt. Es geht auch um die öffentliche Verdeutlichung unterschiedlicher sozialer Statusdifferenzen, die sich in Vermögen, Geschlecht und Generation niederschlagen, im Gabentausch zu unverwechselbaren Merkmalen werden und mit spezifischen Gegenständen verbunden sind. Die symbolische Verbindung zwischen /mwali/ (Armbänder) und /soulava/ (Halsketten) im Trobriandschen /kula/, die Bronisław Malinowski in seiner Monographie /Argonauts of the Western Pacific/ (1922) beschreibt, bezeichnet die Ehe zwischen Frauen und Männern.[fn:119] Die gegebenen Gegenstände lenken die Aufmerksamkeit des Gebers auf den sozialen Rang des Empfängers. Im /kula/ kann dieser Gabentausch die Form eines Wettbewerbs annehmen, bei dem die Protagonisten miteinander konkurrieren, sich gegenseitig herausfordern und ihr Vermögen zur Schau stellen, um ihre Macht zu inszenieren und dabei zu versuchen, den Austausch zu vermehren, damit nicht nur die Anzahl der getauschten Gegenstände, sondern auch der Wert dieser Gegenstände steigt. Bei diesen Gabewettbewerben wird die gesamte soziale Hierarchie der Gruppen offengelegt, wobei der gegebene Gegenstand als Vermittler dieser Enthüllungsoperation fungiert. So werden etwa bei den Kwakiutl alle Gegenstände im Haus der Familie nach Position der Akteure in der Familie personalisiert. Sie tragen Namen, die mit den Titeln der adligen Männer und Frauen und ihrer Privilegien verbunden sind.[fn:120] In Melanesien werden die Gaben, die innerhalb von Bruderschaften von Männern und Frauen ausgetauscht werden, für den Erwerb von Titeln und für den Aufstieg innerhalb dieser Bruderschaften verwendet.[fn:121] Dort entspricht jeder Titel einem bestimmten Gegenstand. Bei den Kwakiutl ist es die Zauberkiste, die bei Initiationsriten oder Hochzeiten überreicht wird und "den Empfänger in ein 'übernatürliches' Wesen -- einen Schamanen, Magier, Adligen, Inhaber von Tänzen oder Sitzen in einer Bruderschaft" verwandelt.[fn:122]

Der Gabentausch spiegelt also eine ganze soziale Organisation wider, und obwohl Mauss einerseits immer wieder auf die Vermischungen hinweist, die durch Gaben entstehen und die zu Verwebungen von sozialen Gruppen, Geschlechtern oder sogar Stämmen führen, zeigt er andererseits, dass soziale Unterscheidungen durch den Gabentausch verschärft werden. Die Praxis des Gabentausches bringt zwar Akteure mit unterschiedlichen sozialen Positionen zusammen, aber sie zielt nicht darauf ab, diese Unterschiede zwischen Positionen zu beseitigen. Im Gegenteil tragen die Gaben zur Selbstbehauptung der Akteure und der sozialen Gruppen, zur Hervorhebung ihrer sozialen Position und zur Schärfung der vielfältigen Operationen bei, die notwendigerweise durchgeführt werden müssen, um diese Gaben so zu tätigen, wie sie getätigt werden müssen: "es ist nicht wie auf einem Markt, wo man objektiv, zu einem bestimmten Preis, eine Sache nimmt. Nichts bleibt hier dem Zufall überlassen"[fn:123] sowohl beim Geben, als auch beim Empfangen, als auch beim Erwidern. Im Folgenden vertiefen wir die Bedeutung der drei Positionen des Gebens, Empfangens und Erwiderns, die zusammen, wie Mauss sagt, die "Zyklen" des Gabentausches strukturieren.[fn:124]

** Geben, Empfangen und Erwidern als Zyklus der Gabe

Das Geben zeichnet sich durch die "Mobilisierung" des Kollektivs aus.[fn:125] Der /potlatch/ in Nordamerika oder in seiner abgeschwächten Form des melanesischen /kula/ stellen deutliche Beispiele einer solchen Mobilisierung des Kollektivs dar. Der /potlatch/ wird von einem Häuptling, sei es ein Familien- oder ein Clanchef, gegeben. Das Geben des /potlatchs/ setzt voraus, dass der Häuptling nicht nur seine Familie, sondern die größtmögliche Anzahl von Akteuren um sich herum schart. Im melanesischen /kula/ versammeln sich die Dörfer und Clans um ihren Chef, bereiten maritime Expeditionen vor, um Dörfern und Clans auf anderen Inseln Gaben zu überbringen. Es sind stammesübergreifende Phänomene, die "ja selbst auf internationaler Ebene bestimmt werden",[fn:126] wie die Beispiele des nordamerikanischen /potlatch/ zeigen. Sie kommen aber auch dorf- oder clanintern wie beim potlatch der Tlingit oder in Britisch-Kolumbien vor. Diese verschwenderische Ausgabe, die bis zur Zerstörung des von diesen Gesellschaften im /potlatch/ angehäuften Vermögens gehen kann, symbolisiert das Prestige, das adelige Wesensmerkmal der Häuptlinge und ihrer Clans. Sie wird häufig von verschiedenen Ritualen begleitet -- der Geber wird zum Schafott gebracht, der Klettermast wird aufgezogen --, die metaphorisch auf eine doppelte Bewegung des Gebers bzw. der Geber verweisen, der/die durch das Geben des /potlatch/ seine/ihre soziale Position den Empfängern des /potlatch/ zeigt/zeigen und ihnen dadurch seinen/ihren Einfluss auf sie deutlich macht/machen.[fn:127]

Mit dem Empfangen von Gaben stellt sich die Frage der weiteren Durchführung des Gabentausches und daher der Verantwortung für den Gabentausch im Dorf oder im Clan. Gleichzeitig bedeutet diese Position für den Geber, der eine Gabe erbracht hat und sich jetzt in der Position befindet, eine Gabe zu empfangen, dass er "vom Zorn des Gebers abhängig" ist.[fn:128] Er wird zu dessen "'Partner-Kandidat'", wie die Melanesier sagen.[fn:129] Dieser Partnerstatus ist variabel, und diese Variabilität spiegelt sich sowohl in der Vielfalt der Gegenstände, die der Partner-Kandidat erhält, als auch in seiner Haltung zu diesen Gaben wider. Daher ist es wichtig, diesen Partner zu umschmeicheln und ihm mehrere Gaben darzubieten, die ihm zeigen, mit wem er zu tun hat. Die Entgegennahme ist gleichermaßen ein Test, der belegt, ob der Empfänger fähig ist, den Gabentausch auf weitere Akteure im Dorf oder im Clan bzw. auf das Kollektiv auszuweiten. Ist der Partner "erst zur Hälfte Partner" oder ist er ein Partner, der sich wirklich verpflichtet, die Gabe nicht nur anzunehmen, sondern sie auch und vor allem zu erwidern? Wenn der Empfänger die Gabe ablehnt, dann verliert er unweigerlich an "Würde".[fn:130] Auch wenn solche Ablehnungen hin und wieder vorkommen, betreffen sie nur bestimmte Akteurkategorien, nämlich solche, die im Allgemeinen einen hohen sozialen Status haben. In der Regel werden Gaben jedoch nicht abgelehnt, denn eine solche Verweigerung würde den Empfänger isolieren. Deshalb gibt es in der Position des Empfangens für den Empfänger und den/die ihm gegenüberstehende(n) Geber eine doppelte Herausforderung. Es wird geprüft, ob der Empfänger seine Position halten kann, wenn er am Gabentausch teilnimmt, und ob er fähig ist, in diesem Tausch zu bleiben. Von dem Empfänger wird also erwartet, der Gabe zu widerstehen und dabei seine Identität und seine Würde unter Beweis zu stellen. Gleichzeitig wird die Fähigkeit des Gebers infrage gestellt, Gaben zu tätigen, weshalb der Geber Strategien einsetzt, um zu gewährleisten, dass der Empfänger die Gabe tatsächlich annimmt.

Sowohl für den Empfänger als auch für den Geber ist deshalb das Empfangen der Höhepunkt im Zyklus des Gabentausches. Mit dem Empfangen werden die jeweiligen Positionen im Gabentausch bestätigt, und gleichzeitig wird der Punkt erreicht, an dem der Gabentausch fortgesetzt oder unterbrochen wird. Abgesehen von der sozialen Identität der Akteure, die durch ihre Position im Gabentausch gekennzeichnet ist und ihre Position in der gesellschaftlichen Hierarchie widerspiegelt, steht das Prinzip der Identifikation selbst auf dem Spiel. Denn durch die Ablehnung der Gabe weigert sich der Empfänger nicht nur, sich dem Gabentausch zu stellen. Er verwehrt auch anderen die Möglichkeit, zu zeigen, wer sie sind, wie sie ihre Ehre verteidigen, welche Macht sie haben und zu welchen Opfern sie fähig sind. Das Erwidern der Gabe entspannt diese Situation.

Nach Mauss ist der "wichtigste dieser geistigen Mechanismen [des Gabentausches; CP] (...) ganz offensichtlich jener, der dazu zwingt, das empfangene Geschenk zu erwidern".[fn:131] Das Erwidern der Gabe ist zeitlich gesehen nicht nur der letzte Akt im Zyklus des Gabentausches. Es ist auch der Moment der Anerkennung der Position des Gebers seitens des Empfängers einerseits, die Anerkennung der Position des Empfängers seitens des Gebers andererseits. Schließlich ist es die Anerkennung des Gabentausches selbst, der sich nicht nur zwischen ihnen entwickelt, sondern auch auf das Kollektiv, auf ihre Familie, auf ihren Clan und auf ihr Dorf übergreift. Diese Einschreibung der Gaben in der ganzen Gesellschaft verpflichtet diese Gesellschaft zu neuen Gaben und neuen Zyklen des Gabentausches. Was zu dieser Einschreibung beiträgt, sind die materiellen und immateriellen Gegenstände, die gegeben werden und anschließend erwidert werden müssen. Beim Erwidern ist der Gegenstand deshalb wichtig, weil er den Beweis dafür liefert, dass ein Gabentausch stattgefunden hat. Der Gegenstand repräsentiert den Gabentausch, was Mauss mit der "Gewißheit" gleichsetzt, dass die Gabe tatsächlich erwidert wurde.[fn:132] Was und auf welche Weise im Gabentausch erwidert wird, bestimmt den Erwerb oder den Verlust seines Ranges, seiner sozialen Position sowie den Abschluss und die Eröffnung eines neuen Gabenzyklus. Mauss' Argument, das er in Unterstützung seines Ansatzes zum Zwangscharakter der Erwiderung der Gabe heranzieht, bezieht sich auf den Begriff des /hau/, auf den Geist des Gebers im gegebenen Gegenstand, der seine Rückkehr zum Geber verlangt und den Empfänger diskreditiert, wenn dieser den Gegenstand nicht erwidert. Im Vergleich zum /mana/ -- der Kraft des Gabentausches -- ist das /hau/ die "Kraft der Dinge",[fn:133], die ihre Rückkehr zum Geber fordern. Aber das hau ist nicht alles. Es gibt weitere Elemente, die dazu beitragen, das Erwidern der Gaben zu fördern und zu motivieren. Eines dieser Elemente betrifft die Verhältnisse zwischen den Akteuren und besonders die Art und Weise, wie sich das Geben und das Erwidern gegenseitig herausfordern. In diesem Zusammenhang bedeutet das Erwidern für einen Akteur, dass er in der Regel mehr zurückgeben muss, als er erhalten hat. Dies setzt ihn einerseits unter Druck, auch wenn dieser Druck andererseits im Erwidern gegen den Geber umgedreht werden kann. Diese Umkehr der Asymmetrie zwischen dem Geber und dem Akteur, der die Gabe erwidern soll, äußert sich darin, dass der Akteur in der Position des Erwiderns die Gabe häufig "mit Zinsen" erwidert,[fn:134] um den Geber gezielt zu erniedrigen, damit er sich verpflichtet, den Gabentausch fortzusetzen. So wird ein Zyklus des Gabentausches abgeschlossen und ein neuer eröffnet. Ein anderes Element, das zur Gewährleistung des Erwiderns der Gabe beiträgt, verweist demgegenüber auf das Verhältnis zwischen Akteur und Gesellschaft. Dieses Element vergegenwärtigt sich nach Mauss schon in den demonstrativsten Formen der Zerstörung von Vermögen im /potlatch/, die darauf hinweisen, dass hinter dem, was im Gabentausch zirkuliert, Institutionen wie der Totenkult oder das Gottesopfer stehen. Etwa im /kula/ ist es nicht möglich, Gegenstände unabhängig von den Kulten und Institutionen zu verwenden, mit denen diese Gegenstände verbunden sind, woraus Mauss schließt: "Den Lebenden geben heißt den Toten geben".[fn:135] Beim Erwidern der Gabe geht es deshalb nicht nur darum, die Gabe des Gebers auszugleichen. Es geht insbesondere darum, sich mit den gesellschaftlichen Institutionen in Verbindung zu setzen, mit denen ein Gegenstand assoziiert ist.

Das Erwidern im Gabentausch zeigt besonders deutlich, dass die Gabe nicht nur zur Behauptung von persönlichen und sozialen Identitäten, sondern auch zur Positionierung von Akteuren in der Gesellschaft und daran anschließend zur Hierarchisierung der Gesellschaft beiträgt. Dies gilt nicht nur für alten Gesellschaften oder Gesellschaften anderer Kulturen, sondern auch für unsere Gesellschaften. Die Gabe versteht Mauss entsprechend als Felsen ("roc") aller Gesellschaften.[fn:136]

** Die Gabe als Felsen aller Gesellschaften

Im Gabentausch werden nicht nur die Klassifikationsmuster von Gesellschaften deutlich, sondern auch, wie sie entweder zugunsten oder gegen die Akteure und Gruppen angepasst werden, die am Gabentausch teilnehmen. Der Gabentausch bestimmt sowohl den künftigen Gabentausch als auch die Art und Weise, wie dieser Austausch weitere gesellschaftliche Klassifikationen und Hierarchien hervorbringt, in denen wiederum Akteure und Gruppen eingeordnet werden. Im Gabentausch sieht man "Gesellschaften in ihrem dynamischen oder ihrem physiologischen Zustand".[fn:137] Beim Gabenzyklus kommt es zu einer Verhandlung gesellschaftlicher Hierarchien, aus der im Abschluss des Zyklus teilweise eine Rechtfertigung und teilweise eine Erneuerung der Gesellschaft resultiert. Deshalb gilt der Gabentausch nicht nur als Zirkulationsinstanz von materiellen und immateriellen Gegenständen, sondern auch als eine Verteilungsinstanz von Menschen, Dingen, Symbolen, Zeichen, Göttern usw. auf die Gesellschaft, die den Ausgangspunkt für die Erfahrung einer erneuerten sozialen Ordnung mit neuen Tauschmöglichkeiten darstellt, und die von der gegenseitigen Anerkennung, Legitimation und Zirkulation der Macht zwischen Akteuren/Gruppen abhängt. Zwischen Wirtschaft und Gesellschaft, Freiheit und Zwang, Eigennützigkeit und Uneigennützikgeit, entwickelt sich die Gabe nicht nur in segmentären Gesellschaften, sondern auch in unseren Gesellschaften. Die Gabe ist nicht nur eine Besonderheit ferner Gesellschaften und Kulturen. Mauss sieht in ihr vielmehr eine Alternative zur Veränderung der modernen Gesellschaften, weil die Gabe in ihren Wurzeln noch immer in unserer Gegenwart lebendig ist. Deshalb sollte sie in unseren rationalisierten, utilitaristischen und desillusionierten Gesellschaften als Tauschpraxis wieder aufgegriffen und im Zentrum des gesellschaftlichen Lebens platziert werden. Die Gabe enthält gleichermaßen eine Friedensbotschaft -- so geht es bei der Gabe zwar auch um Herausforderungen, Rache, Kämpfe und Machtverhältnisse, sie lässt sich jedoch keineswegs auf diese Ereignisse reduzieren. Grundsätzlich zielt sie darauf ab, das gesellschaftliche Band zu erneuern und weiterzuentwickeln. Wenn man gibt, gibt man nicht nur eine Ware oder eine Dienstleistung. Man gibt auch ein Stück von sich selbst.

Obgleich Mauss die Vielseitigkeit des Gabentausches aufzeigt und die Gabe als Konvergenzpunkt der Moral, der Wirtschaft, des Rechts, der Religion, der Magie, der Ästhetik, des Körpers, der Gefühle und der Emotionen bestimmt, lässt sein Essay doch Zweifel daran aufkommen, ob die Gabe wirklich dieser "roc", dieser Felsen der Gesellschaft ist. Mauss beschreibt die Gabe unter Rekurs auf das Vokabular indigener Bevölkerungen, deren Termini oft keine adäquate Übersetzung zulassen, was wiederum einer einseitigen Verwendung solcher Termini Vorschub leisten kann. Dies trifft im Besonderen auf die Verwendung des /mana/ und des /hau/ zu, auf die Mauss zur Beschreibung der Kraft der Gaben und des Geistes des Gebers im gegebenen Gegenstand rekurriert. In der Ethnologie hat dieser begriffliche Umgang Kontroversen ausgelöst.[fn:138] Mauss wird vorgeworfen, dass er diese Begriffe zu frei gedeutet habe. Beide Begriffe unterstützten eine Deutung der Gabe als einer gesellschaftlichen Tauschpraxis, die der Wirtschaft und dem wirtschaftlichen Tausch gegenüber immun wäre, was jedoch der Vorstellung einer Einbettung in der Gesellschaft entgegenlaufe. Sein engster Freund Hubert wirft ihm dies unmittelbar vor, als er 1925 /Die Gabe/ gelesen hat.[fn:139] In der Folge wird die Kritik geäußert, dass Mauss das obligatorische und daher reziproke Merkmal der Gabe überbetont habe, was zur Relativierung einer möglichen Verbindung zwischen der Gabe und der Idee einer moralisch tragfähigen Sozialwirtschaft in den Industriegesellschaften führe. Liegen in der Gabe tatsächlich die grundlegenden Normen unserer sozialen Verhältnisse? Oder zeigt die Gabe nur unsere blinde Idealisierung dieser Normen und entlarvt unseren Ethnozentrismus, wenn es darum geht, die verschiedenen Merkmale des sozialen und kulturellen Austauschs zu analysieren? Oder geht es noch um etwas anderes, wie Mauss' normative und politische Schriften nahelegen?

Am 11.05.1924 gibt es Parlamentswahlen in Frankreich, und die Sozialisten der SFIO nehmen an diesen Wahlen an der Seite der /Radicaux indépendants/, der /Parti républicain radical et radical-socialiste/, der /Parti républicain-socialiste/ teil. Es ist ein lockeres Wahlbündnis, das jedoch die Wahl gewinnt und Séverac wie Mauss in ihren Überzeugungen bestätigt. Besonders für Mauss bringt dieser Erfolg die Hoffnung mit, dass die Sozialisten verstanden haben, welche Einheit sie tatsächlich wollen, um Frankreich aus der finanziellen Krise auf dem Weg zum Bündnis mit den anderen Ländern Europas und darunter insbesondere Deutschland im Rahmen eines noch entfernten und idealisierten europäischen Verbandes zu führen. In dieser Zeit glaubt Mauss an die Verwirklichung eines anderen Sozialismus, die er fünf Jahre früher die Skizze in der Folge der britischen Reformen skizziert hatte, die seine Freunde Beatrice und Sidney Webb vorgeschlagen hatten, und die wie im Einklang mit den normativen Schlussfolgerungen von /Die Gabe/ kommen. In November 1920 berichtet Mauss über den Genfer Kongress der II. Internationale.[fn:140] In diesem Zusammenhang erwähnt er die Berichte über den von Sidney und Beatrice Webb Vorschlag einer Verfassung für die sozialistische Republik, die nach den Webb Großbritannien werden sollte. Mauss sieht dieser Vorschlag in direkter Verbindung zu den Äußerungen von Jaurès in /L'Armée nouvelle/ (1911),[fn:141] und auch in enger Verbindung mit seiner Vorstellung der Totalität, wie er sie in /Die Gabe/ vertreten wird: "Jetzt werden rechtliche und wirtschaftliche Formeln für die Totalität des sozialen Lebens angeboten, und diese Formeln sind sehr sozialistisch. Andererseits betreffen sie nur das Mögliche, das Unmittelbare, diese Dinge, die in das Gesetz aufgenommen werden können; morgen werden sie in England in das Gesetz aufgenommen, wenn die Labour Party mit Mehrheit die Macht legal beanspruchen wird".[fn:142] Und Mauss fährt begeistert fort: "Wir befinden uns nicht mehr nur im Bereich der Utopie oder der destruktiven Revolution. Wir befinden uns auch nicht mehr im Bereich der rein bürgerlichen Reformen. Hier liegt ein umfassender Plan für den Wiederaufbau des gesamten englischen Gesellschaftslebens vor. Es handelt sich hierbei nicht um ein Minimalprogramm. Der englischen Gesellschaft wird eine vollständige Veränderung des englischen Lebens zur Diskussion vorgeschlagen".[fn:143] Zu den Hebeln dieser Veränderungen gehört auch das Prinzip der Kommunalisierung von Ressourcen, darüber Mauss in seinen politischen Schriften in Anlehnung an die genossenschaftliche Organisation von Kommunen und Städten viel spricht. In diesem Zusammenhang hat Mallard mehrmals betont, dass Mauss /Die Gabe/ nicht nur in der Verlängerung seiner soziologischen Untersuchungen zum Opfers, zur Magie und zu den gesellschaftlichen Klassifikationssystemen situiert. Er versteht sie in sehr enger Verbindung mit seiner Vorstellung der Entwicklung der europäischen Nationen nach dem Ersten Weltkrieg, die vor der Herausforderung stehen, eine neuen Form der internationalen Allianz im Frieden zu gründen. Dabei geht es darum, die Idee von Gesellschaft auf einer neuen -- internationalen bzw. europäischen -- Ebene zu erneuern.[fn:144] Dies haben die Gesellschaften immer gemacht, als sie Krisen gegenüberstanden. Es ist undenkbar, dass die sogenannten modernen Gesellschaften dies nicht tun würden. Aber für Mauss, der bald 60 Jahre alt wird, ist diese Herausforderung umso schwieriger zu bewältigen, als die jüngere Generation, die ein solches Projekt übernehmen sollte, mehrheitlich im Krieg dezimiert wurde. Das ist nicht nur ein Problem angesichts der politischen internationalen Lage, sondern auch in Bezug auf die Ausbildung von den Menschen, die ein solches Projekt tragen würden. Mauss erlebt es im kleinen am Beispiel des eignen akademischen Kontextes.

** Mauss und die Reform des Hochschulsystems in Frankreich

Seit dem Ende des Ersten Weltkrieges machen sich die Stimmen laut, die Mauss darum bitten, das Projekt von /L'Année/ sociologique wieder aufzunehmen. Aber lohnt sich ein solches Unterfangen noch? Mauss denkt sich, dass er diese Frage mit Ja nur dann beantwortet, wenn /L’Année/ neu organisiert wird. Die Arbeitslast unter den Mitarbeitern muss besser aufgeteilt werden. /L’Année/ müsste kein Jahrbuch mutierende Zeitschrift mehr sein, sondern eine Fachzeitschrift, die zudem nicht nur für das Vorhaben der Durkheimianer werben sollte, sondern auch zum Fortschritt der Soziologie und der Sozialwissenschaften weltweit beitragen sollte. /L’Année/ müsste dann für Beiträge aus dem Ausland geöffnet werden. Mauss mobilisiert sein Netzwerk im Ausland, um Autoren für /L’Année/ zu gewinnen und die Arbeit an der Zeitschrift zu finanzieren. 1925 trägt er selbst am meisten zum ersten Band von /L’Année/ bei. Er schreibt einen Nachruf auf Durkheim und die im Krieg verstorbenen Mitarbeiter von /L’Année/. Er veröffentlicht in /L'Année/ /Die Gabe/. Er unterschreibt mehr als hundert Rezensionen und Besprechungen aus dem sich ausweitenden Feld der Sozialwissenschaften. Mauss ist wichtig, dass /L'Année/ nicht mehr wie die Kirche von Gefolgsmännern um ihren sakralen Anführer -- Mauss selbst -- aussehen müsste. Aufgabe der Zeitschrift sei es nicht, an den Geist einer Schule zu erinnern, sondern eine nützliche Arbeit für gegenwärtige und künftige Sozialwissenschaftler zu leisten. Deshalb ist es Mauss überaus wichtig, gute Beziehungen zu Wissenschaftlern der Psychologie, der Geschichte und der Ethnologie zu pflegen, deren wissenschaftlichen Fortschritte er bewundert. Diese Wissenschaften haben sich innerhalb von 25 Jahren sehr weit entwickelt und liefern der Soziologie nach Mauss' Dafürhalten ein gutes Beispiel des Weges, den die Soziologie ebenfalls beschreiten muss, um zu einer modernen Wissenschaft zu werden. Auch deshalb beschäftigt sich Mauss nach dem Ersten Weltkrieg nicht nur mit der Soziologie allein, die er weiter unterstützen will, sondern es geht um mehr bzw. um die französischen Sozialwissenschaften insgesamt.

Sie benötigen besser organisierte wissenschaftlichen Strukturen, wie etwa in den Vereinigten Staaten mit ihren neuen, von Stiftungen finanzierten und hoch technisierten Universitäten, die Mauss 1926 besucht und die ihn schwer beeindrucken.[fn:145] Es braucht nicht nur weitere wissenschaftliche Institute, die sich mit den Problemen der Zeit beschäftigen (der wirtschaftlichen Krise, dem Kolonialismus, der Entstehung von neuen politischen Ideologien). Mauss fordert zudem eine bessere Kommunikation zwischen den französischen Sozialwissenschaften und schlägt vor, sie an einem Ort, etwa an der Universität Paris Sorbonne, in benachbarten Gebäuden, unterzubringen und auf diese Weise die Bildung einer gemeinsamen Wissenschaftskultur zu unterstützen. Die Psychologie solle am dort ansässigen Institut für Psychologie gelehrt werden und das Institut für Ethnologie müsse ebenfalls dorthin verschoben werden. Auch ein Institut für Sozialwissenschaften müsse entweder an der Sorbonne eingerichtet, oder als eine sechste Sektion an der EPHE geschaffen werden.[fn:146] Mauss ist von seiner Idee so überzeugt, dass er sich mit der in Paris beheimateten Tochterstiftung der amerikanischen /Laura-Spelman-Rockefeller-Stiftung/ in Verbindung setzt, von deren finanzieller Macht er seit seiner Reise in die Vereinigten Staaten beeindruckt ist. Aber für die /Rockefeller-Stiftung/ ist Mauss' Vorhaben nicht konkret genug, weshalb sie sein Projekt im Gegensatz zu anderen konkurrierenden Projekten nicht unterstützt.

Zu dieser Enttäuschung kommen weitere unangenehme Ereignisse hinzu. Infolge der Veröffentlichung des ersten Bandes der neuen Reihe von /L’Année/ möchte Mauss die Zukunft der Zeitschrift und einen zweiten Band planen, weshalb er seine Freunde und einige Mitarbeiter von /L’Année/, z. B. Hubert, Bouglé und Fauconnet, kontaktiert. Sie antworten, dass sie nicht mehr mitmachen möchten. Mauss lässt sich dennoch nicht entmutigen und versucht seine Kollegen von der Bedeutung der Zeitschrift für die Sozialwissenschaften in Frankreich und weltweit zu überzeugen. Aber 1927 stirbt Hubert und mit ihm verlieren Mauss und /L’Année/ einen wertvollen Freund und eine außerordentliche Arbeitskraft. Mauss versucht aus eigener Kraft, die Essays für den ersten Teil des zweiten Bandes von /L’Année/ zu stemmen und Bibliographien zu bestellen, damit die Rezensionen zu den wichtigsten Neuerscheinungen verfasst werden können. 1927 erscheint der zweite Band von /L’Année/, aber er ist unvollständig. Im gleichen Jahr erfährt Mauss vom Tod Alice Hertz'. Weniger schlimm, aber nicht wirklich ermutigend, muss Mauss feststellen, dass die sozialistischen Bewegungen und die Zeitungen, die er unterstützt hatte, eine Entwicklung durchleben, die ihm immer fremder wird. Die Möglichkeit der Teilnahme an der französischen Regierung scheint den Sozialisten greifbarer wie nie, aber auch aus diesem Grund wachsen die Konflikten zwischen den Sozialisten, die sich gegenseitig versprechen, getrennte Wege zu gehen. Die Einheit, die sich Mauss wünschte und im Jahre 1924 fast verwirklicht wurde, ist wieder gefährdet. Ein einziges Ereignis gibt Mauss in diesen grauen Zeiten Hoffnung: Seine dritte Bewerbung auf eine Professur am /Collège de France/ hat diesmal geklappt, und mit der Unterstützung von Andler und seinen Freunden um die Überbleibsel der Durkheim-Gruppe wird Mauss am 03.02.1931 als Professor für Soziologie am /Collège/ vom Präsidenten der Französischen Republik Gaston Doumergue bestätigt. In dieser Rolle erscheint Mauss für seine Freunde immer mehr als der selbstverständliche Leiter der Durkheim-Schule neue Fassung, weshalb sie zu Mauss mit neuen Ideen kommen.

Célestin Bouglé, François Simiand und Halbwachs legen Mauss nahe, eine weitere Ausgabe von /L’Année/ in Angriff zu nehmen, die die neue Vision unterstützen würde, die Mauss von der Zeitschrift entwickelt hat. Die Zeitschrift muss die Fortschritte der Sozialwissenschaften weltweit abbilden und deshalb stärker internationalisiert werden. Zudem sollte sie nicht mehr /L’Année/ heißen, sondern am Vorbild ähnlicher Zeitschriften anderer Disziplinen /Les Annales sociologiques/. Halbwachs übernimmt die Leitung der Redaktion von /Les Annales/, und er bittet Mauss darum, zu sondieren, ob die /Rockefeller-Stiftung/ bereit wäre, /Les Annales/ zu finanzieren.[fn:147] Zwar erklärt sich die /Rockefeller-Stiftung/ zur Finanzierung bereit, möchte hierüber jedoch weniger mit Mauss allein als vielmehr mit den Institutionsleitern der Universität Paris verhandeln. Zudem signalisiert die Stiftung ihr Interesse daran, die Rubriken von /Les Annales/ mitzugestalten, um eine klare Verbindung mit den Sozialwissenschaften in den Vereinigten Staaten herzustellen. Mauss versteht, dass sich nicht nur das Bild der Soziologie verändert hat, sondern auch die Praxis in diesem Fach. Die Soziologie stellt sich immer weniger als eine allgemein-theoretisch orientierte und immer mehr als eine empirisch orientierte Wissenschaft dar, die soziale Probleme lösen und deshalb weiter professionalisiert werden sollte. Mauss teilt diese Vorstellung einer induktiv, normativ und praktisch orientierten Soziologie, weshalb er versucht, die französischen Sozialwissenschaftler unmittelbar in Verbindung mit ihren amerikanischen Kollegen zu bringen. Aber in dieser Zeit taucht ein unerwartetes Problem auf, dafür Mauss eine Lösung sucht. Dieses Problem kommt von Straßburg.

** Die Kompromisse um die Fortdauer einer soziologischen Tradition

Halbwachs, der den Lehrstuhl für Soziologie an der Universität Straßburg inne hat, überlegt seit 1930, Straßburg zu verlassen. In einem Brief vom 29.08.1930 kündigt Halbwachs Mauss bereits an: "Ich denke nur daran, eine mögliche Kandidatur an der Sorbonne nicht zu gefährden, falls Bouglé es schafft, dass man ihn von seiner Lehrtätigkeit entbindet".[fn:148] 1933 verwirklichte Halbwachs seinen Wunsch, näher an Paris heranzukommen, wenn er Simiand am /Conservatoire des Arts et Métiers/ vertrat.[fn:149] Die Frage seiner Nachfolge in Straßburg, die für Mauss und die Durkheim-Anhänger von entscheidender Bedeutung war -- Straßburg ist neben dem /Collège de France/ (Mauss) und der Sorbonne in Paris (Fauconnet) die einzige Universität in Frankreich, die einen Lehrstuhl mit der formalen Denomination Soziologie hat --, stellt sich als schwierig. Zunächst geht es darum, den Vorgaben treu zu bleiben, die sich die Universität 1919 bei ihrer Wiedereröffnung gesetzt hatte. Um weiterhin den Vergleich mit der alten deutschen Kaiser-Wilhelm-Universität Straßburg zu halten, ist ein renommierter Soziologe erforderlich. Diese erste Herausforderung gewinnt umso mehr an Bedeutung, als Mauss mit einem heiklen Problem konfrontiert ist. Mit dem Wechsel von Halbwachs in die Sorbonne würde die Durkheim-Gruppe einen Soziologie-Lehrstuhl verlieren, was den Ruf der Durkheimianer immer mehr trüben würde. Straßburg bleibt eine Hochburg der französischen Geistes- und Sozialwissenschaften, auf die alle Blicke gerichtet sind. Unter der Generation der Durkheim-Anhänger gibt es jedoch keinen Kandidaten, der die Nachfolge hätte antreten können. Wenn die Philosophische Fakultät der Universität Straßburg am 04.07.1935 einstimmig Georges Gurvitch "den einzigen Kandidaten" auf dem Lehrstuhl für Soziologie beruft,[fn:150] ergibt sich diese Wahl als Doppelzwang bzw. als "die Unmöglichkeit, auf einen Soziologieprofessor zu verzichten und einen anderen als [Gurvitch; CP] zu berufen".[fn:151]

Gurvitch lernt Mauss im April 1932 anlässlich einer Bewerbung als Dozent für die Sektion der Religionswissenschaften an der EPHE kennen.[fn:152] Mauss weiss wenig von ihm, den er als einen "Philosophen russischer Herkunft, der seit einigen Jahren mit den Durkheimianern in Verbindung steht" zu kennen glaubt.[fn:153] Bouglé und Fauconnet sind Mitglieder der Promotionskommission von Gurvitch, dem es gelingt, mehrere Soziologen für sein Institut für Rechtsphilosophie und Rechtssoziologie (IPDSj) zu gewinnen -- darunter neben Bouglé und Fauconnet auch Davy, René Hubert, Maxime Leroy, René Maunier und Mauss. Im Jahre 1934 ersetzt Gurvitch in Bordeaux Max Bonnafous, und er bietet Lehrveranstaltungen als Privat Dozent am /Collège Sévigné/ in Paris mit dem Ziel an, in der akademischen Welt in Frankreich sichtbar zu bleiben. Im April 1935 verschlechtert sich die Lage. Bonnafous überlegt, seine Stelle in Bordeaux wieder anzutreten, was Gurvitch in einen Zustand "unverzeihlicher Nervosität" versetzt: "Ich nehme bis heute Drogen, um schlafen zu können", gesteht er Mauss.[fn:154] Bonnafous trifft seine Entscheidung am 26. April, was für Gurvitch bedeutet, dass er zum 1. Mai aus dem Dienst entlassen wird. Er macht eine Depression, und die Symptome "einer Herzkrankheit, die sich nun sehr schmerzhaft bemerkbar macht", treten zum ersten Mal auf.[fn:155] Zwei Optionen stehen Gurvitch noch offen. Er kann sich auf den Lehrstuhl für Moral und Soziologie an der Philosophischen Fakultät der Universität Montpellier bewerben, oder er könnte sich auf den Lehrstuhl für Soziologie in Straßburg bewerben. Mitte Mai entscheidet sich jedoch die Philosophische Fakultät an der Universität Montpellier den Lehrstuhl für Moral und Soziologie umzustrukturieren, die zum Lehrstuhl für Geschichte der Philosophie wird. Gurvitch bleibt deshalb nur noch der Lehrstuhl in Straßburg. Mauss ist mit dieser Lage mäßig zufrieden. Gurvitch ist nicht wirklich Soziologe und auch nicht wirklich ein Anhänger der Durkheim-Gruppe. Zudem passt seine Bewerbung mit der Personalpolitik an der elsässischen Universität Straßburg nicht, die einer Logik der Opposition gegen Deutschland folgt und auf Assimilation der Elsässer ausgerichtet ist.

Deshalb ist es nicht überraschend, dass die literaturwissenschaftliche Fakultät in Straßburg auf Pierre Maxime Schuhl als Ersatz zu Halbwachs setzt. Als /agrégé/ aus dem Elsass passt er besser als Gurvitch im Bild, das sich die Kollegen an der Fakultät vom idealen Bewerber machen. Gurvitchs Einbürgerung allein, d. h. ohne die Russophobie einiger Kollegen in Straßburg dazu zu zählen, ausreicht, um geltend zu machen, dass er "nicht über die tief verwurzelte französische Kultur verfügt, die insbesondere an der Universität Straßburg unverzichtbar ist".[fn:156] Kann ein zuerst nach Deutschland emigrierter russischer Jurist den französischen nationalen Merkmale einer Denkschule -- der Durkheim-Schule -- und einer Disziplin -- der Soziologie -- entsprechen? Selbst Marc Bloch, der Gurvitch seine Stimme gerne geben würde, ist von dieser Nachfolge wenig begeistert: "Kein einziger junger französischer Soziologe, der diesen Platz einnehmen könnte! Finis Durkheimismi!".[fn:157] Gurvitch, der am 17.04.1929 eingebürgert wurde, wird in Paris höchstens als Ersatzmitarbeiter wahrgenommen, der mit öffentlichen französischen Ämtern nichts zu tun hat. Die Akademie von Straßburg folgt dieser Schätzung, und entsprechend reagiert der Germanist und Rektor Joseph Dresch, der keinen offiziellen Antrag an die Dienststellen von Elsass-Lothringen für die Wiederbesetzung der Professur für Soziologie stellt. Mauss interveniert persönlich in Unterstützung von Gurvitch, der zudem Glück im Unglück hat, weil in der letzten Minute Schuhl der Universität mitteilt, dass er seine Bewerbung auf den Lehrstuhl für Soziologie zurückzieht. Mit der starken Unterstützung von Halbwachs, der in dieser Zeit noch in Straßburg ist und mit der Unterstützung der Philosophen rechnen kann, um die literaturwissenschaftliche Fakultät davon zu überzeugen, dass Gurvitch die richtige Person für diesen Lehrstuhl ist, schreibt Mauss an den Dekan der Fakultät. In seinem Brief stellt er Gurvitch als der Philosoph und Rechtswissenschaftler, der sich "immer mehr unseren Methoden angenähert hat und (...) immer mehr zu dem Soziologen geworden ist, der er implizit war".[fn:158] Und Mauss argumentiert weiter: "dieser ausgezeichnete Kandidat [ist] der einzige junge französische Soziologe, der einer so wichtigen Position würdig ist".[fn:159] Um Gurvitchs neuen Titel als französischer Soziologe zu untermauern, organisiert Mauss mit Halbwachs Ende Mai 1935 die Ausschreibung einer Mitgliedschaft am /Institut français de Sociologie/, darauf sich Gurvitch so schnell wie möglich bewerben sollte. Empfehlungsschreiben bekommt er sofort u. a. von Lévy-Bruhl, Bouglé, Fauconnet und Mauss, und der Bericht von zwanzig Zeilen, der über die Verdienste Gurvitchs in der Soziologie verfasst werden muss, muss Gurvitch selbst übernehmen.

Parallel dazu wird auch Mauss mit der Unterstützung von Halbwachs auf höchster Ebene aktiv. Um den Hindernissen und Verzögerungen der Behörden von Elsass-Lothringen entgegenzuwirken, wenden sie sich zunächst an das französische Bildungsministerium und plädieren für eine Reduzierung vom Aufgabenpensum Gurvitchs auf dem Lehrstuhl für Soziologie. Gurvitch sollte lediglich "Dozent in Ausbildung sein, der für die Vertretung von Herrn Halbwachs zuständig ist (...). Mit dieser Lösung würde Herr Gurvitch kein Status als Beamte bekommen, was die Behörden von Elsass-Lothringen von der Verantwortung für diese Ernennung entbinden würde, die dann rechtlich unangreifbar wären".[fn:160] In Begleitung der Philosophen -- darunter Charles Blondel, Martial Guéroult und Maurice Pradines -- übt Halbwachs Druck auf Dresch und auf den Dekan der literaturwissenschaftlichen Fakultät in Straßburg aus, um "die Bedingungen zu präzisieren, unter denen [sie] die schnellstmögliche Ernennung [Gurvitchs] zum Delegierten beantragen [sollen]".[fn:161] Die formellen Erwartungen der Durkheimianer und die wirtschaftlichen Erwartungen Gurvitchs ergeben eine Kompromisslösung, die für Gurvitch jedoch einen bitteren Beigeschmack hat. Einerseits sinkt sein Gehlat von 43.000.- Francs zu 28.000.- Francs jährlich. Andererseits ist seine Stelle befristet. Im besten Fall kann Gurvitch damit rechnen, dass er von Jahr zu Jahr verlängert wird. Diese prekäre Lage geht bis 1939 weiter, bevor Gurvitch mit den Anmarsch der Nazi auf Paris Frankreich für die Vereinigten Staaten verlassen muss.

Trotz seiner interessierten Unterstützung ist und bleibt Gurvitch für Mauss kein Soziologe. Mauss sagt es ihm unmittelbar, wenn Gurvitch, der 1936 einen Essay zu Soziabilitätsformen vorbereitet (mit dem Titel /Essai d’une classification pluraliste des formes de la sociabilité/), damit er davon überzeugt ist, "dass er das soziologische Denken von Grund auf erneuert hatte",[fn:162] nach seiner Meinung zu diesem Essay fragt. Mauss antwortet mit deutlichen Wörtern: "Diese ganze Einleitung, die dazu führt, dass wir endlos und von Meinungen zu Meinungen Menschen von so unterschiedlichem Wert diskutieren, die jedoch für diesen Anlass auf der selben Ebene behandelt werden, wie Durkheim auf der einen Seite und Max Weber und alle Schellers dieser Welt auf der anderen Seite, hat nur rein dialektisches Interesse. (...) All dies zeugt von einer immensen Gelehrsamkeit, deren Interesse für andere Philosophen ich nicht leugne, die aber, weil sie keinen heuristischen Wert hat, auch von keiner wissenschaftlichen Bedeutung ist".[fn:163] Nicht nur mit der Dialektik Gurvitch und seiner aus den deutschen Sozialwissenschaften inspirierten Erkenntnistheorie hat Mauss Schwierigkeiten, sondern auch mit Studierenden, die in ihm einen Anführer sehen und seine Erbschaft weiter entwickeln wollen, in der sich Mauss nicht wieder erkennt. 1938 wird Mauss zum Präsidenten der Sektion der Religionswissenschaften an der EPHE und empfängt immer mehr Studierende, die seine Lehrveranstaltungen besuchen, seine Vorträge hören möchten oder ihm Dissertationsprojekte vorschlagen. In diesem /âge d’or/ der französischen Ethnologie und ihrer Institutionen begleitet Mauss die Arbeiten vieler junger Ethnologen. Er unterstützt die Gründung eines nationalen Forschungszentrums in Frankreich (/Centre national de la recherche scientifique/ oder CNRS, 1939), das für eine bessere Ausstattung der wissenschaftlichen Forschung in Frankreich sorgen und diese Forschung weiter profilieren soll. Entsprechend wirkt Mauss unterstützend bei der Initiative von Georges Bataille und einigen seiner Studierenden mit, die 1937 das /Collège de sociologie/ in Annäherung an Mauss und nach dem Vorbild des soziologischen Programms von Durkheim und den Durkheimianern gründen.[fn:164] Jedoch bleibt er skeptisch in Bezug auf die Art und Weise, wie das /Collège de sociologie/ die Soziologie und die Ethnologie versteht und an der Profilierung dieser Disziplinen arbeiten will. Nach Mauss' Ansicht vermischen die Mitglieder des /Collège/ die Existenzphilosophie Martin Heideggers mit der Soziologie des Sakralen, die dem Fortschritt der Sozialwissenschaften nicht wirklich dient. Doch auch wenn Mauss seinen Studenten nicht in all ihren Überlegungen zustimmt, so entscheidet er sich im Jahr 1939 seine Stelle an der /Ecole pratique/ aufzugeben, was ihm u. a. erlauben würde, dieses Projekt von einem Ende zu bringen, davon er seit dem Ende des Ersten Weltkrieges spricht -- die Nation.

** Die Nation und die unvollendete Theoretizierung eines sozialistischen Engagements

Als Sozialist schlägt Mauss eine Reorganisation der Wirtschaft und Finanzwirtschaft mit dem Ziel vor, die öffentlichen Finanzen zu stabilisieren und so den Wohlstand aller europäischen Bürgern abzusichern. Nach Mauss hat der Kapitalismus maßgeblich zum Ersten Weltkrieg beigetragen und muss entsprechend verändert werden. Eine solche Umstrukturierung erfordere die Institutionalisierung von Genossenschaften auf staatlicher Ebene. Oder anders formuliert: Die Umstrukturierung der Wirtschaft durch die Genossenschaftsidee setzt eine entsprechende Umstrukturierung des Staates. Damit wäre eine Entscheidungs- und Regulierungsmacht in der Gesellschaft tatsächlich in der Lage, diese Gesellschaft auf die nächste Stufe ihrer Entwicklung vorzubereiten, die nach Mauss in der unvermeidlichen Allianz mit anderen Gesellschaften auf internationaler Ebene besteht. Nach Mauss bedeutet eine solche korrespondierende Umgestaltung von Wirtschaft und Politik in der Gesellschaft die Strukturierung von diesen Gesellschaften auf der Grundlage von Verbänden nationaler Genossenschaften. Diese Botschaft entwickelt Mauss in seiner unvollendeten Schrift /Die Nation, oder Der Sinn fürs Soziale/.

Im Gegensatz zu Durkheim versteht Mauss den Staat nicht als Garant der gesellschaftlichen Einheit. Aber ebenso wie Durkheim betont auch Mauss die Wichtigkeit von intermediären Gruppen bzw. von Berufsverbänden, die Durkheim als neue Zünfte fasst, während sie von Mauss nach dem Vorbild des kooperativen Sozialismus als Genossenschaften bezeichnet werden. Ob Zünfte oder Genossenschaften, Mauss ist davon überzeugt, dass nur derartige intermediäre Gruppen tatsächlich in der Lage sind, einen sozialen Wandel zu realisieren und moderne Gesellschaften zu sozialistischen Gesellschaften zu verändern. Dieses erste Argument geht quer durch Mauss' Schriften über die Nation: Die Nation ist nicht der Staat, sondern sie hat sich gegen ihn entwickelt.[fn:165] Die Internationalität ist das zweite Argument, das Mauss in Bezug auf die Nation vorbringt und ihn deutlich von Durkheim unterscheidet: Jede Gesellschaft entwickelt sich international, was nicht mit dem Kosmopolitismus zu verwechseln ist, womit Mauss die deregulierten Tätigkeiten von (Finanz)Kapitalisten meint. Das Problem der Währungs- und Schuldenkrise verdeutlicht dies in prägnanter Art und Weise. Eine Nation ist auf ihre internationale Umgebung angewiesen, denn nichts, was die inneren Angelegenheiten einer Gesellschaft betrifft, kann sich nur auf diese Gesellschaft allein beziehen. Alles, was sie betrifft, beeinflusst auch die Gesellschaften, die sie umgeben und mit denen sie unmittelbar oder mittelbar in Verbindung steht. Die Krise der französischen Währung nach dem Ersten Weltkrieg ist nicht nur das Ergebnis der Inflation und der schlechten Verwaltung der Staatsschulden. Sie ist das Ergebnis einer schlechten internationalen Politik.

Statt wie Durkheim mit dem Staat und dem Druck von intermediären Gruppen auf den Staat zu rechnen, um die moderne Gesellschaft zu reformieren, rechnet Mauss mit nicht-staatlichen Initiativen und Organisationen, deren Vorbild die (Konsum)Genossenschaften sind. Dabei ist er nicht der Einzige, der ein solches Argument unterstützt. Albert Thomas zum Beispiel, ein Freund von Mauss und Durkheim, engagiert sich ebenfalls in der Genossenschaftsbewegung, was ihn dazu führt, die /Internationale Arbeitsorganisation/ (IAO) zu gründen. Selbst wenn die IAO eher zu einer intermediären Organisation weiterentwickelt wird,[fn:166] bleibt sie doch den von Mauss mit den sozialistischen Genossenschaften verbundenen erzieherischen Merkmalen treu, die Maurice Colombain nach Thomas an der Leitung der IAO besonders lobend hervorhebt. Bereits in den 1950er Jahren macht Colombain die Genossenschaften zum Prinzip der Erziehung durch wirtschaftliches Handeln. Genossenschaften erziehen nicht nur zur Demokratie, sondern auch zur Demokratisierung der Wirtschaft, weil sie die Freiheit der Einzelinitiative mit einer möglichst direkten Beteiligung der Bürger an wirtschaftlichen Entscheidungen verbinden und zum Nutzen der Gemeinschaft bereitstellen.[fn:167] Anhand von einer organischen Metapher -- Genossenschaften sind, so Colombain, "nicht mehr nur Zellen, sondern Organe, notwendige Organe des demokratischen Gesellschaftskörpers"[fn:168] -- stellt Colombain dar, dass Genossenschaften, wie von Mauss vorgeschlagen, föderal strukturiert werden sollten. Ein solcher Verband sollte nicht nur auf nationaler Ebene stattfinden, sondern auch international verbreitet werden. Die Genossenschaftsbewegung unterscheidet sich jedoch von anderen Bewegungen, die eine Internationalisierung anstreben, wie etwa dem Marxismus, dem Kommunismus oder dem Sozialismus. Nach Gide besteht die Besonderheit dieses genossenschaftlichen Internationalismus darin, dass er eng mit den Ideen von Heimat und Nation verbunden bleibt: "Wem gehört das Vaterland? Macht man es zum Erbe der Bourgeoisie? Wollt ihr ihr, nachdem ihr ihr vorgeworfen habt, alle Güter dieser Welt zu monopolisieren, auch noch das Monopol auf all die unschätzbaren Güter überlassen, die das Wort ‚Heimat‘ verkörpert? (...) Nein! Wir wollen nicht, dass unsere Internationale sich anmaßt, unser Vaterland zu verleugnen. Wir halten die Unterscheidung zwischen den Nationen nicht für überflüssig".[fn:169] Für Gide ist der Rekurs aufs Vaterland nicht zu verwechseln oder gar gleichbedeutend mit Nationalismus. Im Gegenteil. Er unterscheidet vielmehr den Internationalismus der Genossenschaften, verstanden als Internationalismus der Nationen, vom Internationalismus der anderen Bewegungen. Mauss' Auffassung vom Internationalismus und von der Nation geht in eine ähnliche Richtung.

Nach Mauss symbolisiert "d[ie] Heimat bzw. d[as] Vaterland (...) alle Pflichten, die die Staatsbürger gegenüber der Nation und ihrem Grund und Boden besitzen".[fn:170] Er verbindet die Heimat bzw. das Vaterland mit dem Völkerrecht als Grundlage der Nation.[fn:171] Ohne institutionalisiertes Völkerrecht, das dem Einzelnen Rechte an allen öffentlichen Gütern gibt, ist die Nation nur eine Idee und keine konkrete Realität. Dasselbe gilt für die Verbindung zwischen Heimat/Vaterland und Staatsbürger, "denn im Grunde genommen sind die beiden Begriffe des Vaterlandes und des Staatsbürgers Auswuchs ein und derselben Institution, ein und derselben praktischen und ideellen moralischen Norm und in Wahrheit ein und derselben ausschlaggebenden Tatsache".[fn:172] Mit dieser Verbindung zwischen Heimat/Vaterland, Staatsbürger und Nation gelangt Mauss zu einer ersten Definition der Nation als Gesamtheit der Bürger und damit als Heimat: "In einem gewissen Grade ist die ganze Gesellschaft, die Gesamtheit aller Bürger zum Staat als souveräner politischer Körperschaft geworden. Genau dies nennt man Nation".[fn:173] Die Nation setzt mehrere Merkmale voraus, von denen jedoch vier von besonderer Wichtigkeit sind. Erstens ruht eine Nation auf einer ausreichend integrierten Gruppe von Staatsbürgern. Zweitens leben diese Bürger in einer mehr oder weniger demokratischen Ordnung mit individuellen Rechten. Drittens können sie diese Rechte besitzen und souverän ausüben, was ihnen das Gefühl der Zugehörigkeit zu einer Nation vermittelt, woraus sich in der Folge die nationale Souveränität ergibt. Und schließlich wird diese nationale Souveränität und damit die Nation so weit verbreitet, wie der Nationalcharakter, d. h. das, was die Bürger einer Nation kennzeichnet, wie die gemeinsame Sprache, Moral und Zivilisation, verbreitet ist. Diese vier Merkmale vertiefen wir im Folgenden.

Das erste Merkmal, das von Brubaker gut hervorgehoben wurde, bezeichnet die Nation als integrierte Gruppe von Bürgern.[fn:174] Damit will Mauss sagen, dass eine Nation ein mehr oder weniger entwickelter Prozess innerhalb von Gesellschaften darstellt. Diese Entwicklung hängt davon ab, ob sich die Einzelakteure über das Kollektiv, das sie bilden, bewusst sind bzw. ob sie verstehen, dass sie ein Kollektiv bilden und diesem angehören. Dieses Bewusstwerden steigt umso mehr, als es weniger Vermittler zwischen den Einzelakteuren und dem Kollektiv gibt, was zur Verbreitung der Nation in der Gesellschaft beiträgt.

Das zweite Element dieser Definition ist die Demokratie im Sinne individueller Rechte, die die Einzelakteure besitzen und souverän ausüben können. Fournier und Terrier weisen darauf hin, dass sich "Mauss weniger für die Demokratie als für die Demokratisierung [interessiert]",[fn:175] wobei die Demokratisierung als die Verbreitung der nationalen Souveränität auf die Bevölkerung verstanden wird. In einer Nation geht es darum, dass so viele Bürger wie möglich von dieser Souveränität unterstützt werden und sie entsprechend weiter ausbauen. Nach Mauss haben die Sozialisten in den modernen Gesellschaften die Demokratisierung bzw. die "Emanzipationsbewegung von Nation und Bürger" gefördert,[fn:176] was zeigt, dass Mauss ein spezielles Verständnis von Demokratie besitzt, das nicht mit der bürgerlichen Demokratie, die aus der Französischen Revolution hervorgegangen ist, in eins zusammenfällt.[fn:177] Es handelt sich auch nicht um die Arbeiterdemokratie der Marxisten oder der Kommunisten, die Mauss nur als Teil seines Demokratieverständnisses betrachtet. Mauss’ Auffassung von Demokratie stimmt auch nicht mit der der Gewerkschaften überein, die oft nur eine auf einzelnen sozialen Klassen basierte Auffassung der Demokratie unterstützen, deren Interessen sie verteidigen. Schließlich handelt es sich auch nicht um die "direkte, unorganische Demokratie mit imperativen Mandaten, nicht haftenden Generalversammlungen, Überwachungsorganen" und "Schikanen".[fn:178]. Die Demokratie, von der Mauss spricht, die "démocratie profonde“,[fn:179] findet ihr Vorbild in der "Verbraucherdemokratie",[fn:180] die mittels der Konsumgenossenschaften entwickelt und verbreitet wird. Diese Verbraucherdemokratie bedeutet für Mauss "die Vorstellung einer Versicherung aller durch alle, jedes Einzelnen durch alle, die der Vorstellung von Demokratie zugrunde liegt und die ich die auf Wechselseitigkeit beruhende Demokratie nennen werde",[fn:181] wovon auch die Webbs, schon sprachen. Nach Mauss berücksichtigt diese Art von Demokratie die Interessen der einzelnen Verbraucher und damit die gemeinsamen Interessen aller Bürger. Oder anders gesagt: Das Vorbild der Demokratie, das durch Konsumgenossenschaften eingeführt wird, dient dem allgemeinen Interesse, das Mauss als "Summe der Privatinteressen" versteht.[fn:182] Es führt zu einer Nation, die sowohl auf wirtschaftlicher als auch auf rechtlicher Ebene verwirklicht wird.

Tatsächlich fördert diese auf Wechselseitigkeit beruhende Demokratie nach Ansicht von Mauss die gegenseitige Stärkung sowohl der Wirtschaft als auch des Rechts: "Die Entwicklung des öffentlichen Rechts hängt nämlich von der wirtschaftlichen Lage der Gesellschaft ab und umgekehrt: Der Prozess, durch den sich die Nationen bildeten, war einerseits ein ökonomischer und andererseits zugleich ein moralisch-juristischer Prozess".[fn:183] Mauss spricht jedoch der Wirtschaft eine führende Rolle bei der Verwirklichung der Nation in den Gesellschaften zu. Die Wirtschaft habe sich vom Geschäft in den Städten befreit. Sie wurde auf die gesamte Gesellschaft verbreitet und stellt daher das Modellbeispiel dessen dar, was Mauss mit dem Terminus "Nationalisierungsprozess" bezeichnet und was er unter diesem Prozess verstanden wissen möchte. Zwar ließe sich, so Mauss, behaupten, dass die modernen Gesellschaften wirtschaftlich voneinander unabhängig bleiben, weil jede Gesellschaft eine Art von Protektionismus bzw. "eine wahrscheinlich pathologische (...) Form" der nationalen Wirtschaft praktiziert.[fn:184] Mauss sieht diesen Protektionismus aber gleichsam als eine notwendige Stufe der Wirtschaftsentwicklung, die alle Nationen durchlaufen müssen, um auf der internationalen Ebene weiterentwickelt zu werden. Eine solche Entfaltung und Ausgestaltung der Wirtschaft ausgehend von der nationalen zur internationalen Ebene bildet für Mauss das Ideal, das alle Nationen gleichermaßen anstreben und verfolgen: "[es gibt] in Bezug auf Industrie, Ökonomie und Finanzen bereits ein Nationenideal und (...) dieses Ideal [ist] innerhalb der zivilisierten Menschheit bereits so weit verbreitet, dass die Nationen in dieser Hinsicht höhere Ansprüche an die anderen Nationen stellen als an sich selbst".[fn:185]

Der Internationalismus der Nation begünstigt ihre Selbstorganisation und ihre Autonomie im Spiel der internationalen Beziehungen mit anderen Nationen. Dabei kommt dem Kapitalismus trotz Mauss’ scharfer Kritik eine Führungsrolle zu, weil er die Nationen diesem Ideal Schritt für Schritt näher bringt. Aber die zeitgenössische Form des Kapitalismus muss unbedingt überholt werden, weil die Nationen andernfalls die Stufe ihrer Internationalisierung nicht zu erreichen imstande sind. Entsprechend lässt sich diese Stufe der Internationalisierung nach Mauss nur realisieren, wenn ihre wirtschaftlichen Tätigkeiten und Tätigkeitsbereiche im Zeichen und vom Standpunkt einer kollektiven Verwaltung von Wirtschaftsgütern und Dienstleistungen entwickelt werden. Eine solche Entwicklung würde nicht nur die Wirtschaft stärken, sondern auch zur Stärkung des Rechts maßgeblich beitragen.

Die wechselseitige Einflussnahme zwischen Wirtschaft und Recht bedeutet jedoch auch, dass in denjenigen Nationen, wo die wirtschaftliche Entwicklung schwach ausgebildet ist, auch das öffentliche und das private Recht sowie das Völkerrecht, welches aus Sicht von Mauss von besonderer Wichtigkeit ist, weil es für ihn "die Idee einer von den Nationen gebildeten egalitären Gesellschaft" symbolisiert,[fn:186] schwach bleiben. Deshalb muss auch das Recht in Form des Völkerrechts weiterentwickelt werden, damit sowohl das öffentliche als auch das private Recht der Nationen Fortschritte machen. Ein solcher Fortschritt setzt die Preisgabe des Begriffs des souveränen Staates voraus, um die Verwaltung der wirtschaftlichen und rechtlichen Angelegenheiten und damit die Verwaltung von Verträgen und Rechten in die Hände der „Verbraucher“ bzw. der in Genossenschaften organisierten Verbraucher zu legen. Unter dem Einfluss des wirtschaftlichen Fortschritts bei der Überwindung des Kapitalismus einerseits und des rechtlichen Fortschritts bei der Entwicklung des privaten und öffentlichen Rechts sowie des Völkerrechts andererseits können also nach Mauss die zeitgenössischen Gesellschaften als Nationen verwirklicht werden.

Eine solche Verwirklichung bezeichnet Mauss mit den Begriffen "Internationalismus" oder "Inter-Nation", womit er "die Bewegung" apostrophiert, "[die] die Vereinigung der Nationen [anstrebt]" und nicht etwa, wie Mauss ausdrücklich hinzufügt, "ihre Zerstörung".[fn:187] Zwar hat die Nation Grenzen, die Mauss durch die Erwähnung symbolischer (Sprache, Bräuche) und institutioneller oder organisatorischer Merkmale (Künste, Techniken, Industrien) klar definiert. Nichtsdestotrotz ist die Nation aber auch als eine Bewegung zu verstehen, weil sie sich stets in Wechselbeziehungen zu anderen Nationen befindet. Die Aufrechterhaltung dieser Beziehungen erfolgt durch "eine Menge sozialer Kräfte, die danach streben, das Zusammenleben der Gesellschaften praktisch und moralisch zu regeln",[fn:188] d. h. durch die Bürger, die die "Verbraucher" der Nation sind. Entsprechend ist die Nation in der Interdependenz der Nationen für Mauss nur dann vollständig verwirklicht, wenn ihre Bürger sie nach den genossenschaftlichen Prinzipien nutzen. In diesem Sinne stellt die Nation also keineswegs eine utopische Realität dar, sondern vielmehr eine zeitgenössische Tatsache im Werden: "Politisch und moralisch noch wichtiger ist, dass diese wechselseitige Abhängigkeit von den Völkern selbst erkannt, empfunden und gewollt wird. Die Völker hegen ganz klar den Wunsch, dass dieser wechselseitigen Abhängigkeit gesetzlich, in einem kodifizierten, sanktionierten, öffentlichen und privaten Völkerrecht Ausdruck verliehen wird. In diesem Punkt sind die Völker ihren Führungen voraus".[fn:189]

Das Ende des Ersten Weltkriegs und die Gründung des Völkerbunds im Rahmen des Versailler Vertrags im Jahr 1919 zeigt nach Mauss deutlich, dass die Entwicklung der Nation in den zeitgenössischen Gesellschaften mit der Motivation der Bürger rechnen kann, die nicht mehr den Krieg wollen, sondern sich für Frieden, gegenseitigen Austausch und gegenseitige Unterstützung aussprechen. Aber nicht nur die Ablehnung des Krieges begründet eine solche Motivation seitens der Bürgerschaft. Die vom Sozialismus initiierten sozialen Bewegungen und selbst der Marxismus sowie der Kommunismus haben zudem die Grundlage für die Entstehung dieser Motivation bereitgestellt, indem sie zur Organisation der Arbeiterklasse und zur Aufklärung der Arbeiter entscheidend beigetragen haben. Die sozialen Bewegungen und unter ihnen insbesondere die Arbeiterbewegungen, haben den Weg für ein Bewusstsein des Kollektivs gebahnt, das auf alle Akteure der Gesellschaft unabhängig von ihrer Klassenzugehörigkeit oder Herkunft offen war und so über die gesamte Gesellschaft hinweg Verbreitung fand. Die Nation und ihre internationale Reichweite entstehen daraus bzw. sie entstehen aus diesen sozialen Bewegungen von unten, ausgehend von den unprivilegierten sozialen Gruppen der Gesellschaft.


** Schlusswort

Mauss' normative Schriften und sein Werk La nation beschreiben insgesamt die Einschreibung des Kollektivs in das Individuum durch Erziehung und Sozialisation. Diese Sozialisation begünstigt die Emanzipation des Individuums und des Kollektivs im Sinne gegenseitiger Wechselbeziehungen und gegenseitiger Unterstützung zwischen Akteuren bzw. zwischen Nationen. Diese Wechselbeziehungen zwischen Einzelakteuren und Kollektiven bilden eines der Hauptmerkmale, die Mauss' wissenschaftliches und politisches Vorhaben eint. In seinen normativen Schriften und in /La nation/ wird dieses Merkmal wie folgt präzisiert: Sozialistische Genossenschaften unterstützen und organisieren diese Wechselbeziehungen am besten. Sie sind deshalb eine glaubwürdige, praktische Alternative zu den verschiedenen Arten des Sozialismus in Form von in Verbänden organisierten Konsumgenossenschaften auf nationaler und internationaler Ebene. So spiegelt die Nation strukturell die Organisation einer genuin sozialen Gesellschaft wider, in die alle Gesellschaften münden. Seit der Englischen, Amerikanischen und der Französischen Revolution und seit der Entwicklung von demokratischen Gesellschaften ist die Nation konkreter geworden. Es gehört zu den Aufgaben von Gesellschaften nach dem Ersten Weltkrieg, diesen Prozess nun zu vervollständigen.

Die Tatsache, dass nach Mauss die Nation in unseren Gesellschaften unvollendet bleibt, bedeutet, dass unsere Gesellschaften immer noch nach einer sozialen Form suchen, die die Einschreibung des Kollektivs in das Individuum ermöglicht und verbessert. Dies kann nur durch die Überwindung des Kapitalismus in der Wirtschaft und durch die Stärkung des Völkerrechts im Bereich des Rechts erreicht werden. Ohne eine solche vollständige Konkretisierung der Nation sind Krisen und Konflikte innerhalb und zwischen Gesellschaften unvermeidlich und führen auf mikrosozialer Ebene zur Gefährdung der Vergesellschaftung von Einzelakteuren mit Kollektiven, was unweigerlich die Fortdauer von sozialen und kulturellen Ungleichheiten zwischen Akteuren, Kollektiven, Gesellschaften und Kulturen zur Folge hat, die statt gemeinsamer Interessen nur noch eigene Interessen verteidigen. Sind unsere Gesellschaften in der Lage, eine solche Form des Zusammenlebens zu entwickeln, oder muss man vielmehr davon ausgehen, dass sich den Gesellschaften diese Form des Zusammenlebens entzieht, wie Mauss vor allem mit Blick auf das Aufkommen des Faschismus in Italien und das national-sozialistische Regimes in Deutschland um die 1930er Jahre befürchtet?

1934 heiratet Mauss -- heimlich -- die 14 Jahre jüngere Marthe Rose Dupret, mit der er seit Anfang der 1920er Jahre liiert ist. Diese Hochzeit, von der selbst Mauss' engen Freunde nichts wissen, überrascht und erfreut letztere zugleich. Aber 1935 findet Mauss Marthe bewusstlos in ihrer Wohnung, in der Mauss einen starken Gasgeruch wahrnimmt. Die ersten Hoffnungen auf eine verhältnismäßig schnelle Genesung werden enttäuscht. Marthe bleibt schwach und darf die meiste Zeit das Bett nicht verlassen. Seitdem muss sich Mauss um den gesundheitlichen Zustand seiner Frau kümmern, auch wenn er beruflich zunehmend Verantwortung trägt. 1939 gibt Mauss seine Stelle an der EPHE auf. Er will mit dieser Entscheidung Platz für jüngere Wissenschaftler schaffen, damit sie ihre Projekte weiter entwickeln können. Einige dieser jungen Wissenschaftler sind im Ausland und berichten Mauss nicht nur von der Möglichkeit, nach Frankreich zurückzukehren, um sich auf eine vakante Stelle zu bewerben. Sie berichten ebenfalls von gegenwärtigen politischen Entwicklungen, die zu der Vermutung Anlass geben, dass ein weiterer Krieg in Europa bevorstehen könnte. Infolge des Münchner Abkommens (1938) -- dem großen politischen Erfolg des Dritten Reichs in Deutschland -- rechnen viele damit, dass Adolf Hitler den Plan verfolge, im Geheimen einen Krieg vorzubereiten. Zunächst beruhigt Mauss seine Studierenden und Freunde. Im Moment sei die Lage ruhig, was zwar nicht bedeute, dass die Lage so ruhig bleibe, aber noch gäbe es keinen Grund, das schlimmste zu befürchten.

1940 marschieren die Nationalsozialisten jedoch in Paris ein. Mauss, dem sich die Möglichkeit geboten hatte, mit seiner Frau in die Nähe von Toulon zu reisen, bleibt schließlich mit ihr in Paris, da sie sich noch weniger als er eine solche Reise wünscht. Die Situation in Paris verschärft sich im Laufe der Wochen immer weiter. Die ersten Juden in der Stadt werden verhaftet. Mauss gibt im Jahr 1939 seine Funktion als Präsident der V. Sektion der Religionswissenschaften auf, damit die EPHE nicht darunter leiden muss, dass sie einen Juden in ihrer Belegschaft hat. Im Jahr 1940 kündigt er aus dem gleichen Grund seine Stelle am /Collège de France/. Seine Verwandtschaft in den Vogesen und seine Freunde und Bekannten in Paris werden unter der Vichy-Regierung mit Berufsverboten belegt. Mauss und seine Frau müssen ihre Wohnung verlassen, die von einem deutschen General übernommen wird. Sie werden in Paris in einer sehr kleinen Wohnung ohne funktionierende Heizung untergebracht. Die Jahre zwischen 1941 und 1943 sind die schwierigsten Jahre im Leben von Mauss. Er muss den gelben Stern tragen. Er hat viele Schwierigkeiten Lebensmittel für sich und seine Frau zu besorgen. Er bleibt jedoch am Leben, auch dank der passiven Unterstützung von Bekannten und ehemaligen Freunden in der Verwaltung, die versuchen, die Nationalsozialisten und die Vichy-Regierung nicht auf ihn aufmerksam zu machen. Als Paris im Laufe des Jahres 1944 befreit wird, haben Mauss und seine Frau überlebt. Sie beziehen wieder ihre ehemalige Wohnung und Mauss wird zum Honorarprofessor am /Collège de France/ ernannt.

Viele seiner Studierenden und Freunde, die ins Ausland geflüchtet sind, kehren aus ihrem Exil zurück und wollen ihn sehen. Gurvitch, der aus den Vereinigten Staaten zurückreist, will Mauss unbedingt bei der Gründung des /Centre d’études sociologiques/ und der Zeitschrift des /Centre/, den /Cahiers internationaux de sociologie/, involvieren. Viele erkundigen sich nach den Projekten, die nun anstehen -- etwa nach der Veröffentlichung von Huberts Werken zu den Kelten und den Germanen, nach Mauss' eigenen Untersuchungen zu den Mythen Australiens und selbstverständlich nach /L’Année/, von der sich viele weitere Publikationen wünschen. Aber Mauss antwortet nicht. Der Krieg hat ihn gezeichnet und krank gemacht. Er erkennt die Personen, die ihn besuchen, nicht mehr, wie etwa Lévi-Strauss und Louis Dumont, oder er verwechselt sie mit anderen Menschen. Sein Bruder Henri zieht nach Paris, um sich vor Ort um Mauss und dessen Frau Marthe kümmern zu können. 1947 stirbt Marthe. Mauss bleibt allein mit seinem Bruder und leidet unter einer Bronchitis, an der er am 11. Februar 1950 schließlich verstirbt.


* Bibliographie

#+cite_export: csl /home/cpsoz/Github/reclam/soziologiemagazin.csl
#+print_bibliography:

* Footnotes

[fn:1] Vgl. [cite/t/b:@Benthien2021 495], Brief 407 vom 25.07.1923; ebd., 496, Brief 408 vom 9.08.1923.

[fn:2] Ebd., S. 484, Brief 396 vom 31.07.1922.

[fn:3] Ebd., S. 496, Brief 408 vom 9.08.1923.

[fn:4] Vgl. [cite:@Hertz2007].

[fn:5] Vgl. [cite:@Paoletti2012b 345].

[fn:6] Vgl. [cite:@Paoletti2012b 354f.]. Dazu auch vgl. [cite:@Hertz2007 211], in dem Hertz vom /homo duplex/ spricht.

[fn:7] Vgl. [cite:@Mauss1926 109].

[fn:8] Vgl. [cite:@Mauss1921 36], der Boas unmittelbar als seine Quelle zum /potlatch/ erwähnt.

[fn:9] Vgl. [cite:@Davy1922].

[fn:10] Vgl. [cite:@Besnard1985].

[fn:11] Ebd., S. 248.

[fn:12] Ebd.

[fn:13] Ebd.

[fn:14] Vgl. [cite:@Benthien2021 478-479], Brief 301 vom 26.03.1922.

[fn:15] Vgl. [cite:@Besnard1985 252].

[fn:16] Ebd., S. 254.

[fn:17] Vgl. [cite:@Mauss1974b].

[fn:18] Vgl. [cite:@Mauss2012c 291].

[fn:19] Vgl. [cite/t/b:@Benthien2021 444], Brief 358 vom 21.01.1919.

[fn:20] Vgl. [cite:@Fournier2007 258].

[fn:21] Ebd., S. 449, Brief 362 vom 3.10.1919.

[fn:22] Ebd., S. 447, Brief 360 vom 19.10.1919.

[fn:23] Ebd., S. 454, Brief 366 vom 6.10.1920.

[fn:24] Dieses Nachwort basiert teilweise auf überarbeitete Fassungen der Kapitel eins, drei und vier aus unsere Einführung zu Marcel Mauss in [cite:@PapilloudRol2025].

[fn:25] Vgl. [cite:@Fournier2007 157].

[fn:26] Vgl. [cite:@Besnard1987 76].

[fn:27] Vgl. [cite:@Fournier2007 513].

[fn:28] Vgl. [cite:@Besnard1979 17ff.]

[fn:29] Vgl. [cite:@Dumont1991 201; @Moebius2012 629-643].

[fn:30] Vgl. [cite:@Fournier1994 149].

[fn:31] Vgl. [cite:@Paoletti2012b 301].

[fn:32] Vgl. [cite:@Pickering1979 163].

[fn:33] Vgl. [cite:@Fournier2007 463; @Cabanel2017].

[fn:34] Vgl. [cite:@Tarot2003; @Fournier1994].

[fn:35] Vgl. [cite:@Sembel2015b 10].

[fn:36] Vgl. [cite:@Fournier2007 545, Fn. 3].

[fn:37] Vgl. [cite:@Lukes1973 327; @Moebius2006 114f.]

[fn:38] [cite:@Mausspr1898 2; @Mausspr1899 2; @Mausspr1899b 3-4].

[fn:39] Vgl. [cite:@Maussprorgsyndic-1-1899 4; @Maussprorgsyndic-2-1899 3; @Maussprorgsyndic-3-1899 3; @Maussprorgsyndic-4-1899 3; @Maussprorgsyndic-5-1899 4].

[fn:40] Vgl. [cite:@Mauss1997 72-82].

[fn:41] Vgl. [cite:@Maussprgen1900 1].

[fn:42] Vgl. [cite:@GeraultRichardprgen-2-1900 1].

[fn:43] Vgl. [cite:@Guillemin-1900 3].

[fn:44] Vgl. [cite:@Longuet-1900 2].

[fn:45] Vgl. [cite:@Longuet-2-1900 2; vgl. auch @Maussunioncoop1900 4].

[fn:46] Vgl. [cite:@Longuet-1900 2].

[fn:47] Vgl. [cite:@Hamelin-1-1900 3].

[fn:48] Ebd.

[fn:49] Vgl. [cite:@Hamelin-2-1900 2].

[fn:50] Ebd.

[fn:51] Vgl. [cite:@NN-1901-4 4].

[fn:52] Vgl. [cite:@NN-1901-1 3].

[fn:53] Vgl. [cite:@NN-1901-2 4; @NN-1901-3 4; @NN-1902-1 4; @NN-1902-2 4; @NN-1902-3 4].

[fn:54] Vgl. [cite:@Guillemin1905 6]

[fn:55] Vgl. [cite:@Cuin1997 12f.; @Karsenti1997 63ff.]

[fn:56] Vgl. [cite:@Mauss1990 176].

[fn:57] Vgl. [cite:@Namer1977; @Paoletti2012].

[fn:58] Vgl. [cite:@Robertson2003 142].

[fn:59] Vgl. [cite:@Paoletti1998 111f.].

[fn:60] Vgl. [cite:@Fournier2007 587].

[fn:61] Vgl. [cite:@Besnard1979 19ff.].

[fn:62] Ebd., S. 23-24.

[fn:63] Vgl. [cite:@Fournier2007 705].

[fn:64] Vgl. [cite:@Schuettpelz2017 118; @Hsu2017 91f.]

[fn:65] Vgl. [cite:@Mausscoop1902 5].

[fn:66] Vgl. [cite:@Clark1972 171].

[fn:67] Vgl. [cite:@Mausshuma-1-1904 8].

[fn:68] Vgl. [cite:@Mausshuma-3-1904 1].

[fn:69] Vgl. [cite:@Mausshuma-2-1904 4].

[fn:70] Ebd.

[fn:71] Vgl. [cite:@Mausshuma-4-1904 4].

[fn:72] Vgl. [cite:@Mausshuma-3-1904 1].

[fn:73] Vgl. [cite:@Mausshuma-5-1904 3].

[fn:74] Vgl. [cite:@Mausshuma-1-1905 4].

[fn:75] Vgl. [cite:@Mausshuma-2-1905 4].

[fn:76] Vgl. [cite:@Mausshuma-3-1905 3].

[fn:77] Vgl. [cite:@Gaumont1923 189].

[fn:78] Ebd., S. 361.

[fn:79] Vgl. [cite:@Guilleminhuma-1-1906 1].

[fn:80] Vgl. [cite:@NNcoop-1905].

[fn:81] Vgl. [cite:@NNcoop-1910 5; @NNcoop-1911 5].

[fn:82] Vgl. [cite:@NNcoop-1912 5].

[fn:83] Vgl. [cite:@Benthien2015 209ff.].

[fn:84] Vgl. [cite:@Fournier1994 322].

[fn:85] Ebd., S. 329f.

[fn:86] Vgl. [cite:@Sembel2015b 17].

[fn:87] Vgl. [cite:@Fournier1994 374].

[fn:88] Vgl. [cite:@Fournier1994 417].

[fn:89] Vgl. [cite:@Steiner2005 203ff.].

[fn:90] Vgl. [cite:@Fournier2007 865].

[fn:91] Vgl. [cite:@Crawford2005 142].

[fn:92] Vgl. [cite:@PVCAL1919 3-9].

[fn:93] Vgl.[cite:@Hallays1919 242; @Craig1984 406].

[fn:94] Vgl. [cite:@Becker2003 179].

[fn:95] Vgl. [cite:@Craig1979 9].

[fn:96] Vgl. [cite:@Bloch1933 551].

[fn:97] Ebd.

[fn:98] Vgl. [cite:@Blum1992 32].

[fn:99] Vgl. [cite:@Craig1984 204].

[fn:100] Vgl. [cite:@CongresTours1912; @Petot1914].

[fn:101] Vgl. [cite:@CongresParis1919].

[fn:102] Vgl. [cite:@CongresMarseille1922 194].

[fn:103] Ebd., S. 196.

[fn:104] Vgl. die Erwähnung von Mauss als Mitglied der Hauptmitarbeiter von /L'Avenir/ in [cite:@Siecle1916, 2; @Action1916, 3].

[fn:105] Vgl. [cite:@Aurore1913 4].

[fn:106] Vgl. Dieser Brief wird in extenso in [cite:@VieSoc07081920, 1] abgedruckt; vgl. auch [cite:@Erenouvelle1920, 5] und [cite:@PetitProvencal1920, 1].

[fn:107] Vgl. [cite:@RF1920 1-2].

[fn:108] Vgl. [cite:@Fournier1994 445].

[fn:109] Vgl. [cite:@Viesocialiste1922 3]

[fn:110] Vgl. [cite:@Viesocialiste1923 4].

[fn:111] Vgl. den Artikel von Séverac "Concours pour la paix!" (Wettbewerb für den Frieden!) und den Artikel von Mauss "L'Inflation rentière -- La Dette flottante"  (Die Rentierinflation -– Die schwebende Verschuldung) in [cite:@Populaire18041924, 1].

[fn:112] Vgl. [cite:@Mauss1924 2].

[fn:113] Vgl. [cite:@Mauss2012b 213].

[fn:114] Ebd., S. 212.

[fn:115] Ebd., S. 214.

[fn:116] Vgl. [cite:@Mauss2010 27].

[fn:117] Ebd., S. 46.

[fn:118] Ebd., S. 36.

[fn:119] Ebd., S. 49.

[fn:120] Ebd., S. 84, Anm. 206.

[fn:121] Ebd., S. 62.

[fn:122] Ebd., S. 83f., Anm. 205.

[fn:123] Ebd., S. 115f.

[fn:124] Ebd., S. 52.

[fn:125] Ebd., S. 15.

[fn:126] Ebd., S. 17.

[fn:127] Ebd., S. 68, Anm. 138.

[fn:128] Ebd., S. 115.

[fn:129] Ebd., S. 47.

[fn:130] Ebd., S. 76f.

[fn:131] Ebd., S. 18f.

[fn:132] Ebd., S. 63.

[fn:133] Ebd., S. 80.

[fn:134] Ebd., S. 78.

[fn:135] Ebd., S. 69, Anm. 142.

[fn:136] Ebd., S. 14.

[fn:137] Ebd., S. 139.

[fn:138] Vgl. etwa [cite:@Firth1940;@Lefort1950;@Levistrauss2010;@Weiner1985].

[fn:139] Vgl. [cite:@Benthien2021 531], Brief 446 vom 21.12.1925.

[fn:140] Vgl. [cite:@viesocialiste_19201113].

[fn:141] Ebd., S. 3.

[fn:142] Ebd., S. 4.

[fn:143] Ebd.

[fn:144] Vgl. [cite:@Mallard2011; @Mallard2021].

[fn:145] Vgl. [cite:@Fournier2017 413].

[fn:146] Vgl. [cite:@Fournier1994 530ff.].

[fn:147] Vgl. [cite:@Kaesler1985 140ff.].

[fn:148] Vgl. [cite:@FondMauss-1].

[fn:149] Vgl. [cite:@ADBR-1].

[fn:150] Vgl. [cite:@Mueller2003 269], Brief von Marc Bloch an Lucien Febvre vom 04.07.1935.

[fn:151] Vgl. [cite:@FondMaussAllg], Brief von Halbwachs an Gurvitch vom 21.10.1935.

[fn:152] Ebd., S. Brief von Gurvitch an Mauss vom 15.04.1932.

[fn:153] Vgl. [cite:@Fournier1994 647, Anm. 2].

[fn:154] Vgl. [cite:@FondMaussAllg], Brief von Gurvitch an Mauss vom 08.04.1935.

[fn:155] Vgl. [cite:@FondMaussAllg], Brief von Gurvitch an Mauss vom 26.04.1935.

[fn:156] Vgl. [cite:@ADBR-2], Versammlung vom 04.07.1935.

[fn:157] Vgl. [cite:@Mueller2003 269], Brief von Marc Bloch an Lucien Febvre vom 04.07.1935.

[fn:158] Vgl. [cite:@Fournier1994 648].

[fn:159] Vgl. [cite:@FondMaussAllg], Brief von Mauss an den Dekan der literaturwissenschaftliche Fakultät vom 08.10.1935.

[fn:160] Vgl. [cite:@FondMaussAllg], Brief von Mauss an den Dekan der literaturwissenschaftliche Fakultät vom 07.10.1935

[fn:161] Vgl. [cite:@FondMaussAllg], Kopie des Briefes von Halbwachs an Gurvitch vom 21.10.1935.

[fn:162] Vgl. [cite:@Levi-Strauss1988 102-103].

[fn:163] Vgl. [cite:@Fournier1994 620, Anm. 3].

[fn:164] Vgl. [cite:@Moebius2006c; @Daermann2010].

[fn:165] Vgl. [cite:@Mauss2017 53].

[fn:166] Vgl. [cite:@Charbonnier1976 98].

[fn:167] Ebd., S. 103.

[fn:168] Ebd. 104.

[fn:169] Ebd., S. 107.

[fn:170] Vgl. [cite:@Mauss2017 94].

[fn:171] Ebd., S. 285.

[fn:172] Ebd., S. 94.

[fn:173] Ebd., S. 94-95.

[fn:174] Vgl. [cite:@Brubaker2005].

[fn:175] Vgl. [cite:@Mauss2017 38].

[fn:176] Ebd., S. 333.

[fn:177] Ebd., S. 337.

[fn:178] Ebd., S. 323.

[fn:179] Vgl. [cite:@Mauss2018 367]. Vgl. die entsprechende aber unpassend übersetzte Stelle in der deutschen Übersetzung, [cite:@Mauss2017 316].

[fn:180] Vgl. [cite:@Mauss2017 313].

[fn:181] Ebd., S. 288.

[fn:182] Ebd., S. 326.

[fn:183] Ebd., S. 91.

[fn:184] Ebd., S. 92.

[fn:185] Ebd., S. 217.

[fn:186] Ebd., S. 201.

[fn:187] Ebd., S. 342.

[fn:188] Ebd., S. 342-343.

[fn:189] Ebd., S. 344.

[fn:190] Ebd.
