* Kommentar

Wenn Mauss im Laufe Januar 1919 aus dem Kriegsdienst entlastet wird,[fn:1] fängt eine Zeit der schwierigen Rückkehr zum zivilen und akademischen Leben an, oder wie Mauss im Briefwechsel mit Henri Hubert mitteilt: "Ich bin gerade dabei, mich neu einzurichten, was nicht einfach ist. (...) Es muss mit einer relativ langen Rückkehr zur Barbarei gerechnet werden".[fn:2] Der Erste Weltkrieg ist beendet. Die Lust auf die Wiederaufnahme der wissenschaftlichen Arbeit ist vorhanden, und die Erwartungen sind groß. Schon im September 1919 fragen ihn die ehemaligen Kollegen,[fn:3] ob es nicht gut wäre, die Arbeit an /L'Année sociologique/ der Zeitschrift für Soziologie der Mitarbeiter um Emile Durkheim und Marcel Mauss, die nach 1912 nicht mehr veröffentlicht wurde, wieder aufzunehmen. Und die alten sozialistischen Kameraden der Genossenschaftsbewegung müssen auch nicht vergessen werden, sowie die persönlichen Projekten, die in dieser Zeit vielleicht mehr als vor dem Anfang des Krieges an erneuter Bedeutung gewonnen haben -- dabei insbesondere das Projekt von einem Buch zum Thema der Nation, davon Mauss mit einem kaum enthaltenen Enthusiasmus den schon halb abgeschlossenen Plan mit fortgeschrittenen verfassten Textteilen Hubert vorstellt.[fn:4] Es gibt so viel zu tun, um den Anschluss an die Ideen vor 1914 wieder zu finden, so viele Leute zu treffen, davon nicht wenige ihr Leben auf dem Schlachtfeld verloren haben. Darunter zählt man eine große Anzahl an ehemaligen Studenten und Freunden von Mauss, die für die /Année/ gearbeitet haben oder mit Mauss in der Unterstützung des Sozialismus in Frankreich gewirkt haben. Von diesem Übergang aus den Trümmern des Krieges ins neue freie Leben bezeugt Mauss' /Gift, Gift/ in seiner Form und in seinem Inhalt, in der Verbindung zwischen dem Text und seinem Intertext.

Wann genau Mauss /Gift, Gift/ verfasst, kann nicht mit Sicherheit ermittelt werden. Wahrscheinlich wurde der Text in den Jahren 1922-1923 für die Veröffentlichung in der Festschrift für Charles Andler vorbereitet. Aber es bleibt fraglich, ob ihn Mauss speziell für diese Angelegenheit vorbereitet oder schon früher bzw. vor dem Krieg verfasst hat. Einerseits erkennt man in /Gift, Gift/ die Themen, die Mauss in seiner jungen Karriere mit Hubert herausgearbeitet hat. Es geht um die magischen und religiösen Phänomenen verschiedener Ländern und Kulturen auf den fünf Kontinenten mit besonderer Berücksichtigung der melanesischen Inseln in der Pazifik, der Indianerstämmen Nordamerikas, der alten indoeuropäischen Gesellschaften. Andererseits geht es gleichzeitig auch um dieses Phänomen der Gabe, dem Mauss nicht fremd ist, weil er es immer wieder in seinen ehemaligen Arbeiten trifft. Vielleicht gäbe es Möglichkeiten, ein solches Phänomen wie die Gabe im Rahmen der neuen Betrachtung der Arbeiten mit Hubert zur Magie zu vertiefen, wie ihm Hubert vorschlägt,[fn:5] oder im Rahmen neuer Überlegungen zum unvollendeten Gebettext einzubeziehen,[fn:6] den Mauss vor dem Ersten Weltkrieg zu einer Dissertation anfertigen wollte. Andererseits gehört /Gift, Gift/ zu diesen Texten, die schnell fertig geschrieben werden müssen, weil Mauss nach fast einem Jahr Lugenkrankheit (vom Oktober 1921 bis August 1922) mehr denn je die wichtigeren Projekte zum erfolgreichen Ende bringen will,[fn:7] die bis jetzt warten mussten, nämlich sein geplantes Buch zum Thema der Nation und die Nachfolge von /L'Année sociologique/. In diesem Sinne ist /Gift, Gift/ an der Schnittstelle zwischen der Vergangenheit und der Gegenwart Mauss' Biobibliographie, und er verweist entsprechend auf verschiedene Überlegungen im Rahmen der Arbeiten von Mauss, die weiter über die zentrale Botschaft von diesem Text gehen -- Gaben sind ambivalent bzw. sind Geschenke sowie gleichzeitig Giftstoffe -- und im späteren Essay /Die Gabe/ (1925) weiter entwickelt werden. Im Folgenden kommen wir zur Erklärung dieser inhaltlichen Überlegungen, wie sie vom Anfang bis Ende des Textes auftauchen.

/Gift, Gift/ fängt mit der Erwähnung der zwei Bedeutungen von Gift als Geschenk und Giftstoff an, wobei die Verbindung zwischen beiden Begriffen auf Deutsch, Englisch und Holländisch nicht eindeutig geklärt ist. Weil ihn die Literatur zum Wort "Gift" nicht zufriedenstellt, schlägt Mauss eine Hypothese vor: Die Bedeutungen von "Geschenk" und "Giftstoff" wurden im Wort "Gift" miteinander verbunden, um die Bedeutung von Gift als Giftstoff abzumildern bzw. um die Gefahr, die die Bedeutung vom Wort "Gift" als Giftstoff enthält, zu dämpfen und die Verwendung des Wortes zu gewähren. In diesem Zusammenhang findet man eine unmittelbare Verbindung zu den Arbeiten vom Studenten und Freunden Mauss' Robert Hertz (1881-1915) insbesondere in Bezug auf die religiöse Polarität und die Sühne in den alten Gesellschaften.[fn:8] Hertz ist nicht nur der Kameraden im Rahmen des politischen Engagements im Sozialismus an der Seite von Mauss. Er ist auch derjenige, davon Mauss wie Durkheim dachten, dass er die Zukunft der Durkheim-Schule darstellen würde.[fn:9] Insbesondere mit seiner Studie zur Vorherrschaft der rechten Hand gibt Hertz Durkheims These der Dualität im Menschen neue Dimensionen. Nach Durkheim ist der Mensch ein /homo duplex/ in diesem Sinne, dass er zwei Bewusstseinzustände einverleibt.[fn:10] Der erste Bewusstseinzustand führt zur Entwicklung einer individuellen Persönlichkeit und der zweite Bewusstseinszustand zur Entwicklung einer sozialen Bewusstsein. Nach Durkheim setzt diese Dualität im Menschen die grundsätzlichere Dualität zwischen dem Sakralen und dem Profanen voraus: Die zwei unterschiedlichen Bewusstseinszustände sind aus dieser grundsätzlichen Unterscheidung zwischen dem Sakralen und dem Profanen entstanden. Hertz verallgemeinert diese These Durkheims insofern, als er die innerliche Dualität im Menschen auf die Ebene einer Dualität zwischen Natur und Gesellschaft bringt. Einerseits gibt es profane Gegenstände, die gleichzeitig symbolisch mit dem Bösen, dem Schlechten, dem Unreinen assoziiert werden, die allesamt Merkmale sind, die mit der linken Hand verbunden sind. Andererseits gibt es das Gegenteil bzw. das Sakrale, das gleichzeitig das Gute, das Reine, das Richtige, die mit der rechten Hand assimiliert werden. Diese Dualität innerhalb vom Menschen spiegelt sich außerhalb von ihm in der Form von Klassifikationssystemen wider, die auf die alltäglichen Gegenstände sowie in der Aufteilung des Raumes und der Zeit, der sozialen Rollen und Berufen, in der Hierarchisierung der Götter und der Teilung der Geschlechter und der Generationen verwendet werden. Wie Mauss in /Gift, Gift/ sagt, die Vielfalt der Gaben ruht auf einem breiten Spektrum an Bedeutungen zwischen dem Sakralen und dem Profanen, davon sie jeweils einen Aspekt des asymmetrischen Verhältnisses zwischen diesen Polaritäten bezeichnen, weil die Gaben immer an diese untrennbare Unterscheidung zwischen dem "Geschenk" und dem "Giftstoff" verweisen, die die untrennbare Beziehung zwischen dem Sakralen und dem Profanen im Alltag der Austauschpraktiken in diesen Gesellschaften der Gabe übersetzt. Zusammen betrachtet, bilden diese Gaben eine Totalität von Dienstleistungen, die an die Totalität der Gesellschaft erinnert, die unmittelbar oder mittelbar an solchen Dienstleistungen teilnimmt.

Deshalb spricht Mauss in /Gift, Gift/ von der Gaben als totale Leistungen. Mit dem Begriff der Leistung verdeutlicht er das rechtliche Merkmal der Gaben: Gaben werden als Folge der Schließung von einem Vertrag getätigt. Mit dem Attribut "total" sagt Mauss, dass diese Leistungen alles betreffen, was in Unterstützung von Dritten getan werden kann. In einem späteren Text erklärt Mauss: "eine Gruppe von Menschen, ob hierarchisch organisiert oder nicht, schuldet einer bestimmten Anzahl anderer Menschen, Verwandten oder Verbündeten, die einen symmetrischen Platz beziehen (übergeordnet oder gleichwertig oder untergeordnet oder unterschiedlich aufgrund des Geschlechts), eine ganze Reihe moralischer und materieller Leistungen (Dienste, Frauen, Männer, militärischer Hilfe, ritueller Speisen, Ehren, usw.), und sogar die ganze Reihe dessen, was ein Mensch für einen anderen tun kann. Im Allgemeinen werden diese totalen Leistungen von Klan zu Klan, von Altersklasse zu Altersklasse, von Generation zu Generation, von Verbündeten zu Verbündeten erbracht. (...) Im Allgemeinen erfolgen diese Leistungen innerhalb dieser Gruppen und von Gruppe zu Gruppe entsprechend dem Rang der einzelnen Personen".[fn:11] In /Die Gabe/ spricht Mauss von einem "System" der totalen Leistungen, und mit diesem Begriff "System" unterstreicht er zwei Merkmale der Gaben: a) die Gaben bilden in den unterschiedlichen Gesellschaften eine Einheit von sozialen Leistungen, die mehr oder weniger homogen sind und sich von anderen gesellschaftlichen Praktiken unterscheiden; b) diese Einheit entsteht aus der (unmittelbaren oder mittelbaren) Integration aller Menschen einer sozialen Gruppe bzw. einer Gesellschaft in die Gabenpraktiken. Mit dem ersten Merkmal sagt Mauss, dass Gabenpraktiken in der Gesellschaft nicht ständig stattfinden, sondern es gibt Bedingungen, die erfüllt werden müssen, damit Gabenpraktiken entwickelt werden. Diese Bedingungen spiegeln sich in der Vielfalt der Namen von Gaben wider, die geleistet werden, und sie verorten diese Gaben in der Vielfalt der Praktiken in einer Gesellschaft. Etwa die Mitgift, die Mauss in /Gift, Gift/ erwähnt, bezeichnet im Allgemeinen das Heiratsgut der Braut an die Familie des Bräutigames, das in der Hochzeitzeremonie mitgegeben wird. Die Morgengabe ist eine nähere Bezeichnung der Mitgift als das Heiratsgut der Braut, das am Morgen vor der Hochzeitzeremonie geleistet wird. Mit dem zweiten Merkmal verdeutlicht Mauss, dass die Gabenpraktiken eine Wirkung auf den Zusammenhalt der Gesellschaft haben, den sie stärken. Weil die Gabenpraktiken alle Menschen in einer Gesellschaft direkt oder indirekt einbeziehen, tragen sie entsprechend zur engeren gesellschaftlichen Kohäsion, die die Wirkung auf die Akteure in dieser Gesellschaft hat, dass sie ihre Gesellschaft als Einheit aus der Praxis der Gaben besser wahrnehmen können, sie sich besser vorstellen können.

Lien avec la thèse de l'homo duplex et la nécessité de reconnaître où on se trouve entre le sacré et le profane, de comprendre les dimension de la vie sociale qui résulte de là où on se trouve entre le sacré et le profane, et donc de comment corriger et ajuster la vis sociale pour la péréniser.




** prestations totales, intégration de la totalité au sein des pratiques de dons

** le don agonistique, le potlatch, le lien germains, celtes, amérique du nord, mélanésie

** la polémique avec Davy et la foi jurée

** le spectre des dons entre interdiction et permission, comme modulation du tabou

** l'importance des objets qui lient, l'assymétrie et le pouvoir de la chose sur le receveur du don

** la forte ambivalence de gift dans le droit germanique qui se présente sous la forme d'un cadeau mais peu se retourner immédiatement en poison (l'exemple des gift-getränke)

** la communication de cette ambivalence aux autres objets qui entre dans ce type de contrat, et par conséquent à ce type de contrat entre confiance/méfiance, défis/engagement -- le lien (Bund) n'est jamais loin du déliement

** présence de cette ambivalence dans tout ce qui touche la magie par la potion magique -- lien avec les dons de boissons, les plus ambivalent (alles fliesst)

** la conclusion qui rappelle l'étendu du phénomène (Mélanésie, Amerique du Nord, Europe), un phénomène conservé jusque dans nos sociétés contemporaine qui se voit au malaise que nous éprouvons lorsque nous recevons des cadeaux

** le rappelle que ces phénomènes renvoie à l'obligation de rendre les présents qui sera l'un des grands thème de l'Essai sur le don

* Footnotes

[fn:11] Vgl. [cite:@Mauss1926 109].
[fn:10] Vgl. [cite:@Paoletti2012b 354f.]. Dazu auch vgl. [cite:@Hertz2007 211], in dem Hertz vom /homo duplex/ spricht.

[fn:9] Vgl. [cite:@Paoletti2012b 345].
[fn:8] Vgl. [cite:@Hertz2007].

[fn:7] Ebd., 496, Brief 408 vom 9.08.1923.
[fn:6] Ebd., 484, Brief 396 vom 31.07.1922.

[fn:5] Ebd., 495, Brief 407 vom 25.07.1923; ebd., 496, Brief 408 vom 9.08.1923.
[fn:4] Ebd., 454, Brief 366 vom 6.10.1920.

[fn:3] Ebd., 447, Brief 360 vom 19.10.1919.
[fn:2] Ebd., 449, Brief 362 vom 3.10.1919.

[fn:1] [cite:@Benthien2021 444, Brief 358 vom 21.01.1919]


#+bibliography: Mauss-Bib.bib
