#+Setupfile: /home/cpsoz/OrgTemplates/odt-fr.org

* gift-gift (1924)[fn:1]

Les deux sens "cadeau" et "poison", dans lesquels ce mot unique a divergé dans les différentes langues germaniques, semblent si éloignés l’un de l’autre que les étymologistes ont peine à s’expliquer le passage de l’un à l’autre et leur commune origine. La destinée même du mot varie suivant les langues, le sens de poison étant presque le seul conservé en allemand moderne, le sens de cadeau et don étant le seul conservé en anglais, le hollandais ayant deux mots l’un neutre, l’autre féminin pour désigner l’un le poison, l’autre le cadeau, la dot.  Ici, un sens s’est effondré, là un autre, et nulle part la dérivation sémantique n’est claire. Autant que je vois dans les grands dictionnaires étymologiques de l’allemand et de l’anglais, le Murray et le Kluge[fn:2], aucune explication satisfaisante n’en a été donnée. Les importantes remarques de M. Hirt à propos de l’allemand /gift/ doivent cependant être notées[fn:3]. Il est évident en effet que gift "poison" est un euphémisme et provient d’un tabou du mot qu’on craignait d'employer: tout comme en latin /venenum/ correspond à /* venesnom/ "Liebestrank". Mais pourquoi est-ce le mot /gift/ et l’idée de don qu'il évoque qui ont justement été choisis pour symboles du poison? C’est ce qui reste à expliquer.

Or, pour le sociologue et pour l’historien du droit germanique, la filiation des sens n’offre aucune difficulté.

Pour éclairer le sujet, qu’on nous pardonne d'indiquer quelques principes encore trop peu vulgarisés pour n’avoir pas besoin d’être exposés à nouveau.

**

Dans le monde germanique a fleuri à un haut degré le système social que j’ai proposé d’appeler "système des prestations totales". Dans ce système non seulement juridique et politique, mais encore économique et religieux, les clans et les familles et les individus se lient au moyen de prestations et de contre-prestations perpétuelles et de toutes sortes, d’ordinaire engagées sous forme de dons et de services, religieux ou autres, gratuits[fn:4].

Après avoir longtemps cru que ce système n’était très général que dans les sociétés arriérées, nous en constatons maintenant l’existence dans une bonne partie des anciens droits des sociétés européennes[fn:5]. En particulier les groupes dont se composent les anciennes sociétés germaniques se lient par les mariages, par les brus et gendres, par les enfants issus dans les deux lignes, utérine et masculine, les neveux, cousins, grand-père et petit-fils élevés les uns chez les autres et nourris les uns par les autres, servis les uns par les autres[fn:6], etc. -- par les services militaires et les initiations, intronisations et les festins qu’elles provoquent; -- par les morts, les repas funéraires et les successions, les usufruits, le retour de dons qu’elles entrainent; -- par les dons gracieux, les prêts usuraires rendus ou à rendre. Un incessant circulus des biens et des personnes confondus, des services permanents et temporaires, des honneurs et des fêtes données et rendues et à rendre; voilà comment il faut se figurer une bonne partie de la vie sociale des anciens peuples de Germanie et de Scandinavie.

D'autres sociétés européennes anciennes, par exemple les Celtes, ont plus particulièrement développé d’autres éléments de ces rites et de ces droits anciens. Le thème de la rivalité, celui du combat singulier, celui de l’émulation à coups de dépenses somptuaires, des défis et des tournois a été pour ainsi dire exaspéré en pays gaulois, gallois et irlandais[fn:7]. Ces sociétés pratiquent nettement cette forme de prestations totales à type agonistique auxquelles nous avons proposé de donner le nom de "potlatch" emprunté au chinook et au sabir des traitants et des Indiens d'Amérique et sur le côté juridique de laquelle M. Davy a attiré l’attention[fn:8]. On sait que ces formes sont fort développées dans le Nord-Ouest américain et en Mélanésie. Le potlatch proprement dit n’est pas étranger non plus aux mœurs des anciens Germains et des Scandinaves.

Mais ce qui est le plus intéressant à étudier chez ceux-ci, c’est le don, le gage. En effet, la /Gabe/, la ou le /gift/, le présent y apparait en traits plus particulièrement développés, plus apparents que dans bien d’autres types de sociétés et surtout que dans d’autres sociétés indo-européennes. L’allemand, en particulier a tout une gamme extrêmement riche de mots et de mots composés pour en exprimer toutes sortes de nuances depuis /Gabe/ et /Mitgift/ jusqu’à /Morgengabe/, /Liebesgabe/, /Abgabe/ et à la si curieuse /Trotzgabe/.

**

Or, dans toutes ces nombreuses sociétés, à toutes sortes de degrés de civilisation, en droit maori en particulier, ces échanges et ces dons de choses qui lient les personnes s’opèrent à partir d’un fonds commun d’idées: la chose reçue en don, la chose reçue en général engage, lie magiquement, religieusement, moralement, juridiquement, le donateur et le donataire. Venant de l’un, fabriquée ou appropriée par lui, étant de lui, elle lui confère pouvoir sur l’autre qui l’accepte. Au cas où la prestation donnée ne serait pas rendue dans la forme juridique, économique ou rituelle, prévue, le donateur a barre sur celui qui a participé au festin et en a absorbé les substances, sur celui qui a épousé la fille ou s’est lié par le sang, sur le bénéficiaire qui use chez lui d’une chose enchantée de toute l’autorité du donateur.

La chaine de ces idées est particulièrement claire dans les droits et les langues germaniques, et l’on voit facilement comment les deux sens du mot /gift/ s’y insèrent. En effet, la prestation type, chez les anciens Germains et Scandinaves, c’est le don de boisson[fn:9], de bière; en allemand, le présent par excellence[fn:10], c’est ce que l’on verse (/Geschenk/, /Gegengeschenk/). Inutile d’évoquer ici un nombre très grand de thèmes de droit et de mythologie germaniques. Mais on le voit: nulle part l’incertitude sur la nature bonne ou mauvaise des cadeaux n’a pu être plus grande que dans des usages de ce genre où les dons consistaient essentiellement en boissons bues en commun, en libations offertes ou à rendre. La boisson-cadeau peut être un poison; en principe, sauf sombre drame, elle ne l'est pas; mais elle peut toujours le devenir. Elle est toujours en tout cas un charme (le mot gift a gardé ce sens en anglais) qui lie à jamais les communiants et qui peut toujours se retourner contre l’un d’eux s’il manquait au droit. La parenté de sens qui lie gift-cadeau à gift-poison est donc facile à expliquer et naturelle.

Il y a d’ailleurs d’autres mots appartenant à ce système de droit qui ont également, en pays germanique, cette ambiguïté. Le gage, en droit ancien, correspondait, lui aussi, à cet enchantement réciproque. M. Huvelin, dans un mémoire classique[fn:11], a soupçonné autrefois, dans cet échange magique, l’origine du lien de droit, comparable au nexum latin. Précisons. Le gage, /wage/, /-wadium/, /vadi/, qui lie le maître et le serviteur, le prêteur et le débiteur, l’acheteur et le vendeur est chose magique et ambiguë. Il est à la fois bon et dangereux; on le jette aux pieds du contractant dans un geste de confiance et de prudence, de défiance et de défi à la fois. Chose curieuse, c’est encore là la façon la plus solennelle d’échanger chez les hardis navigateurs et commerçants des îles mélanésiennes des Trobriands[fn:12]. Et voilà pourquoi l’on dit encore en anglais: /throw the gage/, pour jeter le gantelet.

D'ailleurs, toutes ces idées sont à deux faces.  Dans d’autres langues indo-européennes, c’est la notion de poison qui est incertaine. Kluge et les étymologistes ont le droit de comparer la série /potio/ "poison" et /gift/, /gift/. On peut encore lire avec intérêt la jolie discussion d’Aulu-Gelle[fn:13] sur l'ambiguïté du grec φáρμακον et du latin /venenum/. Car la /Lex Cornelia de Sicariis et Veneficis/, dont Cicéron nous a heureusement conservé la "récitation" même, spécifie encore /verenum malum/[fn:14]. Le breuvage magique, le charme délicieux[fn:15], peut être bon ou mauvais. Φθτρον grec n’est pas non plus un terme nécessairement sinistre, et la boisson d’amitié, d’amour, n’est dangereuse que si l’enchanteur le veut.

**

Ces déductions ne sont qu’un développement technique et philologique à propos d’un seul fait qui ne sera que mentionné plus tard. Car il fait partie de tout un ensemble d'observations empruntées à toutes sortes de droits, de magies, de religions et d'économies de toutes sortes de sociétés, depuis les Mélanésiennes et Polynésiennes et Nord-Américaines jusqu’à notre morale. À ce propos et sans sortir du domaine des germanistes, on peut aussi rappeler qu’un des essais d’Emerson: /On Gifts and Presents/[fn:16] marque fort bien l’agrément et le désagrément que nous ressentons encore à recevoir des cadeaux. On trouvera l’exposé de tous ces faits dans un travail sur "l'obligation à rendre les présents" qui sera publié dans le premier fascicule de la nouvelle série de /l’Année sociologique/.

* Footnotes

[fn:1] /Extrait des Mélanges offerts à Charles Andler par ses amis et ses élèves/, Istra, Strasbourg.

[fn:2] Kluge sent qu’il a dû se passer pour ces mots la même chose que pour vergeben, vergiften. /Etymol. Wörterb./ 1915, p. 171.

[fn:3] /Etymol. d. neuhochd. Sprache/, 1909, p. 297. Le rapprochement de Hirt avec la serie: got, /lubja/, vha, /luppi/ "Liebe-Zaubertrank" est également intéressant et fondé.

[fn:4] Pour une vue sommaire de ces questions, v. Davy, /Eléments de sociologie/, I, p. 156 sq.

[fn:5] Mauss. "Une forme archaïque de contrat chez les Thraces". /Rev. des études grecques/, 1921.

[fn:6] Je fais ici allusion au "fosterage" et autres coutumes du même type.

[fn:7] On trouvera dans un prochain numéro de la /Revue celtique/ des notes de M. Hubert et de M. Mauss, à ce sujet.

[fn:8] /La foi jurée/. (/Travaux de l’Année sociologique/.)

[fn:9] Von Amira, /Nordgermanisches Obligationenrecht/, II, 362, 363, et surtout Maurice Cahen, /La libation, Et. s. le vocabul. religieux/, etc., p. 58, etc.

[fn:10] Pour être complet il faudrait mentionner aussi les "paraphernaux" donnés par le mari à la femme dont Tacite décrit le circuit entre les familles, /Germanie/, 18 (dans une phrase d’ordinaire mal comprise mais cependant parfaitement claire).

[fn:11] "Magie et droit individuel", /Année sociologique/ 10, p. 30 sq.

[fn:12] V. B. Malinowski, /Argonauts of the Western Pacific/, Londres, 1922, p. 473, et surtout les belles photographies, pl. LXI, LXII et frontispice.

[fn:13] 12, 9 qui cite fort à propos Homère.

[fn:14] /Pro Cluentio/, 148. Au Digeste il est encore prescrit de spécifier de quel "venenum", "bonum, sive malum", il est question.

[fn:15] Si l’étymologie qui rapproche /venenum/ (v. Walde, /Lat. étymol. Wört/., ad. verb.) de Venus et de skr. /van/, /vanati/ est exacte, comme il est vraisemblable.

[fn:16] /Essays/, v. la 2e série.
